### ISSUE TITLE
Support react-native-sqlite-2

### ISSUE THREAD

**Issue by KshamaShrey** [microsoft/react-native-windows#10409]
### Module

react-native-sqlite-2

### Module repo url

https://github.com/craftzdog/react-native-sqlite-2

### Target Version

0.69

### Existing issue url

https://github.com/craftzdog/react-native-sqlite-2/issues/134

### Existing windows implementation?

- [X] Legacy/C# implementation

### Which app/customer is requesting this module?

We are trying to upgrade the react-native-windows application to the latest version.In our current react-native-windows version 0.59.0-rc.1,the above mentioned package works as expected.

### In what scenarios will this module be used?

To use local database for desktop applications

**Comment by chrisglein** [comment]
Based on [the diredtory](https://reactnative.directory/?search=sql&windows=true) this one should have current Windows support: https://github.com/andpor/react-native-sqlite-storage
It sounds like sqlite-2 exists because of problems with PouchDB in sqlite-storage. Is that the situation you're in? (I'm not familiar with any of that - just reading off the project's readmes)

If there's an [existing RNW version from pre 0.59](https://github.com/craftzdog/react-native-sqlite-2/tree/master/windows), AND there's [a reference implementation in sqlite-storage](https://github.com/andpor/react-native-sqlite-storage/tree/master/platforms/windows/SQLitePlugin), this should be something you can take a crack at updating and submitting a PR to that repo. It'd be adapting from the WPF C# to UWP C++, but with examples I'd imagine a lot of that code ports over.

**Comment by KshamaShrey** [comment]
@chrisglein Thank you  for the quick reply.We will try replacing the package with react-native-sqlite-storage and check the functionality.
Thank you.

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. If you would like to see this module supported on Fabric, please file an issue on the react-native-sqlite2 repo.
