### ISSUE TITLE
Unable to access sqlite from react native windows

### ISSUE THREAD

**Issue by biswajeet2k17** [microsoft/react-native-windows#10431]
I am using the 'react-native-sqlite-storage' module to fetch data from an existing sqlite db into a react-native windows application. I have followed the steps as mentioned for windows platform [here](https://github.com/andpor/react-native-sqlite-storage). But, I am not able to open database using the openDatabase() API. Although, it mentions that the module works for Windows, but looking at the parameters of the API and code, I see references to only iOS/Android. Does this library does not work for Windows application to access sqlite db? If not, which is the best library to use to access sqlite from react native in windows.

**Comment by chrisglein** [comment]
This library is supposed to work on Windows, and to my knowledge it's the [only sqlite library that supports Windows](https://reactnative.directory/?search=sql&windows=true) (See this thread: https://github.com/microsoft/react-native-windows/issues/10409). There is certainly more regular traffic on the [async-storage](https://github.com/react-native-async-storage/async-storage) library, if you don't specifically need sqlite. But if `sqlite-storage` isn't working for you then you should open an issue against the [react-native-sqllite-storage](https://github.com/andpor/react-native-sqlite-storage/issues?q=is%3Aissue+is%3Aopen) repo.

**Comment by MacKenzieHnC** [comment]
As an end user struggling with this very thing, I think the problem here is rooted in [people not understanding how to include the db file properly](https://github.com/andpor/react-native-sqlite-storage/search?q=windows&type=issues), which is not an issue with the sqlite module. Having no UWP or VS background, I have found the following questions nearly impossible to figure out:

- How do you build your file structure for a react-native-windows project so that your assets are included in the build? (Related to [this](https://github.com/microsoft/react-native-windows/issues/2220))
- Is VS required for including files or can it be done manually (there are several references to using VS to "include in project", but react-native-windows doesn't claim to require VS to function)
- Once you've included the file successfully, what directory do your URIs start from?

I've tried everything I could google my way to, but so far have been fully unsuccessful. Some additional documentation for these questions would be *greatly* appreciated

**Comment by chrisglein** [comment]
It sounds like what you're looking for and not finding is the information for how to include non-image files in a way that'll get bundled and included with your project. Does that sound correct?

**Comment by MacKenzieHnC** [comment]
> It sounds like what you're looking for and not finding is the information for how to include non-image files in a way that'll get bundled and included with your project. Does that sound correct?

Correct. I have now solved it, but finding it was a bit of a nightmare. Some easier-to-find documentation would be wonderful for the next poor soul.
