### ISSUE TITLE
Support react-native-maps

### ISSUE THREAD

**Issue by Gurpreet31-cpu** [microsoft/react-native-windows#10937]
### Module

react-native-maps

### Module repo url

https://github.com/react-native-maps/react-native-maps

### Existing windows implementation?

- [ ] Legacy/C# implementation

**Comment by chrisglein** [comment]
You left most of the fields from this form blank. Can you provide more detail on your need here?
Transparently, there is no dedicated team for adding Windows support to community modules. At most we try to collect information on which modules are most in demand (and why) in order to direct effort for those who are interested in doing the work.
