### ISSUE TITLE
Where are the releases for RN 0.43 & 0.44, and RC for 0.45 ?

### ISSUE THREAD

**Issue by jmcginty** [Microsoft/react-native-windows#1126]
It's been 10 weeks since we had any new releases or release candidates - this project is falling behind facebook react native. What is happening ?

**Comment by zerglingno1** [comment]
https://github.com/Microsoft/react-native-windows/releases

**Comment by jmcginty** [comment]
That is a great outcome, and looking forward to the 0.45 release. Whether it is fair or not, open source projects get judged by how 'active' the project is. I have invested a lot of time and effort in React Native Windows and want to see it succeed. My colleagues were deciding that it has been 'abandoned' based on lack of releases and activity, so you have to ask the question.

**Comment by matthargett** [comment]
Hi James! Activity can be shown in a number of ways, of course :) I've been responding to issues and merging PRs nearly every week for the past 2 months. 

The main difficulty was that 43 and 44 were upstream releases that did not work for a lot of people on other platforms, as well as RNW. It has taken us and upstream RN a while to stabilize things so we can responsibly do a release. This is the comment I've put into a few issues over the last weeks. I hope that next time there's questions about the viability of the project that you or your co-workers will ask in the Reactiflux channel or look at the activity feed :)

Hopefully things have turned a corner, but if you're using enzyme or similar popular test tools, they will break with anything based on RN 43 or newer due to upstream packaging of React 16 alpha. Unless there is a feature in 43+ you desperately need, I would advise waiting. Several teams shipping product have extracted new features like flat list into their own component so they can use them in 42.

I'm confident RN 46 will resolve most of these issues across all platforms.

**Comment by ndbroadbent** [comment]
@matthargett Thanks for the update (and for all your work on this!)

**Comment by rozele** [comment]
@jmcginty There seems to be a serious overhaul of the packager in react-native@0.44 (and potentially 0.45).  As a result, *.windows.js files are no longer being picked up correctly. I'm hoping to find a solution to this issue soon. https://www.facebook.com/groups/reactnativeoss/permalink/1683835541913073/

**Comment by jmcginty** [comment]
thanks for keeping us up do date @rozele , and welcome back :)

**Comment by rozele** [comment]
Thanks @jmcginty. I'll let the release candidates settle for a few days and then publish final releases, 0.44.0-rc.2 and 0.45.0-rc.0 are out.

**Comment by jmcginty** [comment]
Good on you
