### ISSUE TITLE
Rework Built-In DeviceInfo for Fabric

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#11414]
This comment exists within the playground-composition implementation and the new e2e-test-app-fabric implementation. Creating a work item to track tackling the fix for this so the workaround can be removed. 

See https://github.com/microsoft/react-native-windows/blob/1d2767e7ded6943ed7a4723d2d59186659afe011/packages/playground/windows/playground-composition/Playground-Composition.cpp#L145-L182 for source. 
// Work around crash in DeviceInfo when running outside of XAML environment
// TODO rework built-in DeviceInfo to allow it to be driven without use of HWNDs or XamlApps

**Comment by chiaramooney** [comment]
This work is more pressing as we will want this resolved before we create an app template for Fabric and launch an mvp to customers. Will not land in time for v0.72 but should definitely land by v0.73. Adding needs attention label so issue can be assigned to the right dev.

**Comment by YajurG** [comment]
Leaving backlog recommendation as placeholder - is this still planned for 0.73? @chiaramooney @marlenecota

**Comment by jonthysell** [comment]
This work is to extract the stubbed out DevideInfo module in the composition apps and have it load instead of the XAML-based paper module automatically.

It doesn't need to be in 0.73 but we do want apps to not have to manually include this module in-line in their app template, so it needs to be done before we build the app template.
