### ISSUE TITLE
Implement `react-native-windows-init` in `react-native.config.js`

### ISSUE THREAD

**Issue by szymonrybczak** [microsoft/react-native-windows#11510]
### Summary

Right now `react-native-windows-init` is implemented as [separate package](https://github.com/microsoft/react-native-windows/tree/main/packages/react-native-windows-init). But inside React Native CLI we've [plugins](https://github.com/react-native-community/cli/blob/main/docs/plugins.md), which allows to add new commands. Actually inside `react-native-windows` I can see that there's implemented `run-windows` command via `react-native.config.js`.
https://github.com/microsoft/react-native-windows/blob/06fbd58a8f9f8067f13500b4defe281a6282b0be/vnext/react-native.config.js#L13-L15
So it'll really good to unify this, and use `react-native.config.js` for the init command.

### Motivation

That's official API provided by RN CLI, and it'll also in some way future-proof to unify this.

### Basic Example

There's [documentation](https://github.com/react-native-community/cli/blob/main/docs/plugins.md) which provides all necessarily informations, how to do it correctly.

**Comment by jonthysell** [comment]
Interesting idea, but the `react-native-windows-init` script needs to add `react-native-windows` as a project dep in the first place, otherwise it's not there to be found by the plugin. In fact, that's all the script does - adds the correct RNW dep to the `package.json`, installs RNW, then hands off project creation (with params) to the generate-windows commands

Unless upstream CLI wants to either add windows projects alongside ios/android with `react-native init` at project creation time, or add a `windows-init` that does that for us, we need an independent command to get bootstrapped.

**Comment by szymonrybczak** [comment]
> Interesting idea, but the `react-native-windows-init` script needs to add `react-native-windows` as a project dep in the first place, otherwise it's not there to be found by the plugin. In fact, that's all the script does - adds the correct RNW dep to the `package.json`, installs RNW, then hands off project creation (with params) to the generate-windows commands

That's what you can get this done with plugins. 👍

> Unless upstream CLI wants to either add windows projects alongside ios/android with react-native init at project creation time, or add a windows-init that does that for us, we need an independent command to get bootstrapped.

Hm, actually I don't understand what you mean. Why do you need changes in RN CLI? Plugins can be implemented on RNW's side without any new changes in CLI.

**Comment by jonthysell** [comment]
It's a chicken and egg problem. `npx react-native-windows-init` is run on existing RN projects that **do not have** `react-native-windows` as a dependency in their `package.json`.

`npx react-native-windows-init`:

1. Parses the `package.json` to determine the correct version of RNW that goes with the version of RN being used
2. Calls `yarn add react-native-windows@{correctversion}` to install that version
3. Calls the `generate-windows` command contained in the newly installed `react-native-windows` project, in order to add the appropriate windows platform build files.

The RN CLI cannot see the RNW commands if RNW is not already added as a dependency. We do not want to require users to have to manually determine which version of RNW to install. It's just a one-time `npx react-native-windows-init` (no version specified) and they'll be set up correctly and ready to go.

The alternative would be for the CLI to support something like `npx react-native init-windows`, where the CLI does the work of adding `react-native-windows` to the `package.json` first if it's not present, then continuing with the command: i.e. the CLI installs the correct plugin then uses it. As far as I can tell that is not a supported feature of the CLI.

Please re-open if/when the CLI does support "installing plugins" and we can consider migrating to that.
