### ISSUE TITLE
Installing react-native-windows to react-native project initialized with yarn

### ISSUE THREAD

**Issue by sayar** [Microsoft/react-native-windows#1155]
When installing react-native-windows with node v8 & npm v5 into an existing react-native project, the react-native-cli reports no more commands except for init after `npm install rnpm-plugin-windows` succeeds.

**Comment by rozele** [comment]
Can't repro on Windows 10 - 
```
>node --version
v8.1.2
>npm --version
5.0.3
```

**Comment by rozele** [comment]
However, this does repro on Ubuntu

**Comment by rozele** [comment]
This seems to be an issue with trying to generate the RN iOS/Android project with yarn, but not using yarn for the windows packages.

**Comment by rozele** [comment]
I updated the title of the issue because this is definitely something we should look into. If the user initializes a react-native project when yarn is installed, the react-native-cli will use yarn to optimize the init process. If the user subsequently tries to follow our documentation and install rnpm-plugin-windows with npm, npm will uninstall quite a large number of dependencies (breaking react-native). Even if the user installs rnpm-plugin-windows with yarn, the `react-native windows` CLI command still depends on yarn.
