### ISSUE TITLE
add support for udp tcp

### ISSUE THREAD

**Issue by nolotus** [microsoft/react-native-windows#11776]
### Summary

Hopefully, someone will be able to provide a solution for react-native-windows 
tcp, udp, and related support.
The existing https://github.com/Rapsssito/react-native-tcp-socket/issues/157
A new one could be added as well.

### Motivation

Not all data is from http protocol, if there is support for tcp udp. It would be better.

### Basic Example

I can't write c++, so I won't add support for react-native-windows.

**Comment by chrisglein** [comment]
The documentation for writing native modules for windows is [here](https://microsoft.github.io/react-native-windows/docs/native-modules). Writing in C++ is [preferred](https://microsoft.github.io/react-native-windows/docs/native-code-language-choice), but C# is an option, if C++ isn't an option for you.

At this point we prefer that these issues are tracked on the repo of the module itself, rather than here on the core Windows platform repo. So we'll let that other bug track this request. Through the docs and through looking at other modules (and the built in networking module in this repo) there should hopefully be lots of examples to source from. In this case, it looks like it'd be adapting [this code](https://github.com/Rapsssito/react-native-tcp-socket/tree/master/android/src/main/java/com/asterinet/react/tcpsocket) to the [Windows equivalents](https://learn.microsoft.com/en-us/windows/uwp/networking/sockets).
