### ISSUE TITLE
Basic Interaction on Fabric

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#11900]
One of the most common patterns in UIA is Invoke and it enables Narrator’s primary interaction command on many controls (Narrator + Enter).  Implementing it would also allow navigation within a button-based test app in automated test scenarios.  Office and RNW Paper implement the invoke pattern differently.  Work at this stage will begin exploring scalable ways to introduce new patterns. 

| Task  | Description | Status
| -- | -- | --
onAccessibilityTap | Add support for the UIA Invoke method. This method should call onAccessibilityTap and onClick. | https://github.com/microsoft/react-native-windows/pull/11874

```[tasklist]
### Tasks
- [x] #11874
```

**Comment by chrisglein** [comment]
For reference, here's the Paper PR for [accessibilityActions](https://reactnative.dev/docs/text#accessibilityactions): https://github.com/microsoft/react-native-windows/pull/3475.
@YajurG @chiaramooney since this is defined as part of the Accessibility M0, can we have the remaining work here tracked with issues for planning?
