### ISSUE TITLE
Create borders lazily

### ISSUE THREAD

**Issue by antonkh** [Microsoft/react-native-windows#1195]
XAML Border elements can be created lazily to make things considerably faster. Here is a proof of concept: https://github.com/Microsoft/react-native-windows/compare/master...antonkh:lazy-borders-2

**Comment by matthargett** [comment]
This is cool! We've been talking about trying this for a while now. Do you have a Playground or app sample with before/after metrics? for both WPF and UWP?

**Comment by rozele** [comment]
Closed by #1261

**Comment by antonkh** [comment]
Merged to `master`.

**Comment by Kudo** [comment]
Reversing the Border / Canvas order, i.e.
```
<Canvas>
  <Border />
</Canvas>
```
makes WPF unable to do hit-test on pure View only touchable.
(But for UWP, works well for that case)

The test case is pretty simple.
```
<TouchableOpacity onPress={() => {}}>
  <View style={{ width: 100, height: 100, backgroundColor: 'red' }} />
</TouchableOpacity>
``` 

confirmed the test case is not worked at latest master branch code,
and works if I revert #1261's commit.

Any ideas if we could maintain the functionality for both WPF and UWP?

**Comment by rozele** [comment]
cc @kevinvangelder @pre10der89 any ideas why the lazy border change would affect WPF?

**Comment by antonkh** [comment]
I'm wondering if this is because Border is the first element in the Children collection. What if we move it to the end?

**Comment by Kudo** [comment]
@antonkh There is yet another simplified test case, as TouchableOpacity itself a View wrapper.
```
<TouchableOpacity
  onPress={() => {}}
  style={{ width: 100, height: 100, backgroundColor: 'red' }}
/>
```

For that case, Border is the only child in the collection.
Moving Border to the end cannot deal with such case.

**Comment by antonkh** [comment]
Perhaps in WPF the `Border` element is considered to be a valid hit test target, while in UWP it's excluded form the hit test traversal. Could you try to use the `IsHitTestVisible` property to exclude the borders?

**Comment by Kudo** [comment]
Not worked for setting `IsHitTestVisible` as well. (Neither true nor false).

FYI the hit test result if it helps.
The code snippet in [TouchHandler.cs](https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Net46/Touch/TouchHandler.cs#L227-L237)
```C#
            VisualTreeHelper.HitTest(
                _view,
                null,
                new HitTestResultCallback(
                    hit =>
                    {
                        var source = hit.VisualHit;
                        if (!source.HasTag())
                        {
                            return HitTestResultBehavior.Continue;
                        }
```

the `source` will be Border in each hit test iteration but will not be BorderedCanvas.
As we setup Tag in BorderedCanvas, we cannot find the view target in hit test result.
One alternative solution is trying to check the `source`'s parent in the hit test callback.
But I want to first clarify why BorderedCanvas cannot be included in hit test.

**Comment by antonkh** [comment]
The idea is to set `border.IsHitTestVisible=false` on the inner `Border`. `BorderedCanvas` should still be included in the hit test traversal.

**Comment by Kudo** [comment]
Simply setting the `border.IsHitTestVisible=false` is not worked as in original design, if a <View> has background color, the background will be filled with a Border and the Border is not hit-test visible, we cannot click on the View.

Please see my patch https://github.com/Microsoft/react-native-windows/compare/master...Kudo:fix/1195_wpf_not_touchable if it makes sense to set background directly on BorderedCanvas.
One benefit is now we could save a Border if a View only has background and no border.

**Comment by antonkh** [comment]
In most cases background can be set on Canvas. However if the view has rounded borders, the background has to be transferred to the Border.

**Comment by Kudo** [comment]
Well, I guess the root cause of WPF cannot click in current design is that the View's background color is filled by Border but not BorderedCanvas.
And in WPF, a view without color cannot be hit test, that's why BorderedCanvas is not in hit test.

A crazy POC in https://github.com/Microsoft/react-native-windows/compare/master...Kudo:fix/1195_wpf_not_touchable2 is just to add the same background color into the BorderedCanvas, and Touchable works fine.

**Comment by Kudo** [comment]
Thank, let me think if there are any alternative solutions to solve the rounded borders problem.

**Comment by antonkh** [comment]
"a view without color cannot be hit test" - that's a very interesting observation. Sounds like a bug in XAML. but I may be wrong. I should be able to find someone from their team who will tell if this is a bug or not.

As for the rounded corners problem, I happen to have a PR that addresses this - I was hoping to improve performance by saving a few XAML elements, but didn't get much and gave up that idea, but now there seem to be a good reason to give it a way. I'll send the PR shortly.

**Comment by antonkh** [comment]
The PR in question: https://github.com/Microsoft/react-native-windows/pull/1521

**Comment by Kudo** [comment]
I could not find any official documents to describe the design, just a little discussion at SO.
https://stackoverflow.com/questions/5344699/xnull-vs-transparent

I also take some time to dig into WPF's source code.
Visual's `GetHitTestBounds()` will just return `GetContentBounds()`, and `GetContentBounds()` is by default return empty rect.
To get a non-empty content bounds, one common way is to setup a Brush.
https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Media/Visual.cs,1903
https://referencesource.microsoft.com/#q=getcontentbounds
That might be the reason of WPF only do hit test for View with color.
Please also let me know if you have further information from WPF team.

One thing to mention is that even transparent color is okay for hit test.
See https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/hit-testing-in-the-visual-layer
> Note+
A visual object that is transparent can also be hit test.



Thanks for your PR and it is cool for the background transfer from the time to add a border.
As in your PR description, it partially solves the touch issue on WPF, for the case View without adding border.
We could setup BorderedCanvas.Background into transparent instead of null to solve remain cases.
something like this.

```C#
        protected static readonly Brush s_transparentBrush = new SolidColorBrush(Colors.Transparent);

        private void TransferBackgroundBrush(BorderedCanvas view)
        {
             if (view.Background != s_transparentBrush && view.Border != null)
             {
                 view.Border.Background = view.Background;
                 view.Background = s_transparentBrush;
             }
         }
```

**Comment by antonkh** [comment]
That's a good idea. I think using a transparent brush on the Canvas should be fine. I'll need to double check that, though.

**Comment by antonkh** [comment]
Could you also check if `Canvas.IsHitTestVisible = true` fixes the issue?

**Comment by Kudo** [comment]
`Canvas.IsHitTestVisible` is true by default. Confirmed not clickable even set it to true explicitly.

**Comment by Kudo** [comment]
Just pull master code and confirmed #1521 fixed the WPF issue and could close this issue.
Thanks for @antonkh's awesome work.

**Comment by rozele** [comment]
Thanks @antonkh! Closing out this issue.
