### ISSUE TITLE
Future of Windows App SDK Support

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-windows#11960]
### Summary

I can't find any information regarding Windows App SDK support in 2023, all I'm seeing is some deprecation of it, so I'm wondering if you guys still plan on support Windows App SDK? 

### Motivation

Future proofing

**Comment by chrisglein** [comment]
Ah, I can see your confusion. Probably triggered by [this item](https://github.com/microsoft/react-native-windows/issues/11744). We had some experimental WinAppSDK app templates that we built a couple years ago to explore how to add support for that project type. We're removing that because that particular approach to WinAppSDK support is at odds with our strategy for matching RN's [Fabric](https://reactnative.dev/architecture/fabric-renderer) rendering architecture. Long story short, we evaluated that the best way to support Fabric was to adjust the layering of RNW from direct XAML/WinUI that regularly drops down into Composition into instead defaulting to Composition that instead scales up to XAML/WinUI as need be. The end will be something quite possible with Win32/WinAppSDK apps, but is [underway](https://github.com/microsoft/react-native-windows/discussions/11741).

All that to say, we need a persistent discoverable document that covers this. Which is what you're asking for.

**Comment by k1mmm** [comment]
@chrisglein Alright, thanks for clarifying, this sounds great! By being able to leverage Win32 or WinAppSDK RNW apps will be far more powerful out of the box =)

Currently I'm packaging a WPF app to call som APIs UWP do not support, and this works good aswell, but being able to have a ReactNative context all the way would be awesome!
