### ISSUE TITLE
Merge with react native

### ISSUE THREAD

**Issue by landsman** [microsoft/react-native-windows#12135]
### Summary

Why this have to be next dependency?
I would love to see this support for windows, macOS in main repository of react native. 

### Motivation

For new people, it's really overcomplicated. 

### Open Questions

Do you think it's possible to merge these projects together and get the best DX? For me, it's a barrier, and looks like an unhealthy ecosystem.

**Comment by landsman** [comment]
What about opening a discussion with facebook to move the whole react-native to some non-profit org? Something like Apache.

**Comment by chrisglein** [comment]
This is certainly something that has been discussed. Part of the challenge is that there are more out of tree platforms than just Windows and macOS. It's not feasible for RN core to contain _all_ of these. And furthermore, moving them all in would increase the barrier for future out of tree platforms (as they'd be even more exceptional) and stymie innovation.

There's another point of view that RN core should only have core shared bits and Android and iOS should move out so that there's a more uniform experience for each platform. That's also been discussed. But obviously it'd be a lot of work, as the platform organically grew with a different relationship.

It's a bit awkward, it's true. But there's not an easy path forward here that justifies the effort at this moment. Instead, we're focusing on the aspects of the developer experience that we can more readily improve.

**Comment by landsman** [comment]
@chrisglein Have you ever talked to the RN developers about spinning off into a new organization? "React foundation" 

I think that would help too. It's so chaotic right now.

**Comment by chrisglein** [comment]
Yep, that's come up as well. In the way that there's a ".NET Foundation", for example. It's certainly an idea with merit, but would require getting all the various stakeholders on the same page there. Agree that could have promise, but it's not something in the cards at this exact moment.

**Comment by landsman** [comment]
> What about opening a discussion with facebook to move the whole react-native to some non-profit org? Something like Apache.

it is happening! sort of...

https://react.dev/blog/2025/10/07/introducing-the-react-foundation
