### ISSUE TITLE
Need a new community module to camera

### ISSUE THREAD

**Issue by AstrOOnauta** [microsoft/react-native-windows#12208]
### Summary

I was installing the newer version of RNW and I decide to install the `react-native-camera`, but this lib was deprecate. The new version of RNW is 0.72.10 and its incompatible with the lastest version of react-native-camera.
This lib (react-native-camera) suggest to use the lib `react-native-vision-camera`. But its not support to RNW.

So, I read your [documentation](https://microsoft.github.io/react-native-windows/docs/supported-community-modules#help-a-module-i-need-doesnt-work-with-windows-andor-macos) and there was a topic to `Help! A module I need doesn't work with Windows and/or macOS!`...and I am here for this.

If there's any other way of accessing the camera from Windows, it would be a great help...

### Motivation

The lib `[react-native-camera](https://github.com/react-native-camera/react-native-camera)` was deprecate and dont work in new versions of React Native/React Native Windows.

**Comment by chrisglein** [comment]
> So, I read your [documentation](https://microsoft.github.io/react-native-windows/docs/supported-community-modules#help-a-module-i-need-doesnt-work-with-windows-andor-macos) and there was a topic to Help! A module I need doesn't work with Windows and/or macOS!...and I am here for this.

We removed the template for creating a community module request, but apparently missed that line of documentation. That's not because we don't care about modules on Windows - of course we do! But the most effective way to drive that is with issues on the repos where the code lives. If there isn't already, can you pursue a request on the `react-native-vision-camera` repo? Given that there was an implementation on the old module, it should be transferable without someone having to re-figure out the native adaptation. But it's work to adapt it for sure.
