### ISSUE TITLE
Add windows support for react-native-pdf-lib

### ISSUE THREAD

**Issue by amiresobh** [microsoft/react-native-windows#12248]
### Summary

Hi everyone, hope you doing well
I wanna ask for windows support for react-native-pdf-lib package.

Should or can I do anything further to help this request coms ture? pls tell me, I would be glad to give a hand for this

### Motivation

-

**Comment by chrisglein** [comment]
> Should or can I do anything further to help this request coms ture? pls tell me, I would be glad to give a hand for this

Can you open an issue on that repo instead of this one? Sorry if the docs mislead you to opening one here. We're [in the process of updating them](https://github.com/microsoft/react-native-windows-samples/pull/882).
As far as other similar modules that support Windows, you can look here: https://reactnative.directory/?search=pdf&windows=true
