### ISSUE TITLE
NativeModules not working in release .72

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-windows#12521]
### Problem Description

After upgrading from .70 to .72, native modules (C++ part of the root project) work in debug but returns 'undefined' in release.

### Steps To Reproduce

Create a new project.
Add new native module (.cpp / .h) and include in ReactPackageProvider.

Run application, works in debug, null reference in release.

### Expected Results

Should not be a null reference in release.

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Release

**Comment by acoates-ms** [comment]
I assume when you say its coming as null you mean NativeModule.MyModule is returning `undefined`? More details might help.

If you are using remote debugging, then TurboModules will attempt to run as a NativeModule.  This can cause some runtime differences - including being accessible as `NativeModules.MyModule`.   Modules should be accessed using `TurboModuleRegistry.get('MyModule')` which will work if the module is running as a NativeModule or as a TurboModule.

**Comment by jbcullis** [comment]
Thanks @acoates-ms - my apologies, I'll better describe the issue in the future.

That is the issue, one thing to note is that NativeModules.ModuleName() still works on iOS and Android. Is it worth keeping that operational on Windows for consistency?

I haven't updated the mac app yet so not sure where that one sits.

**Comment by acoates-ms** [comment]
How are you registering your module?  You could change to register all your modules as NativeModules instead of TurboModules by using AddAttributedModules(packageBuilder, **false**);  But honestly that is kind of moving backwards at this point.  

iOS and Android are also moving towards turbomodules - so you should really be updating your iOS/Android code to use TurboModuleRegistry.get too. -- It will work if the native code is a turbomodule or a native module.
https://microsoft.github.io/react-native-windows/docs/native-modules-vs-turbo-modules
