### ISSUE TITLE
Remove FlatList.windows.js Fork

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#12770]
Following 1/22 integration RNTester pages which use FlatList are throwing a RedBox error. Needed to fork files to resolve the error. Fork can be removed after is integrated in https://github.com/facebook/react-native/commit/e33767a36daf7901cb46854b6612dd52b0dbdeec 2/22.

**Comment by NickGerleman** [comment]
This was because y’all were adding a babel transform outside the Metro preset, which ran before stripping Flow types. It is unrelated to any code changes, and is related to some ambiguity where Flow can type a member, vs later ES syntax which can lead to shadowing if transformed before types are stopped. 

It will not happen with the transform removed, and we also very recently changed the code to be resilient to custom transforms operating before type stripping, since incorrect transforms are hard to debug, and customizing a babel config isn’t an uncommon use case.
