### ISSUE TITLE
eliminate forced initialization of ReactContext and NativeModules on the UI thread

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1288]
As mentioned here:
http://facebook.github.io/react-native/blog/2017/08/07/react-native-performance-in-marketplace.html

Related to #1268 /cc @rigdern

**Comment by rozele** [comment]
I did a quick prototype of this, and it's a bit more complicated than I would have originally thought. ReactAndroid has a few architectural benefits that lend itself well to initialization off dispatcher thread. Currently, all modules that leverage the UI thread do so from the ReactChoreographer, which can be subscribed to from any thread. For the most part, we subscribe directly to the CompositionTarget.Rendering event, which requires you to be on the Dispatcher thread, so we currently can't move the `OnResume` lifecycle event to the native modules thread. Likewise, ReactAndroid is able to initialize the `MessageQueueThread` for the dispatcher from the native module thread, which we currently can't do either.

So the prototype I did made async calls to the dispatcher thread to do these initialization steps, and it turns out the async overhead of waiting for the `Dispatcher.Run` call to complete was more than the overhead of just initializing on the UI thread.

If we can eliminate the need to do these two steps on the dispatcher (which we could do by creating something like the ReactChoreographer), we could probably see a reasonable speedup from the off-UI-thread initialization.

**Comment by rozele** [comment]
We have 1/2 steps that I outlined above done towards off-UI-thread ReactContext initialization.  The next thing is initializing the MessageQueueThreads off-dispatcher, which we could do if we passed down a reference to the CoreApplication.

**Comment by rozele** [comment]
@matthargett I've done a ton of work towards enabling React context initialization off dispatcher thread, and some of this has had a small (<10ms) impact on startup times, and others have had no impact. I tried to replicate the behaviors of Android as much as possible in terms of which thread the initialization activities occur on, but following the Android approach actually slows down startup times.

**Comment by rozele** [comment]
We've eliminated a bunch of things that need to be initialized on the dispatcher, but overall it's not likely we'll need to move everything to a background thread. Closing for now.
