### ISSUE TITLE
AppState's instance variable should be thread-safe

### ISSUE THREAD

**Issue by rigdern** [Microsoft/react-native-windows#1300]
https://github.com/Microsoft/react-native-windows/blob/fab01fa8cadfa4874d15b0d2b41987eec1d52591/ReactWindows/ReactNative.Shared/Modules/AppState/AppStateModule.cs#L15

The `_appState` instance variable is read by multiple threads (`getCurrentAppState` and `OnResume` run on different threads) but the usage is not thread-safe.

I noticed this when running into #955.

**Comment by rozele** [comment]
I don't think there are any thread safety issues here.  The `_appState` variable is only ever written by the UI thread.  While I agree that we could minimize the race condition where the `_appState` is read while its being written by moving all read/write access to the variable to a single thread, it will never fully eliminate the race condition you experienced in #955. I really don't think this is a problem that can be fixed given the architecture of React Native.

That, or I'm not fully understanding what you mean by "not thread-safe".

**Comment by rozele** [comment]
I was finally able to reproduce this. It turns out, it's not an issue with the native module implementation, but instead the JavaScript assumptions. There are no guarantees in either ReactAndroid or ReactWindows that the lifecycle event calls will occur before the native module call (`getCurrentAppState`). So, technically this bug also exists in ReactAndroid (although it may be a much smaller race condition window). To work around the race condition, I've taken your suggestion to access the variable from a single thread.

**Comment by rozele** [comment]
Either the native module fix here, or the JavaScript fix upstream will take care of this issue.

**Comment by rigdern** [comment]
@rozele I opened this issue because I thought that even with the JavaScript fix there was still a bug in the native code due to accessing `_appState` from multiple threads. After filing this issue, I learned that assignment of reference types such as strings is atomic in C#. I can't think of any other multithreading concerns not addressed by the JavaScript fix so I think we can close this issue.

Thanks for submitting a PR to the react-native repo.
