### ISSUE TITLE
Is it safe to use react?! considering the license issues Apache raised?!

### ISSUE THREAD

**Issue by moderndev** [Microsoft/react-native-windows#1309]
In light of the recent announcements with react licensing that Apache made is Microsoft recommending that its still safe to use react in apps?

https://www.theregister.co.uk/2017/07/17/apache_says_no_to_facebook_code_libraries/?mt=1503119492953

I don't want to continue developing my app if I have to rewrite it to remove react ?! (like what Apache recommends)

**Comment by rozele** [comment]
@moderndev my (personal) takeaway from the link is, if you plan on moving your project to the Apache Foundation, don't use React.js. Otherwise, this licensing issue pops up once or twice a year, and yet many people continue to use React.js and React Native to build apps.

*DISCLAIMER:* My opinion here is my own, not Microsoft's.
