### ISSUE TITLE
File picker

### ISSUE THREAD

**Issue by sm2017** [Microsoft/react-native-windows#1311]
How can I have a file picker?

**Comment by rozele** [comment]
There are no core APIs for react-native-windows for file pickers. You'll need to create a native module, as described in https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeModulesWindows.md

**Comment by rob2d** [comment]
@rozele if you are familiar, would you be able to provide a little more context? A lot of people who pick up React Native are not really invested in the Microsoft ecosystem (which is why React Native is an attractive option). The .NET ecosystem is also really huge. This link is helpful, but makes a lot of assumptions about a developer's previous knowledge; for example, `MainPage.cs` mentioned in the documentation does not exist. Is that just an issue with things being out of date?
