### ISSUE TITLE
Implement autoCapitalize property for TextInput for fabric

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#13120]
Implement the autoCapitalize property for the fabric implementation of TextInput.

Note: A commented out version of this already exists in our new fabric code and may possibly just need to be re-applied.

This property was available in RNW Paper via TextInputViewManager.

See https://reactnative.dev/docs/textinput#autocapitalize for details.

**Comment by marlenecota** [comment]
I think maybe it was commented out because it was only exposed as Android specific?

I noticed this commit in the latest integration:
https://github.com/facebook/react-native/commit/7b3c622219ff6c03f410d34b06a74ba6fd642f5b

If that's the case, you can try the commented out code after this merges: #13264
