### ISSUE TITLE
RN Button size changes when in press state

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/react-native-windows#13332]
When you click on a RN button, the size of the button shrinks slightly, causing content below it to shift which is distracting.
(This can be seen clearly in the RN Gallery app)

**Comment by chrisglein** [comment]
There's a bottom border on the control that is displayed when idle:
![Image](https://github.com/microsoft/react-native-windows/assets/26607885/18bf8fcc-04c5-4a40-ac54-85b0ff38497b)

But not when pressed:
![Image](https://github.com/microsoft/react-native-windows/assets/26607885/7e62a2be-2493-480d-af15-b91eea817a46)

Which is correct... but shouldn't affect the layout size.

Since this is in the JS button, in the platform override of Button.js, this affects Paper and Fabric.
