### ISSUE TITLE
Add support for direct topMouseMove event

### ISSUE THREAD

**Issue by reseul** [Microsoft/react-native-windows#1577]
Current implementation does have direct events like topMouseEnter and topMouseLeave.
We'll have to add a direct topMouseMove, a counterpart of topTouchMove, though the latter is only generated when a button is down (in mouse parlance it's more of a mouseDrag).

Opening here for tracking.

**Comment by reseul** [comment]
This can be considered a follow-up/tweak of https://github.com/Microsoft/react-native-windows/issues/688

**Comment by rozele** [comment]
@reseul / note to implementer - in a standard UWP, there will be no effect on CPU usage / battery life when no listeners are subscribed to the `topMouseMove` event. However, if you implement it for `react-native`, we should do it in such a way that the native event is only subscribed when there is a JS listener, otherwise we'll be sending events over the bridge with no listener. I believe this is actually already a problem for `topTouchMove`.

**Comment by reseul** [comment]
@rozele Good point, will do (and fix the others). Will see what works..

**Comment by reseul** [comment]
@rozele It seems to be easy with direct events since "onXXXX" properties just get propagated to native view manager as boolean properties. This would cover topMouseMove. 
I think it's trickier when trying to address routed events since the handler may be hooked into some parent.

**Comment by reseul** [comment]
Ok, I think I have a solution for bubbled too. When time comes.

**Comment by reseul** [comment]
Hmm, forgot the solution for bubbled, need to think again.

**Comment by rozele** [comment]
@reseul - did we close this one out?

**Comment by reseul** [comment]
@rozele vintage, it's implemented and working. Closing.
