### ISSUE TITLE
Add keyboard listener to ReactRootView

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#159]
Keyboard listener sends an event with the keyboard dimensions to JavaScript.  This allows clipping and other operations to occur.

**Comment by rozele** [comment]
FYI: https://msdn.microsoft.com/en-us/library/windows/desktop/mt185611.aspx

**Comment by rozele** [comment]
I believe this is part of clipped subview work. See #79.

**Comment by victorileaf** [comment]
is there a way to detect keyboard operations in react-native-windows right now?

**Comment by rozele** [comment]
Closing in favor of concrete issues like #1901.

**Comment by gtRfnkN** [comment]
I understand, that #1901 might be more actionable, but it is just a small part of the Keyboard and KeyboardAvoidingView  functionality that is missing. This issue is currently linked in the [`CoreParityStatus page`](https://github.com/Microsoft/react-native-windows/blob/9614b68056081ba125294448fe92ad0fb8dd2c84/docs/CoreParityStatus.md).

Therefore, this should also include:
- keyboard listeners
- show / hide the keyboard
- a real KeyboardAvoidingView that changes the size of the page
