### ISSUE TITLE
UWP app sideload on hockeyapp error: Unable to download JS Bundle

### ISSUE THREAD

**Issue by YogeshDevgun** [Microsoft/react-native-windows#1621]
I've built UWP in react-native. When I run it on locale with react-native run-windows command app works fine. Now I've deployed it on Hockeyapp. When I download it on some other system and run there it throws error Unable to download JS Bundle Please check screenshot for more. Can anyone tell where and what I'm missing?

![image](https://user-images.githubusercontent.com/23658483/35882795-5658b186-0bab-11e8-9e61-09a478315395.png)

![image](https://user-images.githubusercontent.com/23658483/35882913-9fc965f4-0bab-11e8-963a-b6aac35065fa.png)

**Comment by rozele** [comment]
Looks like you published the wrong build configuration to HockeyApp.  By default, the `react-native windows` command generates a solution with two additional build configurations, `DebugBundle` and `ReleaseBundle`. In order to published a "pre-bundled" app, you'll need to:

1. Run the bundle command at the command line:
```
react-native bundle --platform windows --dev [true|false] --entry-file <e.g., index.js> --bundle-output <e.g., windows/myapp/ReactAssets/index.windows.bundle> --assets-dest <e.g., windows/myapp/ReactAssets>
```

2. Build the app with either `DebugBundle` or `ReleaseBundle`.

If this doesn't work, feel free to re-open.

**Comment by YogeshDevgun** [comment]
So I followed this:

1. Run this comand at CMD
react-native bundle --platform windows --dev [true] --entry-file index.js --bundle-output windows/POC/ReactAssets/index.windows.bundle --assets-dest windows/POC/ReactAssets

2. Build project (Not sln) 

3. Right Click on project name Store --> Create App Packages

4. Deploy on hockey app

5.  Right Click on project name HockeyApp--> Distribute App

and working fine on other systems. Thank you! Is there any tutorial for these commands or deployment @rozele

**Comment by brukbrhane** [comment]
I've been having a problem with not being able to find these 2 extra configurations `DebugBundle` and `ReleaseBundle`. Should I be creating a separate issue for it?
