### ISSUE TITLE
Windows Mobile Extensions error on first checkout/build

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#1631]
### Environment

- Target Platform:
UWP, WPF

- Target Platform Version(s):
10.0.14393, .NET 4.6, .NET Core 1.1

- Target Device(s):
Desktop, Xbox

- Development Operating System:

- Visual Studio Version:
VS2017 15.5.6

### Steps to Reproduce
1. On a new Windows machine, do a fresh install of VS 2017 (15.5.6 currently)
2. Do a fresh checkout of master
3. Open the ReactWindows solution in VS2017
4. set platform to x64, and do a solution build

result: on a new install of VS2017 with seemingly all relevant workloads selected. The process to get RN Windows loaded takes a number of installs of mostly auto-detected dependencies, requiring VS2017 restarts along the way. The main one that doesn't get installed automatically is the Windows Mobile Extensions for UWP:
```
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2307,5): error MSB3774: Could not find SDK "WindowsMobile, Version=10.0.15063.0".
```

I ended up having to remove the Windows Mobile Extensions node under the ReactNative (UWP) project references and re-add it to work around the related build failures

expected result:
This process should be documented in detail in the Getting Started guide. It seems like every point release of VS2017 introduces new little regressions that makes the DX worse for our project and similar, but we probably have to roll with the punches and update our documentation on every new patch release of VS2017.

**Comment by rozele** [comment]
Sounds to me like you didn't have the 15063 SDK installed on the fresh VS 2017 instance... thoughts?

**Comment by Nanashia** [comment]
I met this problem.
Visual Studio raises this error if it could not find Extension SDK which is supposed to be installed to `C:\Program Files(x86)\Microsoft SDKs\Windows Kits\10\Extension SDKs\WindowsMobile` because I have installed Visual Studio (and also Windows SDK) with different location from default one.
In my case Windows SDK is installed to `D:\Windows Kits`.
Solved by making symblolic link to `C:\Program Files(x86)\Microsoft SDKs\Windows Kits` from `D:\Windows Kits`.
