### ISSUE TITLE
Use Attached Properties instead of dictionaries for storage

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-windows#1635]
### Environment

1. `react-native -v`: latest
2. `npm ls rnpm-plugin-windows`: latest
3. `npm ls react-native-windows`: latest
4. `node -v`: N/A
5. `npm -v`: N/A
6. `yarn --version`: N/A

Then, specify:

- Target Platform: UWP

- Target Platform Version(s): UWP *

- Target Device(s): *

- Development Operating System: Windows

- Visual Studio Version: 2017

### Expected Behavior

Use XAML Attached Properties to store extra data against dependency objects instead of dictionaries.
Here are some docs: https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/attached-properties-overview.md.

### Actual Behavior

Uses Dictionary<DependencyObject, TValue> to store (and necessarily clean up) extra data associated with a DependencyObject.

**Comment by gmangov** [comment]
@rozele 
Pros:
- Attached properties are universal i.e. a property can be attached to anything that derives from DependencyObject
- consistent approach for all implementations
Cons:
- memory/performance implications
- a better option is to sub-class the UIElement and create properties in the subclass. This however may be problem since some XAML classes are sealed.
- it will be inconsistent implementation if sub-classing is used for non-sealed and Attached props are used for sealed XAML classes

**Comment by rozele** [comment]
I doubt we'll take this approach, attached properties have too much impact on memory / performance.
