### ISSUE TITLE
Add CameraRollModule

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#183]

**Comment by kamil7x** [comment]
Hello, I would like to ask if there is any progress on this issue?

**Comment by zfanda** [comment]
I am currently testing my own CameraRoll module code (getPhotos method). ;-)

**Comment by andrewwyld** [comment]
@rozele I'm currently trying to build a native module to trigger [CameraCaptureUI](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.cameracaptureui); this works fine in win10 but in win81 I can't access this class because React Native for win81 targets net46. I can't apparently reference those assemblies _or_ a win81 project I tried creating to reference them separately.

Are you aware of any way to work around this? Could I use some third type of project as bridging code? Sorry if this is the wrong place to ask—it's the most Cameraful thing I could find!

**Comment by ethanx94** [comment]
@andrewwyld I am also very interested in some kind of native camera module. Could you publish your work, even if it's only compatible on Windows 10? I might be able to help you iron out some bugs in my spare time.

**Comment by chrisglein** [comment]
Not taking on new features for the current (.NET) implementation.
This is being tracked for vnext here: #2550
