### ISSUE TITLE
Update docs: Mark project as experimental / not production ready

### ISSUE THREAD

**Issue by acuntex** [Microsoft/react-native-windows#1921]
Please update the README.md and include a notice that the project is experimental / not production ready.

According to the README.md developers could have the impression that it can be used like react-native.

Unfortunately there are a lot of technical issues:
- A lot of missing react-native components
- Unfinished/buggy build tools/commands
- WPF has an even worse state as UWP (e.g. assets have to be included manually in the project and set to Content/CopyIfNewer or it won't work in ReleaseBundle/DebugBundle)
- Basic stuff does not work properly (e.g. setting a font style in WPF, Picker used inside a drawer navigation view)
- WPF applications don't quit and remain in the background

Furthermore there hasn't been a proper bugfix release since April even though there were changes.

Don't get me wrong, I appreciate the effort and thank all contributors, but if a stakeholder asks if the react-native app works on windows, and a developer looks at the documentation, his answer is probably "Yes", which it is not without very big effort.

**Comment by jeveloper** [comment]
not to mention no releases since April

**Comment by rozele** [comment]
@jeveloper - there have been no releases since April because react-native had a two month gap without a release, and react-native 0.56 is incompatible with react-native-windows due to a known issue with metro that won't be fixed for that release. There has not been any patch releases for 0.55 because no one has requested it as of yet, however, we are long overdue for converting the 0.55-rc to a "stable" release.

@acuntex - we should document that WPF is not well supported. Please do submit specific issues for bugs related to build tools / commands. As far as missing react-native components, there are actually relatively few compared to the total number of "core" react-native components. If there are specific components from core that you need for your app, please file issues for that as well.

**Comment by jeveloper** [comment]
@npmun  mapview was removed a while back from the core, not sure if community version will be appropriate given that this is MS...

**Comment by acuntex** [comment]
WPF should be as important as UWP.

UWP has a lot of restrictions, thats why developers cannot create their apps as UWP App.
Thats why Microsoft created the Desktop Bridge. Not only because "People don't have time to migrate" but because it's sometimes impossible. The Desktop Bridge works great though.

E.g. if you have an app that has extensions for all common browsers, the regular way to communicate with a chrome extension e.g. is off limits because of the missing ability to write to the registry.
If you want the extension to communicate over http, it's also not working because you cannot connect from the same machine, only from remote. (That's a restriction I cannot understand in any way that does not make Microsoft the bad guy. Maybe Microsoft wants developers to force only to create extensions for Edge? That's unfortunately not how it works to get people to your browser.)

**Comment by acuntex** [comment]
Related to the convertion of rc to stable: I'd appreciate this, even regarding missing components.
But: Basic stuff like TextInputs should work at least :)
See:
https://github.com/Microsoft/react-native-windows/issues/1934
https://github.com/Microsoft/react-native-windows/issues/1935
https://github.com/Microsoft/react-native-windows/issues/1936
