### ISSUE TITLE
security-related error without any reason? 

### ISSUE THREAD

**Issue by gc1508** [microsoft/react-native-windows#1954]
Hi.

Using:
react-native 0.55.4
react-native-windows 0.55.0-rc.0

Getting continuous errors which makes impossible to use the library.

Please see last error below:
![image](https://user-images.githubusercontent.com/13567820/44979604-78ea9f80-af65-11e8-9d50-bebd2c1eb096.png)

Any help?

**Comment by gc1508** [comment]
Also, it doesnt happen all the times. Yesterday, it started to work and I was able to carry on the implementation without introducing any major changes. Today, same issue, same problem again. No new libs, no new dependencies, no new versions... any comment on this?

**Comment by rozele** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/misc/security-transparent-code-level-1

Can you try marking the ReactNative assembly as SecurityCritical to see if it resolves the issue? Are you introducing security requirements in the CLR at some other point in the build process?

**Comment by gc1508** [comment]
@rozele I can definitely read that link through. Yet, I am not entirely sure why a out-of-box behavior is not working. I havent made any change to code. Any idea? 

I am still trying to verify whether or not I am in that case, but I have the impression that the issue exists only if I start the APP from CLI. This morning worked when I ran it from within Visual Studio 2017. 
Again, ideas?

**Comment by DouglasDallavale** [comment]
someone got a fix to this?

**Comment by npmun** [comment]
duplicate #1988. You can workaround this issue by downgrading Visual Studio to 15.7.6

**Comment by sidgo28** [comment]
I'm running the app directly with react-native run-windows, but this still happens to me. Please fix this. Thanks.

**Comment by tdcook** [comment]
I followed the project initialization steps in the Getting Started document and I am having the same problem. It runs the first time, but subsequent runs fail.

Windows 10 Pro Build 17134
Visual Studio 2017 15.9.1
react-native 0.57.5
react-native-windows 0.57.0-rc.0

**Comment by JulianAssmann** [comment]
I am having this problem as well. The first execution runs fine but after that I need to delete my windows/Debug folder and then rerun react-native run-windows.

**Comment by drpritch** [comment]
JulianAssmann's solution worked for me. I find that running from Visual Studio tends to work, but command-line fails occasionally in this manner.

For Google help - just want to add the error text to this page, instead of just the image:

Attempt by security transparent method 'System.Reactive.Concurrency.CoreDispatcherScheduler..ctor (Windows.UI.Core.CoreDispatcher)' to access security critical type 'Windows.Core.CoreDispatcher' failed.
Assembly 'System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.

**Comment by rozele** [comment]
Did anyone try installing the latest stable release of the System.Reactive NuGet package?
