### ISSUE TITLE
.57 react-native has been release can this repo follow the upgrade?

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/react-native-windows#1964]
It would be awesome for all of this to be working again.

**Comment by the-nose-knows** [comment]
Either this module needs to be updated to support 0.57.* or a workaround guide needs to be added to explain how to fix the error caused by the current incompatibility for the **_Getting Started_** guide.

Basically, before you can run `react-native windows`, delete package-json.lock, open package.json and change the "dependencies" section for react-native to this:
`"react-native": "0.55.*"`

Then save & close, and re-run `npm install`; you might need to nuke the entire `node_modules` directory and run `npm install`, but try it without, first.

**Comment by craigrbruce** [comment]
Waiting for React Native Windows to work seamlessly with RN 5.7 is actually on our critical path. It would be great for a maintainer to respond with a roadmap or ETA on progress for this.

**Comment by rozele** [comment]
I'll prioritize getting a 0.57 release next week. In the meantime, you should be able to target rozele/react-native-windows#0.57

**Comment by craigrbruce** [comment]
Thanks for your response @rozele that's great news!

**Comment by xtianus79** [comment]
@rozele how do you run your git repository the entire thing is controlled by the rnp cli thing which is checking for verisons and erroring out that i am not on the right version... i've tried bypassing it but it is so baked in there.

**Comment by rozele** [comment]
0.57.0-rc.0 is out!

**Comment by xtianus79** [comment]
@rozele Funny, after the AirBNB article, and some other factors including some of things you have said... we've decided to go with Xamarin.

**Comment by rozele** [comment]
@xtianus79 cool! I think Xamarin is great 😊
