### ISSUE TITLE
A letter to Microsoft: this development choice is unnacceptable and a warning message should be placed on the readme.

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/react-native-windows#1974]
I work for a company that needs a solution for an IOS and Windows application build on a common code base.  Previously, we used Cordova / phone gap but did not like many things about it... for one there wasn't a good way to leverge code across all platform builds that is unique to each platform.  The plugin system changes over time and caused a lot of problems to fix it.  Creating a custom plugin was cumbersome, etc... 

When we sought to look for another solution and came across react-native-windows we thought this would be the solution.... A language everyone is comfortable with built with a powerful common code framework that could be used for each platform.  For over a week we have tried everything to get this repository's code base working and it is not working at all.  It is based on a very old sdk 14393 and is fragile beyond believe.  Fragile meaning, there are so many factors and so much software dependent on making this work... If any of these things fail, the entire plugin repository fails.  

furthermore, why are there so many dependent pieces... IMHO, it is do to lazy coding... throw this plugin to do this when a little bit of code could probably solve the problem.  Nevertheless, this repository is completely broken... It doesn't work, not in any fashion.  Not if we revert to a previous react-native version... nothing.  I callenge anyone to download VS 2017 and create a build with this repository... 

So in the end, what has microsoft done here to develop for this platform?  They literally have nothing that can be cross-platform and work for IOS and Android and Windows with a common code base based on the javascript language -- besides perhaps cordova. 

If one thinks about this, Microsoft most notibly, would have to surmize that Microsoft doesn't care about coding apps for it's platform... From my perspective this has been a disaster of an exercise.  I am literally astonished at the lack of attention Microsoft has given to this platform.  

I want to note I feel bad for the Microsoft employee who has to maintain this repository.  All we have been doing is bitching and complaining that it doesn't work.  I appologize for that and I know it isn't one person's fault.  But Microsoft, you have more than enough resources to address this correctly.  Why will you not make react-native interaction a first class citizen? Why are you choosing to leave a development pattern used by many people off the table?  What is the thinking behind this?  

Last, with the current app building problem for Windows... This would be the #1 reason and whomever doesn't see this inside Microsoft should take a serious look at the world today and your presense in it.

I'm very disapointed.

**Comment by xtianus79** [comment]
Oh and PS ReactXP is broken to because of this plugin

**Comment by rozele** [comment]
Thank you very much for the feedback @xtianus79.  Microsoft contributes to a number of open source platforms, not just React Native. In terms of a cross-platform option for building apps in JavaScript, Microsoft has contributed to Cordova and Electron, both of which are great options for building apps for Windows 10. I acknowledge and apologize that there has not been much attention to this repository lately. Part of the challenge with supporting a platform for React Native is the speed at which React Native moves, and the fact that there is no official "major" version of React Native with a fixed surface area (meaning a version 1.0.0). As I've said in other issues, we've spent less time contributing to this architecture for React Native on UWP because of the pending re-architecture of React Native, codenamed "Fabric". More details about Fabric can be found in this blog post: http://facebook.github.io/react-native/blog/2018/06/14/state-of-react-native-2018.html#architecture. 

I would love if you could provide specific examples to back up this statement: "furthermore, why are there so many dependent pieces... IMHO, it is do to lazy coding... throw this plugin to do this when a little bit of code could probably solve the problem." We are always looking for specific, actionable feedback that can help us improve. In the meantime, I'm going to close this issue as there are no actionable work items here to improve the repository.
 
Thank you for your efforts trying to get this working, and my sincere apologies that it's not working out for your team.

Please note, my comments and opinions here are my own, not necessarily Microsoft's.

**Comment by xtianus79** [comment]
@rozele why doesn't microsoft build something for javscript front-end development on their own?

**Comment by xtianus79** [comment]
and when i was saying over plugin usage... this line from that article is what i am referring to... 

> ust as our architecture changes will help React Native interoperate more cleanly with other native infrastructure, React Native should be slimmer on the JavaScript side to fit better with the JavaScript ecosystem, which includes making the VM and bundler swappable.

**Comment by slnovak** [comment]
Hi @rozele,

I'm really excited about this project and its potential! 

> we've spent less time contributing to this architecture for React Native on UWP because of the pending re-architecture of React Native, codenamed "Fabric".

I was curious about any updates from your team w.r.t. [Native React's Roadmap](http://facebook.github.io/react-native/blog/2018/11/01/oss-roadmap) now that it's been released. After watching the video on [React Native's New Architecture](https://www.youtube.com/watch?v=UcqRXTriUVI), I see that Facebook has created a cross-platform layout engine [with support for .NET and C#](https://github.com/facebook/yoga#net). Is this an initiative that your team will be interested in supporting?

Thanks!

**Comment by reseul** [comment]
@slnovak As far as Yoga is concerned (the cross platform layout engine you're mentioning), the current project already uses it.
(it's not a new thing, nor part of Fabric)
