### ISSUE TITLE
Modal has this error RCTModalHostView?

### ISSUE THREAD

**Issue by GezimVeliu** [Microsoft/react-native-windows#1978]
Is It arranged RCTModalHostView  in this version, I got this error: requirenativecomponent: "RTCModalHostView" was not found in the UIManager?

**Comment by rozele** [comment]
Closed by #1996

**Comment by aRajeshKumar** [comment]
I am receiving the following error when trying to display the Modal:

![image](https://user-images.githubusercontent.com/2465503/101775994-4baed380-3b16-11eb-9362-7cc4d74b91d1.png)

React Native version: 0.63.3

Could you let me know if I am missing anything here ?

**Comment by chrisglein** [comment]
Since this issue was originally opened the core implementation has changed completely for react-native-windows... but Modal still hasn't been implemented yet: #2989 (partially because we didn't have a reference implementation from the old C# core). It is on our radar, but is expected that it doesn't work today.

**Comment by jensonstack** [comment]
+1

**Comment by robsadams** [comment]
Receiving this error as well.... has this ever been fixed?
