### ISSUE TITLE
Help about RNTester or any tutorial to get started ?

### ISSUE THREAD

**Issue by assurancetourix** [Microsoft/react-native-windows#2035]
Hello,

I am conscious it's probably not the right place but I am a bit desperate. I want to extend my android app to UWP, and I have managed to get a few things with react-native-windows (like integration with react-native-sound...).
Works fine, but is there somewhere a kind of step by step tutorial to have insights with the basic react components (like redux, store, navigation...)

Actually, I have read this 
"If you're looking for sample code, just browse the RNTester folder in the GitHub web UI"

But I have no clue regarding how to run successfully RNTester and this page didn't provide me sufficient help to get started
https://github.com/Microsoft/react-native-windows/tree/fb38940b1fabf39787451ef844a273c966cd89a3
(I have the application started, but where should I launch 'react-native start' to get my bundle.js)

If you could maybe update a bit the main page or even put a few links to start building an app once the "Hello World" is done, it would be great.
Also, a procedure regarding the release build and publication to the App Store would be very appreciated (of course if it changes from a classical UWP app).

Thanks a lot for your understanding.

**Comment by rozele** [comment]
To run RNTester, check out the [README](https://github.com/Microsoft/react-native-windows/blob/fb38940b1fabf39787451ef844a273c966cd89a3/README.md) in that folder. Make sure you clone all submodules (e.g., `git clone --recurse-submodules` or run `git submodule init; git submodule update` from existing source directory).

I believe there might be an issue with react-navigation due to a missing dependency for `react-native-gesture-handler`. See https://github.com/Microsoft/react-native-windows/issues/2033.

Any pure JS dependencies should work as expected on react-native-windows (and if they don't it's probably a bug).

For dependencies with React Native native modules for Android and iOS, see [Native Modules doc](https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeModulesWindows.md).

For dependencies with native view managers for Android and iOS, see [View Managers doc](https://github.com/Microsoft/react-native-windows/blob/master/docs/NativeComponentsWindows.md).

For creating a bundled app for publishing in the Windows Store, see [this doc](https://github.com/Microsoft/react-native-windows/blob/master/docs/RunningOnDeviceWindows.md#using-offline-bundle).
