### ISSUE TITLE
React Native Windows after Edge moves to Chromium

### ISSUE THREAD

**Issue by pducolin** [Microsoft/react-native-windows#2036]
Hi,

we recently started building a new UWP based on React Native Windows, finding it a great solution. 
We recently read about the Edge project being rewritten to use Chromium core: since React Native Windows is based on Edge current core, Chakra, we would like to know if there are plan to move also React Native to V8, or if Chakra will still be supported and mantained even after Edge stops using it.

Thank you in advance for your replies.

**Comment by rozele** [comment]
The choice to use Chakra was simply to reduce the size of the app bundle (not JS bundle, but native bundle). Since Chakra already shipped with Windows 10 for Edge, it was easy to use the existing chakra.dll from Windows 10. I suspect it will be some time before Chakra no longer ships as part of the OS, so there is some time to transition to another JSRT. In the ideal world, we'd have options for any JSRT - e.g., JSC, V8, or Chakra. AFAIK, people have investigated using both JSC and V8 with react-native-windows and have been successful. cc @matthargett @reseul.
