### ISSUE TITLE
[Releases] Figure out binary distribution story for RNW

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2080]
We need to establish a plan for how the solution will be released. We know that JavaScript related to react-native-windows will continue to be published on NPM, but we have a few options for how we publish native code. We can use the following questions to guide the plan:

1. Will we ship the native bridge implementation for React Native as source code or compiled binaries?
2. If compiled, will we ship the binaries on NPM alongside the JavaScript?
3. If compiled, and if not shipping binaries with JavaScript on NPM, will we ship the compiled binaries on NuGet, vcpkg, or some other package management service?
4. If compiled, and if not shipping binaries with JavaScript on NPM, what will be the versioning scheme to align compatibility between JavaScript released on NPM and native binaries shipped on some package management service?

**Comment by rozele** [comment]
Near term suggestion to ship as source.

**Comment by harinikmsft** [comment]
In the near term for [Milestone - RNWCPP_Preview](https://github.com/Microsoft/react-native-windows/milestone/15), we will be shipping the source and the CLI will use the source as is. This issue is tracking a future where we package into a nuget package and dlls to save disk space. We may want to add a flag in the CLI to retain both modes.

**Comment by kmelmon** [comment]
We have a plan now, tracked by this project board:
https://github.com/microsoft/react-native-windows/projects/33
