### ISSUE TITLE
Red box error: "No current context"

### ISSUE THREAD

**Issue by npmun** [microsoft/react-native-windows#2082]
### Environment

1. `react-native -v`:  0.57.8
2. `npm ls rnpm-plugin-windows`: ^0.2.8
3. `npm ls react-native-windows`: 0.57.0-rc.5
4. `node -v`: v8.6.0
5. `npm -v`:  N/A
6. `yarn --version`: 1.13.0

Then, specify:

- Target Platform:

- Target Platform Version(s): UWP

- Target Device(s): Desktop

- Development Operating System: Windows 10 pro

- Visual Studio Version: 15.9.7

- Build Configuration: Debug

### Steps to Reproduce

(Write your steps here:)

For past couple days I started seeing red box (see the screenshot) when attempt to launch my react native UWP app. (Android app still works). I did see this error in the past couple times. Deleting node modules & nuget packages and restoring them resolved it. however, this time I cannot get it work. I was playing with "react-native-camera" library when this happened for the first time earlier this week, I rolled back changes related to this since then but  issue still persists. any thoughts?

![image](https://user-images.githubusercontent.com/36347019/53441045-cb5bc480-39ba-11e9-86c7-98b56bc48e46.png)

I will try to create create reproducable demo sometime this week. 

### Expected Behavior

App launches cleanly

(Write what you thought would happen.)

### Actual Behavior

App fails to launch. (see screenshot)

(Write what happened. Add screenshots!)

### Reproducible Demo

Not available yet. 

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rozele** [comment]
@npmun - can you set a breakpoint and share details for what JS module and method is being called in `CallFunctionReturnFlushedQueue`? I suspect a race condition was introduced in the initialization sequence, and it would be good to have that info for reasoning.

**Comment by npmun** [comment]
@rozele Module name is "JSTimers". Please see screenshot for more details. 

It appears like a new version 4.1.3 of System.Reactive and/or System.Reactive.Linq nuget packages (released 3 days ago) probably caused this. Rolling back to older version resolved the issue. 

![image](https://user-images.githubusercontent.com/36347019/53456259-89df0f80-39e2-11e9-82c2-2ddca1f82b81.png)

**Comment by rozele** [comment]
@npmun - thanks for the details. `react-native-windows@0.57.0-rc.5` is still locked to `System.Reactive` version `4.0.0-preview00001`. So, I suspect you have updated the System.Reactive dependency after installing.

That being said, it's still suspicious that updating System.Reactive might cause this bug, I'll try to repro.

**Comment by rozele** [comment]
Honestly @npmun - I'm confused as to how this ever worked. The JSRT context is assumed to provide access to the JSRT by a single thread. If you want to transition control to another thread, the controlling thread nulls out the context and allows a new thread can set a new context.

Currently, we implement the JavaScript queue thread with [NewThreadScheduler](https://github.com/dotnet/reactive/blob/b4ab7a3d5ef05c5f5f1f7f298f3d3ea54622ba3f/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs), which spins up a new Thread for every call to `IActionQueue.Dispatch`.

Can you try updating System.Reactive again, and then changing the JavaScript ActionQueue scheduler to `new EventLoopScheduler()` instead of `NewThreadScheduler.Default`? I.e., here:
https://github.com/Microsoft/react-native-windows/blob/c8ef244b91b7c3f2b7d01df44fb638439f3479a2/ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfigurationFactory.cs#L43

**Comment by rozele** [comment]
In theory, you should still be getting the bug even after downgrading System.Reactive. I believe the solution was only ever working because no other threads were created in the process. Perhaps the version 4.1.3 of System.Reactive modifies the default scheduler (e.g., for native modules) in such a way that it creates additional threads.

**Comment by reseul** [comment]
@rozele I don't know the gory details, but the net effect of that NewThreadScheduler is NOT a new thread for each Dispatch...
I remember from endless debugging, the JS thread had a fixed managed id of 6 or so... It was the module thread that kept changing (i.e. used threads liberally)

**Comment by reseul** [comment]
Others are having same struggles: https://stackoverflow.com/questions/17772373/newthreadscheduler-default-schedules-all-work-on-same-thread

**Comment by rozele** [comment]
@reseul Hmm - looks like you're right. I think it's out of pure luck that NewThreadScheduler sticks with one thread because it is an `ISchedulerLongRunning` and the `ObserveOn` operator we use to set up the subscription in the `ActionQueue` uses `ScheduleLongRunning` to set up a queue + wait handle to process events indefinitely (i.e., [this](https://github.com/dotnet/reactive/blob/58a55ba81ff26d76c314cbded74e89ea74a417c4/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs#L83-L132) event loop).

Still not sure then how else we could run into a situation where the JS ActionQueue thread does not have a context set on the JSRT.

**Comment by rozele** [comment]
And I still think we should switch to `EventLoopScheduler`, which requires less reasoning to assert that all events occur on a single thread.

**Comment by rozele** [comment]
Then again, the problem with the `EventLoopScheduler` is that it is not `ISchedulerLongRunning`, so it uses a slower algorithm to context switch events onto the correct thread.

**Comment by rozele** [comment]
I'm also now convinced that this is all deja vu, and I've gone down this reasoning path before... we should document the choice of NewSchedulerThread, as I now recall that it was a strategic choice 🤦‍♂️

**Comment by npmun** [comment]
> Honestly @npmun - I'm confused as to how this ever worked. The JSRT context is assumed to provide access to the JSRT by a single rental thread. If you want to transition control to another thread, the controlling thread nulls out the context and allows a new thread to set another context.
> 
> Currently, we implement the JavaScript queue thread with [NewThreadScheduler](https://github.com/dotnet/reactive/blob/b4ab7a3d5ef05c5f5f1f7f298f3d3ea54622ba3f/Rx.NET/Source/src/System.Reactive/Concurrency/NewThreadScheduler.cs), which spins up a new Thread for every call to `IActionQueue.Dispatch`.
> 
> Can you try updating System.Reactive again, and then changing the JavaScript ActionQueue scheduler to `new EventLoopScheduler()` instead of `NewThreadScheduler.Default`? I.e., here:
> [react-native-windows/ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfigurationFactory.cs](https://github.com/Microsoft/react-native-windows/blob/c8ef244b91b7c3f2b7d01df44fb638439f3479a2/ReactWindows/ReactNative.Shared/Bridge/Queue/ReactQueueConfigurationFactory.cs#L43)
> 
> Line 43 in [c8ef244](/Microsoft/react-native-windows/commit/c8ef244b91b7c3f2b7d01df44fb638439f3479a2)
> 
>  new ActionQueueFactory(onError => new ActionQueue(onError, NewThreadScheduler.Default)),

@rozele thanks for looking into issue. issue started occuring as soon as I upgraded System.Reactive to v4.1.3. And, changing ActionQueue scheduler to new EventLoopScheduler() seems to have fixed it. Hope this helps!

**Comment by rozele** [comment]
Thanks for following up @npmun!

@reseul - sounds like my logic was flawed for choosing an `ISchedulerLongRunning` and that the event loop can somehow terminate, leading to a new thread being spun up on a subsequent `IActionQueueDispatch` call.  Meh.
