### ISSUE TITLE
[ThirdParty] Create tooling and document an approach for publishing native extensions

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#2104]
One of the most compelling aspects of react-native is the rich open source ecosystem of native extensions. We should make it as easy as possible for developers to write and publish third party native extensions (i.e., view managers and native modules) for React Native. This tooling / documentation should cover:

1. Recommended approach for publishing native code (i.e., as source code or binary)
2. How / where to publish native code and associated JavaScript? (likely NPM, but any additional source for native code?)
3. CLI or .vsix to generate templates / scaffolding for native extensions (see [`react-native-create-library`](https://github.com/frostney/react-native-create-library/) to see an example of this for the C# repo).

**Comment by micahl** [comment]
We should plug into the community efforts that are already doing things in this area.  

https://github.com/react-native-community/cli/issues/288

**Comment by stmoy** [comment]
I believe there are two main thrusts behind this issue: 

1. Native module authors who choose to add Windows support should be able to **publish** their modules using the same workflows that they use for iOS/Android 
2. App developers targeting RN4W should have the same support for auto-linking that iOS/Android enjoy -- Micah's comment above

As filed, however, I think this issue is only focused on the first topic. 

The MVP/tablestakes for this issue are that a module author can add RN4W support and create an NPM package same as iOS/Android that an app author can then install. 

What is unclear to me though is if this already exists - ie. if a module is already building an npm package for iOS/Android, do they get Windows support "for free" assuming that there is a RN4W implementation? If so, great! Let's not do something bespoke for Windows. If not, what do they need to do to generate the package?

**Comment by harinikmsft** [comment]
We have added sufficient documentation for native extensions at this time - https://microsoft.github.io/react-native-windows/docs/native-modules

Auto-linking is being tracked through #2853
