### ISSUE TITLE
Optimize BitmapImage usage

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2117]
ImageViewManager re-creates a new BitmapImage every time you change the source. We want it to modify the BitmapImage's source instead.

See ImageViewManager.cpp => ImageViewManager::setSource()

**Comment by stecrain** [comment]
I'm sure you already know that this optimization is worthwhile.
But just adding my 2 cents.

We did this in Microsoft Store app by structuring the XAML markup to have a BitmapImage and set the url on that instead of directly on Image.
The optimization is definitely worthwhile. I might be able to dig up traces of the gains we saw if you're interested.
