### ISSUE TITLE
Optimize unnecessary layout work

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2118]
Andrew Coates says that we construct a yoga layout tree for a lot of nested Views which we let Yoga perform layout on, yet we must forcefully call Measure/Arrange (not sure which) on the backing XAML panels, otherwise we can't correctly push layout information into them.  This means we're paying a cost in XAML to run layout unnecessarily.

Can we optimize away this cost?  Thoughts:
-Attack the problem as directly as possible.  Requires debugging through XAML to find out why the explicit calls to layout are necessary.
-Change PanelView to Canvas?  Canvas pays a much lower cost to run layout
-Implement MeasureOverride/ArrangeOverride and do nothing?

**Comment by rozele** [comment]
One of the optimizations we have in the C# solution is to "optimize away" some of the React components that are purely used for layout. It turns out there are usually quite a lot of these in a typical React Native app. This would help as you would reduce the number of views doing the unnecessary Measure/Arrange work.

This is the approach that was taken for Android, although I'm not sure if it will go away with the introduction of "Fabric". Here is the code in C# for using the shadow node hierarchy to optimize away native views that would be purely used for layout:
https://github.com/Microsoft/react-native-windows/blob/master/ReactWindows/ReactNative.Shared/UIManager/NativeViewHierarchyOptimizer.cs

**Comment by kmelmon** [comment]
I've split the "optimize away unnecessary panels" aspect of this into a separate issue:
https://github.com/microsoft/react-native-windows/issues/2605
