### ISSUE TITLE
[Component] Text - Property Completion

### ISSUE THREAD

**Issue by kikisaints** [microsoft/react-native-windows#2121]
The following unchecked properties are needed to complete the **Text** control integration into RNWCPP.

## P1
- [x] **selectable**
*Lets the user select text, to use the native copy and paste functionality.*
Maps to TextBlock.IsTextSelectionEnabled (Win8)
- [x] [**ellipsizeMode**](https://facebook.github.io/react-native/docs/text#ellipsizemode)
*When numberOfLines is set, this prop defines how text will be truncated. numberOfLines must be set in conjunction with this prop.*
Partially supported by XAML.  Enum:
-head:  Not supported by XAML
-middle:  Not supported by XAML
-tail:  Maps to TextBlock.TextTrimming.CharacterEllipsis (Win 8.1) or TextBlock.TextTrimming.WordEllipsis (Win8)
-clip:  Maps to TextBlock.TextTrimming.Clip (Win 8.1)
- [x] **numberOfLines**
Maps to TextBlock.MaxLines (Win 8.1)
- [x] **allowFontScaling**
*Specifies whether fonts should scale to respect Text Size accessibility settings. The default is true.*
Maps to TextBlock.IsTextScaleFactorEnabled (Phone 8.1)
- [x] **selectionColor**
Maps to TextBlock.SelectionHighlightColor (Win 8.1)

## P2
- [x] **Nested Text**
Partially supported by XAML.  TextBlock does not nest.  Nesting can be handled by creating Spans, but this creates some impedance mismatches with the RN API as Span doesn't have all the same behaviors as TextBlock.  Needs more investigation.

## P3
- [x] **pressRetentionOffset**
*When the scroll view is disabled, this defines how far your touch may move off of the button, before deactivating the button. Once deactivated, try moving it back and you'll see that the button is once again reactivated! Move it back and forth several times while the scroll view is disabled. Ensure you pass in a constant to reduce memory allocations.*
Needs investigation.  Mobile-specific feature, do we need this?

## Already Completed
- [x] **onLayout**
- [x] **onLongPress**
- [x] **onPress**

| Future |
|:--|
| <ul><li>maxFontSizeMultiplier *iOS Only* </li><li>disabled *Android Only* </li><li>textBreakStrategy *Android Only* </li><li>adjustsFontSizeToFit *iOS Only* </li><li>minimumFontScale *iOS Only* </li><li>surpressHighlighting *iOS Only* </li></ul>|

**Comment by RobMeyer** [comment]
@kmelmon I'm interested in taking this item. Are you actively working on it?

**Comment by kmelmon** [comment]
> @kmelmon I'm interested in taking this item. Are you actively working on it?

Nope - I'm just costing things at this point.  Feel free to take this.  You can help us track by adding yourself as an Assignee.

**Comment by ddalp** [comment]
It looks like there's nothing needs to be done from RNW for supporting Nested Text, the nested layout and text formatting inheritance logic are at React JS side. I tested with several sample scripts and all worked fine. pressRetentionOffset is also implemented in React JS, though I don't know what is the user scenario for this property on Text. 

In my view, this issue can be closed as most of the text properties are implemented in RNW.

**Comment by RobMeyer** [comment]
@ddalp does that mean nested <Text> results in multiple <TextBlock> in the XAML tree then? I was hoping for the performance optimization of using an inlines collection in a single <TextBlock>, but that seems impossible to do from the React JS side without some logic on the native (xaml) side.

On the flip side, if we were to use an inlines collection then the nested <Text> components backed by <Run> or <Span> elements probably would need special-casing to support some long tail of props such as onLayout.

**Comment by ddalp** [comment]
@RobMeyer Using inlineCollection (Span, Run) for TextBlock will make it to opt-out DWriteTextLayout fast path mode and fall back to line services slow layout mode. So the trade-off would be either we have slower layout performance at RNW or and React JS side. Since the React JS side has much simpler layout text format properties, I would imagine there are performance advantages to have the layout/format inheritance logic done on JS side.

**Comment by ddalp** [comment]
Resolving this issue as I don't see any additional work needed for Nested Text and pressRetentionOffset.

**Comment by kmelmon** [comment]
I believe there's still work to do here...  XAML doesn't allow nesting TextBlock so we implement nested Text by creating a Span for the nested Text.  Looking at the Text properties, we have no way to map a number of these properties to Span because Span is more limited than TextBlock.

From a quick glance at TextViewManager, these properties (at the least) seem problematic:
numberOfLines
selectable
lineHeight
allowFontScaling
selectionColor

**Comment by ddalp** [comment]
@kmelmon You are right, we do create inline collections of span/run for the nested text. I think I am clear now that this issue is not about supporting Nested Text, rather it is about whether/how to support all text properties for the Nested Text.

**Comment by ddalp** [comment]
**Properties working on all nested text elements:**
color, fonts (fontSize, fontFamily, fontWeight, fontStyle etc..), spacing.

**Text properties setting on nested child text elements has no effect:**
textAlign
ellipsizeMode
**textDecorationLine**
numberOfLines,
lineHeight,
selectable,
allowFontScaling,
selectionColor

**Others such as view properties setting  on nested child text elements has no effect:**
Padding
Opacity

RNW's behavior is similar to Andriod, but differs from iOS, for example Opacity on Nested Text.

Looks like we should be able to also support textDecorationLine on nested Text since it is supported on Span, I will try that out.

**Comment by chrisglein** [comment]
Okay @kikisaints, Di believes we've done as much as we can do here. So now we need to document what isn't supported. Can you update the [parity status doc](https://github.com/microsoft/react-native-windows/blob/master/vnext/docs/ParityStatus.md) with this information?
