### ISSUE TITLE
Design wrapper for ListView control (make decision on whether or not to expose this)

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#2155]
Currently, the app dev needs to specify all aspects of how the items in a FlatList should look and behave. To improve ease of use and consistency across RN apps on Windows, we should provide a default state similar to what ListView provides in Xaml. Ideally, FlatList would have default states (rest, hover, pressed, selected, disabled), capability to arrow between items, and Narrator announcements of item in set with no or little dev work.

**Comment by MikeHillberg** [comment]
Are there differences also in virtualization & panning performance between FlatList and ListView?

**Comment by acoates-ms** [comment]
While I do think there is a need for a component that is able to take advantage of ListView -- That is not FlatList and we shouldn't be looking at trying to redo or fix FlatList. FlatList is more like repeater, in that it handles layout and virtualization -- thats about all.

We should ensure that the platform has the appropriate properties that people can implement all the states required for list items.  But flat list doesn't do that out of the box in RN, and probably should in RNW either.

**Comment by micahl** [comment]
Agree with Andrew here.  If the existing FlatList doesn't have default policy then we shouldn't be adding any in RNW.

**Comment by YuliKl** [comment]
FlatList in RNW is currently completely unusable with keyboard or Narrator, in large part because there's no FlatListItem concept, I think. It's inefficient to expect every app that wants to use FlatList to roll their own item states and will lead to some very confusing and inconsistent user experiences.

Perhaps we need a new ListView-like component, but I don't know what that does to the xplat story.

**Comment by micahl** [comment]
I think it would be instructive to find examples of apps using FlatList to see what they've done and then we can figure out what makes sense.

**Comment by stecrain** [comment]
I happened to stumble upon this issue, and I have a few thoughts I wanted to share.

I believe the popularity of react-native is a strong signal from app developers that we don't necessarily want all the policy and constrained scenarios that come along with ListView.

Rather than focusing on making controls have built-in support for arrow keys and accessibility I believe the focus should rather be on making sure the framework empowers app developers to implement these efficiently.

The UI framework is never going to be able to capture every-single-scenario for displaying a list of items.
Honestly I believe this is a mentality shift that needs to happen.

IMO creating a ListView wrapper is not worth the investment. The community can do that, take a look at all the examples here.
https://github.com/react-native-community

I whole-heatedly believe the goal of this project being funded should be to enable any app developer to make a ListView wrapper trivially.

**Comment by chrisglein** [comment]
Consensus is that a community module is the right answer here. Either adding keyboarding support to an existing one, or creating a new one.
