### ISSUE TITLE
Clean up folder structures for a simple onboarding experience

### ISSUE THREAD

**Issue by harinikmsft** [Microsoft/react-native-windows#2183]
Make a peer to RNWCPP for the C# implementation, to prevent npm package conflicts, and generally make it easier to delineate the implementations

**Comment by jonthysell** [comment]
Working on it here: https://github.com/jonthysell/react-native-windows/tree/jonthysell/rnwcs

**Comment by hansenyy** [comment]
@jonthysell, as @acoates-ms mentioned in a Teams thread. I would also like to work on this. Specifically, I've been slowing reorganizing the C++ code under the RNWCPP folder. What specific improvements are you working on in your fork? I want make sure that we don't conflict each other or duplicate work here.

**Comment by JunielKatarn** [comment]
@jonthysell @hansenyy +1.
I have worked before in the C++ directory structure. Let's make sure we are on the same page to prevent duplicate efforts.

**Comment by jonthysell** [comment]
I am simply moving all of the C# implementation into a RNWCS folder, as a peer to the RNWCPP folder, in order to prevent npm dependency conflicts between the two implementations.

I will of course also update the config/build files with the new relative path.

Otherwise I am not planning on refactoring the hierarchy under either of these two folders for the purposes of this issue.

**Comment by jonthysell** [comment]
Merged into master, now merging master into rnwcpp
