### ISSUE TITLE
Codepush with RNWCPP

### ISSUE THREAD

**Issue by harinikmsft** [Microsoft/react-native-windows#2185]
Codepush currently supports react-native-windows and the C# implementation. This is tracking investigation on whether CodePush works against RNWCPP and if not, what needs to be done to ensure it works.

**Comment by rozele** [comment]
This would be a great litmus test for the C# interface / backward compatibility for C# native modules. Code Push is relatively complicated, as it downloads the latest assets, saves them in app storage, and then based on the app settings, either restarts the app immediately or waits for the next time the app is loaded. In the former case, it means the interface to the React instance needs to expose enough hooks so that native modules can easily "reload" the app.

If there's not already a C++ SDK for code push, or any react-native-code-push implementations built in C++, it may be worth investigating how much more difficult it would be to consolidate the entire Code Push library to C++ (as opposed to ObjC, Java, C#, and C++).

**Comment by matthargett** [comment]
Hm. I wonder how much of CodePush could be pure C++ using the CxxReact interfaces and implementation. Seems like a great use case to augment any gaps in those interfaces.

**Comment by kmelmon** [comment]
Kiki is driving the work in CodePush to support C++.  Closing
