### ISSUE TITLE
Add DatePicker ViewManager or Module

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#230]

**Comment by martinarroyo** [comment]
I did an implementation for a personal project  (a few `props` might still be missing, but the core functionality was already working), and wouldn't mind making a PR. I might have the time over the weekend to submit a draft :)

**Comment by Hirurgo** [comment]
Maybe you will have free time at the weekend to do PR? =). You have done a wonderful job, and I really hope that DatePicker will become part of RNwindows as quickly as possible

**Comment by npmun** [comment]
@martinarroyo Thanks for your great work for adding date controls to RNWindows, It would be nice to have these controls merged into the upstream branch.

**Comment by martinarroyo** [comment]
Well... in the end I completely forgot about this. I am terribly sorry for the delay, and hope you could still make use of the components in the meantime. I have submitted a new PR with an updated version of the code here: https://github.com/Microsoft/react-native-windows/pull/1881

**Comment by npmun** [comment]
Thanks, @martinarroyo for your help! Yes, I copied the code from your commit to my project for time being.

**Comment by joeygreen** [comment]
I'm currently using an implementation of the CalendarDatePicker (datepickder didn't support min max dates just years) but am struggling with the idea of event firing other than onDateChange. Basically whatever date this thing is instantiated with is what it will display regardless of what react state changes because the only way to update the date is to physically interact with the control thus firing the uwp onDateChange event. Any guidance on adding an event to handle a new date coming in w/out interacting with the control would be amazing but I can't imaging how that's even possible.

**Comment by rozele** [comment]
@joeygreen - take a look at the `TextInput` implementation. It maintains a native counter for the current index of state changes and can verify if a state change from React.js should update the native component

**Comment by joeygreen** [comment]
Thanks so much for your reply rozele!

**Comment by joeygreen** [comment]
I'm referencing 

https://github.com/Microsoft/react-native-windows/blob/65489b3b171b9f688167e27a127fcc02e4105826/ReactWindows/ReactNative.Net46/Views/TextInput/ReactTextInputManager.cs

and 

https://github.com/Microsoft/react-native-windows/blob/e2f6eb10a102f29ea1b7b8a99e43d4326b94bfbb/Libraries/Components/TextInput/TextInput.windows.js

But my lack of familiarity with this wizardry is blocking me from discovering what I'm trying to achieve.

**Comment by joeygreen** [comment]
I'm looking at the onChange of the js file...

**Comment by joeygreen** [comment]
where does _inputRef get assigned to and what is its value?

**Comment by joeygreen** [comment]
I'm getting there. I think this is my new journal.
