### ISSUE TITLE
Title bar full customization

### ISSUE THREAD

**Issue by devdanoliveira** [microsoft/react-native-windows#2527]
Hi folks,
I'm working on a RNW app that has a left navigation view and I need to customize the title bar with placeholders that can trigger events.
Did someone need to customize title bar in a RN Windows app?

Does is It possible to create a native module to do that?

[https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#full-customization](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#full-customization) 

Thank you very much for your reply!

**Comment by harinikmsft** [comment]
Hello @devdanoliveira - you should be able to accomplish this using a native module/custom view manager to do this. Unfortunately, this is not a high priority feature for us at the moment. 

Please refer [Native Modules on windows](https://github.com/microsoft/react-native-windows/blob/master/current/docs/NativeModulesWindows.md) for help on how to accomplish this. 

Another alternative if the custom title is pretty static and only for Windows - you could just do this on the native UWP XAML host code instead of through RN.

**Comment by chrisglein** [comment]
We're not investing in new features on current. If this issue is still relevant feel free to re-open against vnext.
In this case it seems like wrapping WinUI's NavigationView is the path forward.

**Comment by Victor0814gui** [comment]
can you solve? I'm having the same problem.

**Comment by chrisglein** [comment]
> can you solve? I'm having the same problem.

This issue is many years old and logged against an older implementation of RNW. The short answer is that the way to accomplish this is to drop to native code. There isn't deep titlebar customization from JavaScript. Someone could bundle that into a native module and share with the community though.

**Comment by Victor0814gui** [comment]
I'm creating a native module for this, it's almost complete

**Comment by CrisAlejo26** [comment]
Se ha podido agregar alguna funcionalidad a la barra de titulo para modificarla?

**Comment by Victor0814gui** [comment]
@CrisAlejo26. Yes, but it's somewhat limited. For my use case, I only needed to change the colors of the bar or hide it, so those are the functionalities I implemented. Here is the library: https://github.com/laddermore/react-native-custom-window
