### ISSUE TITLE
Investigate:  How to take dependency on react-native master

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2529]
The react-native master branch is where Facebook is making all their changes.  We are currently lagging behind master and taking a dependency on some stable branch.  This makes it difficult for us to submit changes from our code back into master.

This task is tracking understanding how we could make react-native-windows take a dependency on react-native master branch, or an alternative plan (such as cherry picking changes back).

**Comment by MakhouT** [comment]
Does this mean we will be able to use the latest react-native version with UWP? As in my case I was using the 0.59.8, but after using the UWP cli, it changed my react-native dependency to a stable version on a specific branch with a specific version. Would be great it we can instantly use the latest react-native version. Especially in this case where 0.59 has a lot of great improvements!

**Comment by harinikmsft** [comment]
Yes, that's the goal. We are simultaneously working on updating `react-native-windows` version to 0.59 as well, so once that's done, you should be unblocked from using it. 

This issue is trying to track a more scalable way for us to move off of a fork/branch structure for the windows implementation so that it would be easy to submit PRs to master react-native when we make updates that can accrue to react-native instead of locally for windows-only.

**Comment by kmelmon** [comment]
It is now possible for customers to use the not-forked version of react-native.  We also are now caught up to version 60 so this task is largely unnecessary, closing
