### ISSUE TITLE
Sample App doesn't work well in Dark Theme

### ISSUE THREAD

**Issue by vidhartbhatia** [microsoft/react-native-windows#2757]
### Environment

1. `react-native -v`: react-native-cli: 2.0.1
react-native: 0.59.0-microsoft.11
2. `npm ls rnpm-plugin-windows`: react-native-windows@0.59.0-vnext.83 D:\React_Native_Windows\react-native-windows\vnext
`-- (empty)
3. `npm ls react-native-windows`: react-native-windows@0.59.0-vnext.83 D:\React_Native_Windows\react-native-windows\vnext
`-- (empty)
4. `node -v`: v10.16.0
5. `npm -v`: 6.9.0
6. `yarn --version`: 1.16.0

- Visual Studio Version: 2017
- Build Configuration: Debug x64

### Steps to Reproduce
In Universal Sample App
Set Windows Theme to dark
or update App.xaml to include  RequestedTheme="Dark"
### Expected Behavior

The samples should work with dark theme and the text should be readable

### Actual Behavior
Styling is wrong in many examples. Text is not readable (White on white background)
![image](https://user-images.githubusercontent.com/23387006/61069993-6b424980-a3c2-11e9-852c-21eae966c436.png)
![image](https://user-images.githubusercontent.com/23387006/61069890-27e7db00-a3c2-11e9-8ad2-1a5f3ef3ac2b.png)
![image](https://user-images.githubusercontent.com/23387006/61069896-2f0ee900-a3c2-11e9-941d-d6e9f5882c6b.png)

### Additional context

Temporarily forcing sample app to be in Light theme in [Updated Flyout to attach as ContextFlyout on Target](https://github.com/microsoft/react-native-windows/pull/2744)

**Comment by harinikmsft** [comment]
This is occuring because RNTester is a x-plat test scenario and we cannot change it to use the new theming APIs .. yet.. as they are not xplat RN APIs at this time. For now, the workaround to have the RNTester sample app have RequestedTheme = Light always is ok. 

@kikisaints  - can you add a documentation guide that shows how to handle the themeChanged APIs and provide x-plat styles so apps have a way to handle it until we are ready for these aPIs to be cross-plat.

**Comment by kikisaints** [comment]
@harinikmsft I understand documenting the theme changed API... but are you asking that I provide light/dark x-plat RN styles for every component and page within the sample app? That might take a while...

**Comment by NickGerleman** [comment]
The majority of RNTester is theme aware as of 0.62.
