### ISSUE TITLE
startAnimatingNode() exists in NativeAnimatedModule, but only one callback may be registered to a function in a native module.

### ISSUE THREAD

**Issue by adamgorMSFT** [microsoft/react-native-windows#2981]
"The callback startAnimatingNode() exists in module NativeAnimatedModule, but only one callback may be registered to a function in a native module."

I am still investigating it, but I think there might be something with the 
react-native-windows/ReactUWP/Modules/Animated/ 
NativeAnimatedNodeManager or NativeAnimatedModule.

The problem doesn't occur in our app on Android, only on windows RNW vnext.

I will update if I can identify more useful information regarding this problem.

**Comment by asklar** [comment]
Spoke to @adamgorMSFT, "I am not positive that we see this anymore in RN60.  If we do its pretty rare and I don't have a good repro anymore". Closing, please reopen if/when this shows up again.

**Comment by felisadeang** [comment]
My repro: 
We had our animations behind a flight. For all, useNativeDriver is set to true.

All I did was set the flight to true then run the app. The crash with the error sometimes appears on my first navigation around the app, and sometimes it takes a few different times of navigation. If it helps, we only have opacity and transform animations.

**Comment by felisadeang** [comment]
Had a colleague help me look into this.

The NativeAnimatedModule uses AnimationDriver to execute each animation. It then calls the callback when you start an animation, but it also presumably does something that causes the animation to prematurely stop if you stop it. It will call endCallback in both cases. Her theory is that sometimes the endCallback is used in both start and stop animation when it really should only be called once.

So the crash occurs when an animation is stopped prematurely. In our case (Calendar app), it happens when we stop an animation prematurely. Our appointments fade in and when navigating to another month quickly (before all animations have had a chance to conclude), the crash happens. It’s easier to make this happen when there are a lot of appointments which, in turn, means that a lot of animations are running at once.

To support her theory, she did the following:
She had trace breakpoints enabled in AnimationDriver::StartAnimation and AnimationDriver::StopAnimation (found here https://github.com/microsoft/react-native-windows/blob/ce0f4a3a91e31207d2aa1691cfb55d159457e5d0/vnext/ReactUWP/Modules/Animated/AnimationDriver.cpp). She had it log out the id of the callback, and differentiated start and stop in the traces. She got the bug to repro, and count the number of times the error in the view debug console appears then saw that the ids in the stop callbacks matched some of the callback ids of the start block, and the number of them that matched matched the number of times the error had been fired on the view side.

It seems as though there’s an effort to guard against running the callback in StopAnimation, but it seems like it sometimes doesn’t work. Also, it’s odd that our appointments have callbacks given that we do not pass a callback into the start function on Animated.timing()
