### ISSUE TITLE
Implement Modal

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#2989]
## Summary
vnext has not yet implemented Modal.  See https://facebook.github.io/react-native/docs/modal

- [ ] visible
- [ ] supportedOrientations
- [ ] onRequestClose
- [ ] onShow
- [ ] transparent
- [ ] animationType
- [ ] hardwareAccelerated
- [ ] onDismiss
- [ ] onOrientationChange
- [ ] presentationStyle
- [ ] animated

**Comment by chrisglein** [comment]
Moving to track this on a project board: https://github.com/microsoft/react-native-windows/projects/22

**Comment by chrisglein** [comment]
Not in lean core, moving out to M5.

**Comment by exotexot** [comment]
Would enjoy having Modals in RNW :)

**Comment by ryfow** [comment]
Another vote from me. This has been the most annoying part of porting our app to Windows by far.

**Comment by exotexot** [comment]
Having had the same issue, I used https://microsoft.github.io/react-native-windows/docs/flyout-component those which behaves very similarly to Modal components.

**Comment by chrisglein** [comment]
@gillpeacegood You had some need for this. Can you list what features you need from Modal so we can go after this with the right prioritization. It's not yet currently implemented.

**Comment by gillpeacegood** [comment]
I've had to back fill it with a JS library (react-native-root-modal). It would have been good to have known about it from the feature parity documentation https://microsoft.github.io/react-native-windows/docs/parity-status

**Comment by asklar** [comment]
@chrisglein do we know what APIs we need? there is a modal component in core and a community module too. The community module has a lot more APIs. It will be good to understand prioritization.

**Comment by capc0** [comment]
Modal support would be great. In our case we need it to implement a layover-style loadingspinner that prevents all touch events while its visible.

**Comment by SBS-olessia** [comment]
Is there an ETA for when modals for windows might be implemented?

**Comment by acaininet** [comment]
Seems like many packages use Modal to implement common modern controls. What is the roadmap for Modal? Or is there a current workaround?

**Comment by ohzak** [comment]
nice to notice how this matter is substantially ignored since 4 or even more years, while nowadays modals are utilized everywhere XD

**Comment by exotexot** [comment]
https://github.com/microsoft/react-native-windows/issues/2989#issuecomment-691201381

**Comment by jonthysell** [comment]
Related: #11157

**Comment by chrisglein** [comment]
For many years now we haven't supported [Modal](https://reactnative.dev/docs/modal) for Windows. This is largely due to the fact that the Modal component itself doesn't do much of the heavy lifting people come to expect from this type of UI on desktop (where there are more demands than on the constrained screen of mobile). To help address those we do have 2 Windows-only components that provide more desktop and UWP/XAML-centric behavior: [Flyout](https://microsoft.github.io/react-native-windows/docs/flyout-component) and [Popup](https://microsoft.github.io/react-native-windows/docs/popup-component)

On the Paper renderer, we're not going to implement Modal. We're investing our time in closing the gap on the [Fabric](https://github.com/microsoft/react-native-windows/issues/12042) renderer, where this question is going to be revisited anew. The work to track Modal on Fabric is [here](https://github.com/microsoft/react-native-windows/issues/11157). As such, I'm going to close _this_ issue as Not Planned and we'll look to the Fabric issue moving forward.
