### ISSUE TITLE
View onAccessibilityEscape

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/react-native-windows#3119]
https://facebook.github.io/react-native/docs/accessibility.html#onaccessibilityescape-ios
Investigating

**Comment by chrisglein** [comment]
At first glance it appears that this is legacy and replaced by [accessibility actions](https://reactnative.dev/docs/accessibility#accessibility-actions). Since this has never worked on Windows, it seems higher priority to support the modern way of doing this. @AgneLukoseviciute if you can confirm that accessibility actions are the intended future direction then we can close this as a "won't fix".

**Comment by AgneLukoseviciute** [comment]
There's no info regarding this that I could find from RN side, but it does seem that they are going in the direction of preferring accessibilityActions for this with the very [recent addition](https://github.com/facebook/react-native/pull/31532) of a11y actions on core components and their own accessibility examples were changed to use onAccessibilityAction where event==escape as opposed to using onAccessibilityEscape. I've tested on iOS with VoiceOver and the behavior is identical for both.
