### ISSUE TITLE
View onAccessibilityTap

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/react-native-windows#3120]
https://facebook.github.io/react-native/docs/accessibility.html#onaccessibilitytap-ios
Partial
Via ViewViewManager, not shared with other components

**Comment by chrisglein** [comment]
At first glance it appears that this is legacy and replaced by [accessibility actions](https://reactnative.dev/docs/accessibility#accessibility-actions). Since this has never worked on Windows, it seems higher priority to support the modern way of doing this. @AgneLukoseviciute if you can confirm that accessibility actions are the intended future direction then we can close this as a "won't fix".

**Comment by AgneLukoseviciute** [comment]
https://github.com/microsoft/react-native-windows/issues/3119#issuecomment-880161412

> There's no info regarding this that I could find from RN side, but it does seem that they are going in the direction of preferring accessibilityActions for this with the very recent addition of a11y actions on core components and their own accessibility examples were changed to use onAccessibilityAction where event==escape as opposed to using onAccessibilityEscape. I've tested on iOS with VoiceOver and the behavior is identical for both.
