### ISSUE TITLE
Can casing be standardized, or at least more consistent?

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#3318]
https://github.com/microsoft/react-native-windows/blob/78e55b4b2ca07c79c3350babb7d69009f5f53e4b/vnext/include/ReactUWP/Views/ShadowNodeBase.h#L73

Can casing be standardized? Or is there a specific reason why there is a mixture of AddView() vs createView()   (notice the first letter of the method).

If there isn't a valid reason for this, the longer it goes on, the harder its going to be change later on. Because I know this will be a breaking change for everyone. 

```
ShadowNodeBase methods:
    onDropViewInstance
    dispatchCommand
    removeAllChildren
    AddView
    RemoveChildAt
    createView
    NeedsForceLayout
```

**Comment by licanhua** [comment]
`AddView` is the naming convention for function name in UWP app.
`createView`  convention is used by react-native, for example, [UIManager.h](https://github.com/facebook/react-native/blob/master/ReactCommon/fabric/uimanager/UIManager.h)
react-native-windows is the combination of UWP and react-native, and that's why you see two conventions here.
If you see `createView` in react-native-windows, most likely you are hitting the API boundary of the two. For example, react-native-windows is calling react-native functions

**Comment by namrog84** [comment]
Today I learned.  That seems reasonable to me. Closing issue.
