### ISSUE TITLE
Text.onPress is not raised when it's nested in another text

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3373]
### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.60.0-microsoft.5

2. `npm ls rnpm-plugin-windows`:
react-native-windows-repo@0.0.1 F:\repo\react-native-windows
`-- rnpm-plugin-windows@0.3.5  extraneous
npm ERR! extraneous: rnpm-plugin-windows@0.3.5 F:\repo\react-native-windows\node_modules\rnpm-plugin-windows

3. `npm ls react-native-windows`:
react-native-windows-repo@0.0.1 F:\repo\react-native-windows
`-- (empty)

4. `node -v`:
v10.16.3

5. `npm -v`:
6.9.0

6. `yarn --version`:
1.17.3

Then, specify:

- Target Platform Version(s):

- Target Device(s):

- Visual Studio Version: Visual Studio 2019 16.3.1

- Build Configuration:
Debug

### Steps to Reproduce

(Write your steps here:)

1.  Create Text like this
```
export function AccessibilityTestPage() {
    const [pressedCountNested, setPressedCountNested] = useState(0);
    const [pressedCount, setPressedCount] = useState(0);
    return (
        <View>
            <Text accessible={true} accessibilityLiveRegion="polite" style={{fontWeight: "bold"}}>
                I'm bold
                <Text style={{color: 'red'}} onPress={() => setPressedCountNested(pressedCountNested + 1)} accessible={true} accessibilityLiveRegion="polite">Pressed {pressedCountNested} times</Text>
            </Text>
            <Text style={{color: 'green'}} onPress={() => setPressedCount(pressedCount + 1)} accessible={true} accessibilityLiveRegion="polite">Pressed {pressedCount} times</Text>
        </View>)
}
```

or checkout PR #3260, then goto 'Accessibility Test Page'

### Expected Behavior
When clicking the  'red' text, the pressedCountNested should be update

(Write what you thought would happen.)

### Actual Behavior
pressedCount is changed when clicking 'green' text.
but pressedCountNested doesn't change when clicking 'red' text

(Write what happened. Add screenshots!)
![image](https://user-images.githubusercontent.com/6290692/66524757-2785db80-eaa8-11e9-879f-5bf1399be707.png)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

### Additional context

(Write any other additional context that may help in root causing the issue.)

**Comment by chrisglein** [comment]
@licanhua Do you have a scenario that requires this right now? It seems like the way we're handling Text today won't be able to handle this. Is this a hyperlink scenario? If we don't have a scenario for this, given the complexity to achieve this I think this is won't fix.

**Comment by licanhua** [comment]
@chrisglein This is also the example of text in https://facebook.github.io/react-native/docs/text.html
```
   return (
      <Text style={styles.baseText}>
        <Text style={styles.titleText} onPress={this.onPressTitle}>
          {this.state.titleText}{'\n'}{'\n'}
        </Text>
        <Text numberOfLines={5}>
          {this.state.bodyText}
        </Text>
      </Text>
```

**Comment by chrisglein** [comment]
Ah, okay, this is in the initial set of examples for Text. That makes this more of an issue for sure.

**Comment by rectified95** [comment]
After some debugging, I see that nested \<Text> tags get coalesced into one XAML element. For example, clicking on a nested text block, will trigger its <text> parent's onPress callback, but not the clicked element's:
```
<View>
  <Text accessible={true} onPress={() => setCntOuter(cntOuter + 1)} style={{fontWeight: "bold"}}>
    Outer pressed {cntOuter}{'\n'}
    
    <Text style={{color: 'red'}} onPress={() => setCntNested(cntNested + 1)}>
      Nested pressed {cntNested} times
    </Text>
  </Text>
  <Text style={{color: 'green'}} onPress={() => setCnt(cnt + 1)}>
    Single pressed {cnt} times
  </Text>
</View>
```
Looking for a way to work around this.

**Comment by rectified95** [comment]
RNW \<Text> nested tag translation uses a combination of XAML Run and Span elements, which get added to the collection of Inline elements of the resulting TextBlock and recursively its children Spans, while following these rules:
1. the outermost \<Text> becomes the parent XAML TextBlock
2. each piece of the string content of a \<Text> on a given level becomes a XAML child element of type Run 
3. each nested \<Text> becomes a XAML Span child element, appended to the InlineCollection of its parent, becoming a sister element on the same level as the Run elements.

For example, the JSX code on the left, produces the XAML tree on the right:
```
<Text>                 //<TextBlock>
   "outer" {X}            //<Run> <Run>
  <Text>                  //<Span>
    "inner_1" {Y}            //<Run> <Run>
    <Text>                   //<Span>
      "inner 2"                 //<Run>
    </Text>
  </Text>
</Text>

```
Since nested React \<Text> elements only produce one XAML UIElement (Span and Run are of type Inline), all clicks within the resulting XAML TextBlock cause the same JS onPress callback to be invoked - all clicks on the nested \<Text> elements are deemed to be from within the same outer React \<Text> element, because only UIElement instances raise XAML events.

After talking to Keith, I have an outline of a possible solution:
inside TouchEventHandler::TagFromOriginalSource(), we could be performing a more refined hit test in case a TextBlock was identified as the source of the PointerPressed event. Iterate over the InlineCollection of the XAML TextBlock, for each Inline (Run/Span) element call (recursively for Span) ContentStart() and ContentEnd() to get the 2 TextPointers, and from them the bounding box. From that, we can check if the pointer coordinates fall within a child \<Text> or indeed the outer one, as we now ascribe all click events to.

Caveats: this does not handle text wrapping, which can happen over multiple lines, and makes obtaining the bounding boxes more involved; nor does it account for right-to-left scenarios.
@chrisglein Can I spend some time, say 2-3 days, to try and get this working? Currently, we fail to handle this properly for all cases, so perhaps implementing it even without wrapping and R2L is worth it. Otherwise, let's pull this back for retriage.

FYI and thank you - @kmelmon 

Ref:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.documents.inline?view=winrt-19041
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.documents.textelement.contentstart?view=winrt-19041#Windows_UI_Xaml_Documents_TextElement_ContentStart
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.documents.textpointer?view=winrt-19041
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.documents.textpointer.getcharacterrect?view=winrt-19041#Windows_UI_Xaml_Documents_TextPointer_GetCharacterRect_Windows_UI_Xaml_Documents_LogicalDirection_

**Comment by chrisglein** [comment]
@rectified95 It's worth digging in on this one as we have had lots of similar issues. Take a look through #4927, #3417, #3457. You may be able to fix some at the same time. Test whatever changes you make against those scenarios too.
