### ISSUE TITLE
Suggestion: Offer guidance on setting up without visual studio

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/react-native-windows#3396]
I would love to see guidance on getting set up without having to install visual studio.  Perhaps by leveraging chocolatey to install the SDKs that each workload features.

**Comment by chrisglein** [comment]
There was a similar question posed here: #3257 (alongside some other related issues). We don't today have a golden path to set up the SDK without just installing Visual Studio but there may be enough interest. Given that this is our second request, I'd say probably yes. Posing this as a documentation request.

**Comment by JunielKatarn** [comment]
Because the MSVC compiler is needed, I don't think there is a way to install the dependency without Visual Studio.

That said, we could avoid using the GUI installer by automating the VS installer command line.
See `vnext/Scripts/Tfs/Install-VSFeatures.ps1` for reference.

**Comment by acoates-ms** [comment]
I believe you can install the build tools without VS:
https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019

**Comment by asklar** [comment]
@chrisglein we can leverage the work I did for WinUI 3.

**Comment by temetvince** [comment]
Hello, I see that this has been moved back. I believe this feature is important, because react native windows is MIT licensed, while Visual Studio is not. Unless I pay for Visual Studio, I must use the Community version, which limits my use for commercial purposes to 5 or fewer developers. In effect, this means that any business with >5 devs using this MIT licensed free software is actually now in violation of MS's licensing models which could incur litigation against the business, even though they thought they were using open source software.

Please correct me if I'm misunderstanding. Wouldn't be the first time :D

**Comment by NickGerleman** [comment]
I think we have all of this now documented. Please feel free to reopen if there is anything missing.

**Comment by tommyhtran** [comment]
This is still not documented.

The manual instructions at https://microsoft.github.io/react-native-windows/docs/rnw-dependencies do not show an alternative to installing Visual Studio. Running the provided script, `rnw-dependencies.ps1`, is not acceptable because it'll resort to installing Visual Studio Community edition.

I went ahead and installed JetBrains' redistributable of MSBuild, but found that React Native Windows CLI (`@react-native-windows/cli`) has a hard dependency on `vswhere.exe` in order to find MSBuild. Looking at the [documented options for the CLI](https://microsoft.github.io/react-native-windows/docs/run-windows-cli), there is no option to provide a path to MSBuild.

**Comment by asklar** [comment]
@tommyhtran unfortunately e don't have plans to support JetBrains, only Visual Studio.

**Comment by 500-internal-server-error** [comment]
> We don't today have a golden path to set up the SDK without just installing Visual Studio but there may be enough interest. Given that this is our second request, I'd say probably yes.

Is there documentation on how to setup without Visual Studio yet? I can't find it if there is. As mentioned previously, the provided script installs Visual Studio, which is not really an alternative over installing Visual Studio manually.

**Comment by asklar** [comment]
Hi @500-internal-server-error , we don't have plans to support other IDEs/build tools at this time.
