### ISSUE TITLE
ReactNative reference is not added properly

### ISSUE THREAD

**Issue by SelvaraniAlagumuthu** [microsoft/react-native-windows#3523]
Hi,

I trying the react-native in windows , so i created the react-native init appname --version 0.59.0.
react-native windows --template vnext. Its automatically created vnext version 0.59. my system requirment is. Windows 10 pro @2019 and i have VisualStudio2019. While i install react-native-file-viewer into this react-native windows sample app. But inside react-native-file-viewer under Refernces i ReactNative i am getting resolve as false. And also while try to run the app in simulator/localmachine i got the error as ReactNative not found in RNFS.  Could you please help me to resolve this. Because i am very new in react-native as well as in VisualStudio

**Comment by chrisglein** [comment]
Our support for native modules in vNext is currently in progress (see project https://github.com/microsoft/react-native-windows/projects/6). While [react-native-file-viewer](https://github.com/vinzscam/react-native-file-viewer) lists support for Windows, that would be for vCurrent. Since you've specified `--template vnext` you're getting the new implementation that is currently incompatible with that module. We'll have our native modules support online very soon and be able to support this one as well. In the meantime your workaround is to not use `--template vnext`.

@harinikmsft as an FYI for building the module support list
