### ISSUE TITLE
Add dev settings submenu to debug options

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#358]
The DevSupportManager debug options menu should have a sub-menu that allows, e.g., updating the debug server endpoint.

**Comment by rozele** [comment]
This requires a bit more work to support XAML navigation, native back button handling, and a bug when XAML is not initialized properly for UWP libraries.  Going to see if the bug is fixed in the latest Universal Windows SDK.

**Comment by rozele** [comment]
Some progress has been made in http://github.com/rozele/react-native-windows/tree/issue358

**Comment by jtag05** [comment]
Can someone explain to me how this is a 2 year old issue, and incredibly debilitating and yet still not resolved? 

I have tracked down how to resolve the issue for normal operation, but utilizing remote js debugging is still inoperable. Line 63 of `DevServerHelper.cs` allows a reference to a setting for `DebugServerHost`, but not on line 104 of the same file for `JavaScriptProxyHost`. Modifying this in the core code resolves my issue locally but will not scale. So PLEASE resolve this at least to the level of being able to change a setting through application code.

**Comment by bshrader-turner** [comment]
@rozele Is there a workaround for this with the current codebase?  I'm trying to run my app on my Xbox and getting the same red box error that others have reported.  But the recommended solution is to change the IP address in DevServerHelper.cs, and that file no longer exists.  Is there something else I could do instead?

**Comment by bshrader-turner** [comment]
For anyone else having the same issue where your Xbox couldn't find the JS bundle server, I wanted to share my solution.  I used the "Using Offline Bundle" section [here].(https://github.com/Microsoft/react-native-windows/blob/master/docs/RunningOnDeviceWindows.md#using-offline-bundle)

I had to change `index.windows.js` to `index.js`, and then when you run it from Visual Studio, select the DebugBundle instead of Debug when you want to run it on your Xbox.  So now I'm using `react-native start` and the Debug option to run it on my local machine, and when I want to test it on the Xbox, I build the bundle and use the DebugBundle option.  It's working great for me so far.

**Comment by brodybits** [comment]
> I used the "Using Offline Bundle" section [here](https://github.com/Microsoft/react-native-windows/blob/master/docs/RunningOnDeviceWindows.md#using-offline-bundle).

Seems to be moved to: <https://github.com/microsoft/react-native-windows/blob/master/current/docs/RunningOnDeviceWindows.md#using-offline-bundle>
