### ISSUE TITLE
Question: Support for WPF in vNext?

### ISSUE THREAD

**Issue by PairedPrototype** [microsoft/react-native-windows#3666]
I'm looking to get started on making an app using React Native for Windows. However, it is my understanding that there are issues using Visual Studio 2019 build tools when building WPF on vCurrent and that there will be no more fixes for vCurrent since work is being focused on vNext.

I've tried to create a project for WPF on vNext, but it appears it is not supported as of yet. Will vNext eventually be supporting WPF projects at some point in the future?

**Comment by chrisglein** [comment]
We have no plans to support WPF on vNext. Juggling many solutions is challenging so we've decided to focus on the vNext implementation, eventually targeting [WinUI3](https://docs.microsoft.com/en-us/uwp/toolkits/winui3/) to empower broad support across many versions of Windows.

Is there a reason you want to target WPF under the covers instead of the inbox UWP XAML that vNext uses?

**Comment by lmcdougald** [comment]
Windows 8.1 support is helpful for apps that should run on Windows Server 2012, in particular. An RDP server running Windows Server 2012 should be able to support React Native apps.
