### ISSUE TITLE
Fix Driver letter casing problem on metro/node_haste

### ISSUE THREAD

**Issue by licanhua** [microsoft/react-native-windows#3670]
Driver-letter casing contributed to the ```error Unable to resolve module `warnOnce` ```, and it's hard to debug. 
This problem is found when I made `react-native bundle` in msbuild, and it always failed in the VS IDE and VS code IDE, but passed in cmd.exe. Finally I figured out the problem is related to the driver letter casing.

I didn't narrow down the problem to which line of code yet. From high level and logs, I found the we may run into `warOnce` error based on your windows and your environment 

I don't think it has impact on Linux and Mac, so Windows is the only victim. and it's high possibility that RNW customer hits this too. we need to resolve it and contribute it back to metro/node_haste.

It’s very easy to reproduce it by steps like below. At the beginning, it's `c:\\`, run the bundle command, then switch it to `C:\\` and run the bundle again. one of the bundle command may fail. 

c:\repo\react-native-windows\packages\E2ETest>yarn run bundle
c:\repo\react-native-windows\packages\E2ETest>cd ..\..

c:\repo\react-native-windows>cmd /K cd /d "C:\repo\react-native-windows\packages\E2ETest"
**C**:\repo\react-native-windows\packages\E2ETest>yarn run bundle

Here is an example of error, and it doesn't provide useful information when this problem happens.
```
1>------ Build started: Project: ReactUWPTestApp, Configuration: Release x64 ------
1>  C:\repo\react-native-windows\packages\E2ETest
1>  yarn run v1.19.1
1>  $ just-scripts prepareBundle && react-native bundle --platform windows --entry-file dist/app/index.js --bundle-output windows/ReactUWPTestApp/Bundle/index.windows.bundle --assets-dest windows/ReactUWPTestApp/Bundle
1>  [6:06:23 PM] Γûá started 'prepareBundle'
1>  [6:06:23 PM] Γûá finished 'prepareBundle' in 0.01s
1>  Loading dependency graph, done.
1>  error Unable to resolve module `warnOnce` from `C:\repo\react-native-windows\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module `warnOnce` does not exist in the Haste module map
1>  
1>  This might be related to https://github.com/facebook/react-native/issues/4968
1>  To resolve try the following:
1>    1. Clear watchman watches: `watchman watch-del-all`.
1>    2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
1>    3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
1>    4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`. Run CLI with --verbose flag for more details.
1>EXEC : error : Unable to resolve module `warnOnce` from `C:\repo\react-native-windows\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module `warnOnce` does not exist in the Haste module map
1>  
1>  This might be related to https://github.com/facebook/react-native/issues/4968
1>  To resolve try the following:
1>    1. Clear watchman watches: `watchman watch-del-all`.
1>    2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
1>    3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
1>    4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
1>      at ModuleResolver.resolveDependency (C:\repo\react-native-windows\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:183:15)
1>      at ResolutionRequest.resolveDependency (C:\repo\react-native-windows\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
1>      at DependencyGraph.resolveDependency (C:\repo\react-native-windows\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
1>      at Object.resolve (C:\repo\react-native-windows\node_modules\metro\src\lib\transformHelpers.js:264:42)
1>      at dependencies.map.result (C:\repo\react-native-windows\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)
1>      at Array.map (<anonymous>)
1>      at resolveDependencies (C:\repo\react-native-windows\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
1>      at C:\repo\react-native-windows\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
1>      at Generator.next (<anonymous>)
1>      at asyncGeneratorStep (C:\repo\react-native-windows\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
1>  error Command failed with exit code 1.
1>  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1>C:\repo\react-native-windows\vnext\ReactNativeWindows.targets(10,9): error MSB3073: The command "
1>C:\repo\react-native-windows\vnext\ReactNativeWindows.targets(10,9): error MSB3073:     cd
1>C:\repo\react-native-windows\vnext\ReactNativeWindows.targets(10,9): error MSB3073:     yarn run bundle
1>C:\repo\react-native-windows\vnext\ReactNativeWindows.targets(10,9): error MSB3073:     " exited with code 1.
```

**Comment by licanhua** [comment]
node-haste may be no longer needed in RN 0.61

**Comment by chrisglein** [comment]
Should be unneeded as of #3543. Validate after.

**Comment by chrisglein** [comment]
@kmelmon Am I remembering correctly that you mentioned a drive capitalization issue with Metro?

**Comment by kmelmon** [comment]
> @kmelmon Am I remembering correctly that you mentioned a drive capitalization issue with Metro?

That's correct, this is the same issue.  Ideally we would make a change to Metro to fix this, rather than working around it in our scripts.

CanHua is also bringing up a valid complaint that the error you get from Metro is not useful.  It would be worthwhile to put some effort into making Metro do more validation of your config up front., which would help avoid long, largely avoidable investigations as to what part of the config is wrong.

**Comment by kmelmon** [comment]
@asklar this is a good example of a hard-to-diagnose metro error.

**Comment by kmelmon** [comment]
We may be able to leverage this community module, or copy what they've done, to improve this:
https://www.npmjs.com/package/true-case-path
One limitation of this solution is that it does not normalize the drive letter.  We'd likely want to make that improvement as well.

**Comment by asklar** [comment]
> We may be able to leverage this community module, or copy what they've done, to improve this:
> https://www.npmjs.com/package/true-case-path
> One limitation of this solution is that it does not normalize the drive letter. We'd likely want to make that improvement as well.

I believe it does normalize the drive letter too:

> trueCasePathSync('**c**:\\users\\asklar')
'**C**:\\Users\\asklar'
>

**Comment by kmelmon** [comment]
Note:  This needs to be fixed in the CLI and possibly also in metro.  We can keep this bug here to track.

**Comment by jackerghan** [comment]
Btw, @sahrens and I hit this issue too - in Spencer's case we were not able to find AccessibilityInfo instead of warn_once. It does take a long time to figure out what goes wrong, as it is sporadic based on the casing of the drive letter in your command prompt... We should drive a fix for this where it needs to be - can we help?

**Comment by kmelmon** [comment]
@jackerghan thanks!  I can see two possible solutions:
1) Change the Metro code.  I think this would involve changing the haste map code to work with normalized paths (or possibly just use case insensitive search) when the platform is Windows.  This feels more risky but would solve the problem at its source.
2) Change the CLI code.  All the instances I've seen so far of this issue came from props being pushed into Metro by the CLI (via the start command).  We could normalize paths before pushing them into Metro when the platform is Windows.

One of the unknowns with either solution is how to best normalize the paths (assuming we do it this way).  The https://www.npmjs.com/package/true-case-path community module might work, but it's not clear if there's a more standard way, also there may be issues with taking a dependency on this module.

**Comment by MichaReiser** [comment]
Hy everyone. I'm collecting issues related to Metro on Windows to understand how I can improve the developer experience. 

Would someone be able to create a minimal repo and create a new issue in the [Metro repository](https://github.com/facebook/metro)? I can't promise you that I'll have the time to work on it right away but am assembling a list of the most blocking issues. Please let me know (or create an issue) if you're aware of anything else related to metro that would improve the react native windows developer experience.

**Comment by kmelmon** [comment]
Thanks @MichaReiser.  This issue is likely not as noticeable nowadays, due to a change @acoates-ms made a while back: 
 https://github.com/react-native-community/cli/pull/1115
@chrisglein  I was unable to repro this using the original repro steps, and do not know of a way to repro with current bits, closing
