### ISSUE TITLE
Several RNTester pages no longer load

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3876]
This appears to be more fallout from #3865 

Two RNTester pages no longer load:
-Text
-Alert

Hopefully the fix is similar to https://github.com/microsoft/react-native-windows/pull/3867

**Comment by chrisglein** [comment]
@NickGerleman sounds like a regression from your change. A similar fix may be described above. Can you fix the regression?

**Comment by NickGerleman** [comment]
I can take a look. I'm still not convinced the change I made had anything to do with the regression, unless we had a dependency change from the RN bump. @kmelmon do we know if there are any other places whee we have been mixing commonjs and ES6 default import?

**Comment by kmelmon** [comment]
Regarding repro - you may need to delete all haste-map-metro-xxx files from your %TEMP% directory to be in a clean state.

I do think we still have places in the code that do ES6 style exports, but I don't know if there are any mismatches between exports/imports.  I'd like to understand the metro requirement better.  Can you point me to where you were looking in metro code to see how it handles these?

**Comment by NickGerleman** [comment]
@kmelmon I didn't look super deeply into Metro, apart from seeing that it would run Babel internally. That should allow compiled Typescript doing ES6 export to interop with JS doing ES6 import (at least if some level of Babel rules are used).

In the original bug though, we were actually doing a CommonJS import of a ES6 default export (transpiled to Babel's CommonJS representation of ES6 modules). This is kind of weird semantically, since CommonJS exports are always just a single object. I.e. there isn't really a notion of "default import".

From the limited searching I did, I couldn't find any documented behavior of how this is supposed to act. Regardless of whether it was working before, we should probably avoid mixing CommonJS and ES6 module syntax, especially when default exports are involved since that's unique to ES6. 

I will look at these pages shortly to see if the issue is similar.

**Comment by NickGerleman** [comment]
I was able to find two exports where we mismatch with upstream, but both are benign right now. The issues with RNTester seem to be unrelated to bundling. E.g. for "Text", we fail because RNTesterExampleContainer.js expects that example modules define a property called "Examples" and the Windows override of TextExample doesn't do this. From what I can tell, this has been broken for quite some time. I haven't debugged through Alert, but I'm going to assign this back over since these issues seem unrelated.

**Comment by NickGerleman** [comment]
Reopening until we fix Alert. Should maybe be a separate issue?

**Comment by kmelmon** [comment]
Split this out into https://github.com/microsoft/react-native-windows/issues/4091
