### ISSUE TITLE
Build tool to help integrate diffs in platform overrides

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3907]
# Proposal: [Platform override integration tool] 
Build a tool to help automate the process of integrating diffs in RN4W platform overrides when RN4W platform does an upgrade to latest version of react-native

## Summary
The process of upgrading RN4W to latest version of react-native involves manually diffing every one of our platform overrides (eg Dimensions.windows.js) with changes that happened in react-native/master.  This process is too manual and error-prone.  This proposal is tracking building a tool to help automate this process.  There is a spectrum of possibilities here - on the simpler end it could be something that helps us with the manual process (eg it could just tell us which files are interesting), on the complex end it could be something that automates the process of integrating diff's.

**Comment by kmelmon** [comment]
@acoates-ms Since you've done many of our upgrades I want to first ask - have you already done something in this space?

**Comment by acoates-ms** [comment]
No I havent got any kind of automated tool.  We did start trying to add sordid comments to help with diffing of forked files, but it's inconsistently applied.

**Comment by NickGerleman** [comment]
@kmelmon @acoates-ms @ddalp I was thinking about this a bit earlier. Medium-term, we could add some tooling to let us detect breaking changes on a per commit basis and integrate new facebook commits otherwise. The specific idea I had in mind would use integrity checking to break the build if fb souces change that we have analogs to.

E.g. if Facebook added a change to RNTester that required changes in all example pages, we would be hosed, since they would change their sources for Android and iOS, and we don't have CI coverage. Integrity checks of a page we mimic would detect Facebook needed to make a change there, and would alert us to do the same.

It would be super simple to add to the native build. Likely not too crazy for the JS build either.

**Comment by NickGerleman** [comment]
Closing this since it's happening right now and there have been some newer, more concrete proposals.
