### ISSUE TITLE
Update React Native for Windows to target RN 0.62

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4025]
Issue for move to 61 here: #3543

Creating an issue to track what we need to do to update to 62. Our goal is to get caught up and remain current, so we'll want to start investigating this and building infrastructure to improve our update process as soon as 61 support is complete.

**Comment by harinikmsft** [comment]
v62 is in RC and we may want to wait until it is stable before upgrading react-native-windows.

**Comment by NickGerleman** [comment]
Copying from a thread offline, with some context. In addition to what's mentioned below, we have hacks around Native modules like PlatformConstants that we should address to make our lives easier.

-----

We should timebox some effort after the 0.61 to focus on making future merges less painful. Part of this is tooling, but I want to really start thinking about how we can restructure things in both RNW and upstream react-native to make out patches less invasive. E.g. changing how upstream exposes platform specific APIs so that we don't need to stub/bundle them, looking at extracting forked ViewProps to be Win specific views, removing our JS hosting changes, etc. In general, upstream changes have enough latency that I feel like they should be front-loaded.

We should move the JS build to diffs before the 62 upgrade. This should also help with the above, in making it more apparent as to what classes of changes we have to think about.

**Comment by kmelmon** [comment]
@NickGerleman has been working on this and is almost finished
