### ISSUE TITLE
Add Windows support to expo-file-system

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#4027]
> expo-file-system provides access to a file system stored locally on the device. Within the Expo client, each app has a separate file system and has no access to the file system of other Expo apps.

https://docs.expo.io/versions/latest/sdk/filesystem/

Somewhat related to the need for these file system modules:
https://github.com/microsoft/react-native-windows/issues/2829
https://github.com/microsoft/react-native-windows/issues/2271

But by supporting this Expo module we of course unblock Windows scenarios in the excellent Expo toolchain.

**Comment by creambyemute** [comment]
Sorry for chiming in here as an extern, but I had some thoughts I had to get rid of regarding FS in React-Native:

- joltup/RN-Fetch-Blob is unmaintained
   - Mostly iOS/Android relevant
- React-Native-FS has been ummaintained and plagued with issues since for some months now (for example write/readFile performance on Android due to JS-Thread encoding/decoding).
   - Mostly Android relevant.
- Both are not prepared for Android 11 Storage changes
   - Mostly Android relevant again.


With these points in mind and expos continuing push for making their libraries usable with a normal rn-cli project instead of an expo project, would it make sense to invest time/investigate whether to support expo-fs?

I just don't see any other FS library that is actually maintained at the moment and FS-Access is often a big part of bigger apps. 
Just my 2 cents, maybe we need a community module instead?

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
