### ISSUE TITLE
'Question: using async/await in native CS modules'

### ISSUE THREAD

**Issue by mtebenev** [microsoft/react-native-windows#4046]
Suppose the following use case:

I have a native CS module enumerating files using
UWP StorageFolder.GetItemsAsync();
The module method accepts a promise which I would like to resolve with the items information like this:
```csharp
    [ReactMethod("getRoot")]
    public async void GetRoot(string name, IReactPromise<DirectoryContentDto> promise)
    {
....
        var fsItems = await mediaLocation.StorageFolder.GetItemsAsync();
...
        promise.Resolve(contentDto);
      }
    }
```

As a result I'm getting access violation at JSValueWriter.writeArgs()

![image](https://user-images.githubusercontent.com/3949381/74015723-31f6aa00-49a2-11ea-98ea-cb565be5d6ad.png)

I have a suspicion that at the moment of the JSValueWriter.writeArgs() call, the COM object is released (and it's clear that there's the context switch when accessing the file system). 

The question is:
1. Is this a valid use case for native modules? I would like to have non-blocking await calls in my native modules.
2. Is this a RNW issue or I am doing something wrong?

**Comment by NickGerleman** [comment]
@vmoroz

**Comment by vmoroz** [comment]
It must be working. I suspect it could be related to the issue with RNW that I fixed in https://github.com/microsoft/react-native-windows/pull/4045 . Before that change we were effectively creating writer on the call stack and it would crash in any async scenario. I will create a unit test to verify the async scenarios and see if code actually works now.

**Comment by mtebenev** [comment]
@vmoroz I confirm it's working in 0.61.0-beta.7
