### ISSUE TITLE
Update Alert placement for dual-screen

### ISSUE THREAD

**Issue by YuliKl** [microsoft/react-native-windows#4118]
# Alert placement on dual-screen devices 

## Summary

When open on a dual-screen device, Alert should position itself out of the way of the seam.

Because RN's Alert component calls native controls, the correct behavior may already be in place. We need to validate whether this is already the case and work with appropriate partner teams if not.

## Timeframe
This work needs to be completed by May.

**Comment by harinikmsft** [comment]
There is working happening in WinUI to ensure the ContentDialog native component in Windows will solve this in which case the RN component will get the fix for free. However, if this work is happening in WinUI3, this fix will not be available in the timeframe asked for above. @YuliKl to figure out the WinUI timeline for this.

**Comment by YuliKl** [comment]
WinUI work is being done for inbox Xaml not WinUI 3.

**Comment by kmelmon** [comment]
Notes:

Since Alert is a static API, it's tricky to know which screen we should center it on.  With WinUI3.0, we're adding logic to use the last focused element as a hint.  It seems possible we could do the same here - FocusManager has an API to retrieve the currently focused element.  There is still a question in the scenario of multiple XAML islands
