### ISSUE TITLE
Left/right style properties are mishandled in RTL

### ISSUE THREAD

**Issue by aschultz** [microsoft/react-native-windows#4167]
The GetThickness and GetCornerRadius functions in PropertyUtils.h are treating Left/Right as equivalent to Start/Stop. This is incorrect and does not align with other RN implementations, nor the CSS standards on web.

paddingLeft, for example, should always control the real-world left side of the control, regardless of any LTR/RTL settings. paddingStart, however, should flip from left to right in an RTL context.

Related: #2109, #2207

**Comment by chrisglein** [comment]
@kmelmon you did a big pass on RTL and I _think_ this one was fixed? Is that true?

**Comment by kmelmon** [comment]
This is actually by design .  Yes it's confusing!  Note carefully that today in react-native, all the left/right properties actually do flip to the other side when direction is rtl.  This was also reported in this issue:

https://github.com/microsoft/react-native-windows/issues/4645

I had a conversation with Eli White about it as I also found it confusing.   Here's the response from Eli:
@kmelmon, I believe this is the known behavior. RN has always flipped left and right in RTL mode. To enable people to have proper RTL support the start and end properties were introduced, but we've never found a good way to migrate the ecosystem to get the left/right properties to not flip anymore. There is a command I18nManager.swapLeftAndRightInRTL(false) that can disable that flipping. Eventually that should be the default, but it is such a big breaking change we have punted on it for 3 years (timing based on some internal documents I've found)

We have this issue tracking adding the API I mentioned above:
https://github.com/microsoft/react-native-windows/issues/4662

**Comment by aschultz** [comment]
So it's not by-design, but a long-standing bug in RN. They could follow the same deprecation pattern they've used for lifecycle methods -- make it known, start issuing warnings, then change the behavior.

Wouldn't it be in RNW's interest to address this sooner while its community is small? If you make the fixed behavior the new default, new community packages will be forced to do the right thing, while the handful of existing apps can opt-in to the broken behavior until they've cleaned up their styles to use the correct names.

**Comment by kmelmon** [comment]
I considered making this behavior change but then Windows would behave differently than all the other platforms.  Considering this is a basic behavior and it is a goal for react-native-windows to be friendly to cross-platform development, I favor consistency.

Having said that I do agree with the sentiment that it would be better if the behavior followed the web standard.

As a starting point we can implement #4662, which at least gives people a way to have the web-standard behavior.  We can also discuss taking another run at changing the default behavior across all platforms at the bi-weekly msft/facebook sync-up.  I'll take that as an action item.
