### ISSUE TITLE
Platform.Version undefined

### ISSUE THREAD

**Issue by kaiguo** [microsoft/react-native-windows#4176]
### Environment

If you are using latest version:
1. `react-native -v`: 0.61.5
2. `react-native run-windows --info`:
  System:
    OS: Windows 10 10.0.19569
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 16.73 GB / 31.79 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react-native: 0.61.5 => 0.61.5
    react-native-windows: 0.61.0-beta.22 => 0.61.0-beta.22
    rnpm-plugin-windows: ^0.5.1-0 => 0.5.1-0
  Installed UWP SDKs:
    10.0.14393.0
    10.0.15063.0
    10.0.17134.0
    10.0.17763.0
    10.0.18257.0
    10.0.18362.0

### Steps to Reproduce

Call `Platform.Version` in code.

### Expected Behavior

Should return the system version.
https://reactnative.dev/docs/platform-specific-code.html#detecting-the-android-version

### Actual Behavior

`Platform.Version` is undefined.

**Comment by kaiguo** [comment]
Re-enable scale transform test in #4169 when this gets fixed.

**Comment by NickGerleman** [comment]
@kaiguo this is somewhat by design. Windows doesn't allow accurate sniffing for OS version. You could reverse engineer the Universal API contract and use that maybe

See  https://github.com/microsoft/react-native-windows/blob/master/vnext/src/Libraries/Utilities/Platform.windows.js and https://github.com/microsoft/react-native-windows/blob/master/vnext/ReactWindowsCore/Modules/PlatformConstantsModule.cpp
