### ISSUE TITLE
Hover detection can cause multiple items to show up as hovered, not just the top item

### ISSUE THREAD

**Issue by Murtaya** [microsoft/react-native-windows#4274]
### Environment

If you are using latest version:
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.60.6

2. `react-native run-windows --info`:
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    Memory: 12.93 GB / 31.91 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
    react-native-windows: 0.60.0-vnext.145 => 0.60.0-vnext.143
    rnpm-plugin-windows: 0.3.5 => 0.3.5
  Installed UWP SDKs:
    10.0.10240.0
    10.0.10586.0
    10.0.14295.0
    10.0.14316.0
    10.0.14393.0
    10.0.14986.0
    10.0.15063.0
    10.0.16232.0
    10.0.16241.0
    10.0.16257.0
    10.0.16299.0
    10.0.17133.0
    10.0.17134.0
    10.0.17682.0
    10.0.17692.0
    10.0.17744.0
    10.0.17763.0
    10.0.18362.0

Then, specify:

- Target Platform Version(s): 10.0.18362.0

- Target Device(s): Desktop

- Visual Studio Version: Visual Studio 2017

 
- Build Configuration: Debug, Release

### Steps to Reproduce

(Write your steps here:)

1. Create an app that has a header bar that overlays some scrollable page content.
2. In the header, add a tab button that will navigate to some page
3. In the page content, add a button that can slide under the same area as the tab button in the header
4. Slide the page content up under the header so the page content's button is directly underneath header's tab button
5. Hover the mouse over a point that contains both the header's tab button and the page content's button

### Expected Behavior
Only the header button will change to its hover state; the button in the page content should not show up as hovered

(Write what you thought would happen.)

### Actual Behavior
Both the header button AND the page content's button display a hover state.  This ONLY happens when the mouse is over a hoverable item at the very top level; it does not make the lower item hover when there is no upper hoverable item.  Clicking the tab item seems to still work correctly (the top-most tab button only gets invoked, not the underlying button on the page content).

For example, here is an app with a header with "STORE" and "SOCIAL" tabs, which are clickable items.  Under the header, a large button has scrolled underneath.  When the mouse is on the header (but NOT on the clickable/hoverable tab buttons) and over the big button, the big button correctly does not show a hover state:
![image](https://user-images.githubusercontent.com/35792868/76255083-ce62d500-620a-11ea-95a6-b001f5418020.png)

However, when the mouse moves on top of the STORE tab, not only does the STORE tab show hover state (gets bolder), but the big button underneath also starts incorrectly showing a hover state (white border):
![image](https://user-images.githubusercontent.com/35792868/76255445-695baf00-620b-11ea-89a0-0cf0d0c4ffb7.png)

(Write what happened. Add screenshots!)

### Reproducible Demo
I'll try getting something up for this-

(Paste the link to an example project and exact instructions to reproduce the issue.)

### Additional context

(Write any other additional context that may help in root causing the issue.)

**Comment by Murtaya** [comment]
I've been trying to create a repro project.  https://snack.expo.io/ didn't repro, so I'm trying to create a standalone project, but I'm continually getting errors when starting from scratch.

![image](https://user-images.githubusercontent.com/35792868/76657568-67f1f580-652f-11ea-8b3c-8cef1799e1aa.png)

As far as code, we're transferring our code from an Electron-based app to RNW.  We're using Button controls that listen for hover start/end events and update the button's state.  It appears both buttons (the top and bottom) are getting these onHoverStart and onHoverEnd events.

The top-level button is on a panel that uses absolute positioning to show on top of the lower-level button.

I'll keep trying to get a sample app working.

**Comment by chrisglein** [comment]
There aren't any onHoverStart and onHoverEnd events. Can you share a snippet of the code where you're hooking these events?

**Comment by Murtaya** [comment]
I talked with people on our team, and it looks like we can give some people from the RNW permissions to view our source code.  Please advise/forward me to people on the RNW team who would like to investigate further.

**Comment by aschultz** [comment]
@chrisglein We're using the onMouseEnter/onMouseLeave callbacks on View to track hover state. The "onHoverStart/onHoverEnd" events Mike alluded to are fired by a custom Button component in response to those callbacks.

I believe the problem is related to UpdatePointersInViews in TouchEventHandler.cpp. It retrieves a list of elements under the cursor via the GetTagsAtPoint method and blindly fires mouseEnter/mouseLeave events irrespective of the element hierarchy. The result is that there is no sense of layering -- when the mouse moves over a point, the mouse is considering "inside" every element under that point.

That's a different behavior than web, where the hierarchy matters and the mouse is only ever "within" a single subtree at a time. Consider a tree like so:
```
<div id="outer">
  <div id="inner" />
</div>

<div id="overlay" />
```
where `overlay` is absolutely positioned partially on top of `outer` such that you can move the mouse directly from `outer` onto `overlay`. 

When the mouse moves over `outer` and then `inner`, the event sequence is:
1. MouseEnter outer
1. MouseEnter inner

But when the mouse moves over `outer` and then `overlay`, the event sequence is:
1. MouseEnter outer
1. MouseLeave outer
1. MouseEnter overlay

I put together a [JS fiddle ](https://jsfiddle.net/fwey0txq/)to demonstrate. You'll need to open the F12 debugger to see the console messages.

My POV is that RNW should match web's behavior here. It's arguably more useful behavior for app developers and would avoid a weird incompatibility when sharing code via something like react-native-web.

(As an aside, I think the "mouse over empty header doesn't trigger hover underneath" is likely due to the header background being set as the app's title bar region and thus sucking up any input events. I don't think its related to the underlying issue here).

**Comment by chrisglein** [comment]
> My POV is that RNW should match web's behavior here. It's arguably more useful behavior for app developers and would avoid a weird incompatibility when sharing code via something like react-native-web.

We completely agree on this. React Native follows the beat of the React drum, which follows the beat of web. While React Native for Windows is implemented in XAML, we want to present an experience consistent with web.

Mouse support isn't part of React Native core. We intend to flesh that out for RNW, but it's not there yet (#2099 is still in the design phase). However it appears that there is some basic mouse hooks available on View (not via ViewWindows) which frankly shouldn't be there until that design is completed, signed off, and implemented.

What's your timeline and when do you need this to be right?

Also, thank you for raising this issue :)

**Comment by harinikmsft** [comment]
Looks like @aschultz may be unblocking near term. Re-adding triage so we can take a look at whether anything is needed in 0.62 milestone from @kikisaints
