### ISSUE TITLE
[Request] Be more mindful of breaking API now that there is OSS dependencies

### ISSUE THREAD

**Issue by namrog84** [microsoft/react-native-windows#4279]
Recently grabbed latest version of RNW beta.  

I know its beta branch and prone to change but we had taken a dependency on ReactNativeVideoCPP and now it fails because ".Int64()" needs to be updated to .AsInt64()

If possible, try and make these common api breaking changes at bigger updates (like 61 to 62) or just change the underlying behavior under the same name with slightly different behavior. 

Hopefully these don't come up too often.  

Since we have a need to take a recent version of RNW, either we have to wait until ReactNativeVideo updates(I'll go do the PR) or we inject some ugly workarounds (which we will do in this case).

**Comment by NickGerleman** [comment]
There's been a lot of discussion around this topic recently.

We're going to be changing the versioning scheme of our releases soon to try to align breaking changes to React Native versions. 0.62-beta might still end up having a few, but by 0.63 we hope to really enforce this.

**Comment by namrog84** [comment]
Thanks. I had closed the issue because my original issue was from deprecation warning + warnings as errors combo. I was just feeling frustrated when I had opened it, but as the moment passed I came back and closed it.  

I am glad to hear about about this and I probably am a bit overly eager on updating versions since I am trying to be a good early adopter and find bugs early since we care a lot about RNW being successful long term.

**Comment by NickGerleman** [comment]
This experience is definitely good feedback for us though. FYI @vmoroz

The goal over the next few months is to move our development branch to align with Facebook master. In recognition that it's not reasonable to expect teams to use unreleased versions of React Native, the current thinking it to be somewhat liberal in back-porting non-breaking or purely additive changes so that we can continue to provide a stream of improvements. Things like depreciating or removing APIs would only happen with new RN versions every few months though.
