### ISSUE TITLE
Microsoft.ReactNative needs equivalent to ReactUWP FindShadowNodeForTag

### ISSUE THREAD

**Issue by aschultz** [microsoft/react-native-windows#4327]
## Summary
Add a function, possibly to IReactContext, that allows Native Modules to pass in a node id (the value returned by findNodeHandle() in JS) and get access to the corresponding XAML view.

## Motivation
Native modules need the ability to find and act upon arbitrary XAML elements. This allows use of native modules to augment existing UI elements.

For example, XAML's UIElement provides the "StartBringIntoView" function that will trigger any containing scroll region to scroll until the element is visible. Rather than updating all existing ViewManagers to include this function, a native module could be written to enable the behavior.

```
REACT_MODULE(ScrollHelperModule);
class ScrollHelperModule {

    REACT_METHOD(startBringIntoView);
    void startBringIntoView(int nodeHandle) noexcept {
        m_reactInstance->FindViewByHandle(nodeHandle).as<winrt::UIElement>().StartBringIntoView();
    }
}
```
```
const ScrollHelper = NativeModules.ScrollHelperModule;

export function startBringIntoView(target: Component) {
    return ScrollHelper.startBringIntoView(findNodeHandle(target));
}

```

**Comment by chrisglein** [comment]
@vmoroz Do you have a plan here that doesn't involve exposing the shadow nodes directly?
For this particular problem of scrolling into view it doesn't seem clear they need the shadow node, but they want the XAML UIElement. What's the right API for that? What's the parallel in other platforms.

Seems like some design work and discussion is needed here.

**Comment by KAnder425** [comment]
We also need this functionality in our app.  

We are using FindShadowNodeForTag in our native modules in two scenarios.

1. We set one of our View elements to be a custom title bar using the Window.SetTitleBar method. This requires access to the XAML UIElement for that RN View.
2. As a workaround for the issue in [#4080 ](https://github.com/microsoft/react-native-windows/issues/4080), we need access to the underlying XAML TextBox for some of our RN TextInput elements. We use that TextBox to set the width/height of the internal 'DeleteButton' to zero.

We need to find an alternative in order to move from React.UWP to Microsoft.ReactNative.
