### ISSUE TITLE
Native Modules need `#define NOMINMAX` in their pch now?

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4357]
I'm seeing this in the pch of our sample native modules:

`#define NOMINMAX`

Apparently without it, the Microsoft.ReactNative.Cxx shared code can't build.

Do we really need to make sure all native projects have this? Without a "create native module " template, everyone needs to add this manually. Can we force this to be defined/included automatically, preferably in a place where developers don't have to see it?

**Comment by chrisglein** [comment]
What headers that we control can we potentially add this in today? Or part of codegen? Seems like we definitely want to solve this and not push that to the module author.

**Comment by vmoroz** [comment]
The issue with the Microsoft.ReactNative.Cxx compilation concerning min/max was fixed by https://github.com/microsoft/react-native-windows/commit/36be9f4c9fd99cb9894a4e60ce545db821910c88
Though, it would be a good practice to provide a set of flags for Windows.h inclusion that reduces amount of code/macros it brings.
We can add these definitions inside of our project files or better yet the props file used by projects.

**Comment by NickGerleman** [comment]
Sounds like this was resolved? Going to close this issue. Feel free to reopen if not resolved.
