### ISSUE TITLE
'Question: C# Native Module'

### ISSUE THREAD

**Issue by erksch** [microsoft/react-native-windows#4412]
Hey guys, first of all thank you for the great work!

Although I am experienced with React Native I am very new to windows development and have a question about Native Modules. When I create a blank project the windows related code is in C++. So the ReactPackageProvider is in C++. Is it still possible for me to write Native Modules in C# or do I have to use C++? I would like to write a Native Module around a NuGet Package. Or are NuGet packages also usable in C++?

Many thanks!

**Comment by vmoroz** [comment]
We do have a sample of a C# based app and module: 
https://github.com/microsoft/react-native-windows/tree/master/packages/microsoft-reactnative-sampleapps

We also use Nuget packages in our C++ projects. It can be done using the same package manager as with C# based projects.

There should be a way to generate C# based project by passing 'language' parameter with value 'cs'.

Though, please be aware that we currently have a couple of issues with C# code that we work on to resolve ASAP:
- It currently uses .netcore 1.0.
- There are issues with .Net Native that cause a crash.

**Comment by chrisglein** [comment]
I believe the question here was around making a C# native module, not whether the app was C++. We've got an option to `--language cs` to set the app's project after `init`, so that's covered.

As for whether you can create a C# native module hopefully that's clear now with this sample. Let us know if you have any other questions.
