### ISSUE TITLE
Border radius is not getting updated correctly in RTL

### ISSUE THREAD

**Issue by JakovS** [microsoft/react-native-windows#4499]
### Environment

If you are using latest version:
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.60.6
2. `react-native run-windows --info`:
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    Memory: 19.41 GB / 31.91 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.6 => 0.60.6
    react-native-windows: 0.60.0-vnext.155 => 0.60.0-vnext.155
  Installed UWP SDKs:
    10.0.16299.0
    10.0.17134.0
    10.0.17749.0
    10.0.17763.0
    10.0.18362.0

Then, specify:

- Target Platform Version(s):
10.0.18362.0

- Target Device(s):
Desktop

- Visual Studio Version:
Visual Studio 2017

- Build Configuration:
Debug
### Steps to Reproduce

(Write your steps here:)

1. Create a View and give it a border radius style using one of the: borderTopStartRadius, borderBottomStartRadius, borderTopEndRadius, borderBottomEndRadius
2. Some time after the View has been mounted, provide a new style with updated values for the above.
3. Observe in LTR this works as expected.
4. Switch to RTL, relaunch the app
5. Notice that on mount the border radius is applied as expected (start on he right, end on the left)
6. After the style is updated, the radius gets applied as if it was LTR (start on the left, end on the right)
### Expected Behavior

I would expect the style to behave the same way that it did on mount.

### Actual Behavior

After the style is updated, the radius gets applied as if it was LTR (start on the left, end on the right)

LTR behaves as  expected:
![LTRradius](https://user-images.githubusercontent.com/3286780/78517371-d4989280-7771-11ea-9fca-85772672f18a.gif)
RTL after update style gets applied incorrectly (switches sides), on remounting it does applies correctly:
![RTLradius](https://user-images.githubusercontent.com/3286780/78517375-d6faec80-7771-11ea-94dd-9afe41fe1430.gif)

### Reproducible Demo

[https://snack.expo.io/SLis5ZWht](https://snack.expo.io/SLis5ZWht)
Put this component in an application somewhere, and launch with an RTL language.

**Comment by kmelmon** [comment]
I can grab this one, should be an easy fix.

**Comment by kmelmon** [comment]
Bug understood.  This code is swapping the corner "left" and "right" radius properties before pushing them into XAML:
https://github.com/microsoft/react-native-windows/blob/21dea64efa55d0cc23d0ad0e33a058b0e3981800/vnext/include/ReactUWP/Utils/PropertyUtils.h#L71

There are multiple problems with this:
1) XAML already swaps "left" and "right" when FlowDirection == RightToLeft, which it is when direction == 'rtl'.  This code is incorrectly swapping back.
2) The incorrect swapping doesn't correctly detect FlowDirection == RightToLeft in all scenarios.  It assumes that FlowDirection has already been pushed into the XAML tree, which isn't guaranteed at the time we're calling this function.

Problem 2 explains why we only see the bug sometimes.

The fix for most basic scenario is straightforward - we don't need to do this swapping.  That is what I will do to resolve this.

Note that there is another scenario we'll eventually need to handle.  If the app calls a special method, I18nManager.swapLeftAndRightInRTL(false), this is supposed to swap left and right back, like what this code is trying to do.  We don't yet implement this API, filed https://github.com/microsoft/react-native-windows/issues/4662 to track.
