### ISSUE TITLE
Flipper Does Not Show Component Tree When Connected to React Native Windows

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#4711]
![image](https://user-images.githubusercontent.com/835219/80269200-4d4c8980-8662-11ea-9bbc-2386bb882765.png)

We're able to reload and view logs, but we don't support much Flipper functionality.

**Comment by chrisglein** [comment]
@NickGerleman did you connect this on boot? There was a change in behavior there. @acoates-ms made that to match other platforms (checks when dev menu is loaded and once on boot). Check with him. Also, write out your steps for how you got this far, because at least it's a start? We definitely want to get Flipper up and running on RNW.

**Comment by chrisglein** [comment]
A little bird is telling me that DevTools 4 is not supported with 0.62. Does this work with DevTools 3?

**Comment by NickGerleman** [comment]
This was Flipper 0.39.0. Flipper and Metro were open before starting Playground.

**Comment by NickGerleman** [comment]
So, I tried this again, and it seems to be working now with the default V4! This is possibly related to the  older React Depdendency. Things worked correctly when starting metro, starting playground, then loading a bundle with web debugging + fast refresh enabled.

![image](https://user-images.githubusercontent.com/835219/80683682-72cdfe80-8a79-11ea-8d55-185cad20c00d.png)
