### ISSUE TITLE
New 0.62 C# template app crashes at start

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#4749]
Repo:

```cmd
npx react-native init testapp62cs --version ^0.62.2
cd testapp62cs
npx react-native-windows-init --language cs --overwrite
npx react-native run-windows
```
Error: `Failed to deploy: Starting the app`

Running with `npx react-native run-windows --logging` gives:

```
 Start-Locally : Faulting application name: testapp62cs.exe, version: 1.0.0.0, time stamp: 0x5ea9b833
Faulting module name: KERNELBASE.dll, version: 10.0.19619.1000, time stamp: 0x1265fc9b
Exception code: 0xe0434352
Fault offset: 0x0012ab62
Faulting process id: 0x71e0
Faulting application start time: 0x01d61e4bc1f57292
Faulting application path: C:\code\testapp62cs\windows\testapp62cs\bin\x86\Debug\testapp62cs.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e80a2034-88e7-400e-bdd7-6e1a86f87b31
Faulting package full name: da4e9170-1da6-41aa-a9fb-a3e9cde17ea9_1.0.0.0_x86__ha4szp75kcxjr
Faulting package-relative application ID: App
At line:1 char:124
+ ... Utils.ps1"; Start-Locally da4e9170-1da6-41aa-a9fb-a3e9cde17ea9 --remo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Start-Locally
```

**Comment by jonthysell** [comment]
It doesn't repo if I build in VS, only by using the run-windows command.

**Comment by jonthysell** [comment]
Ok, I've confirmed that if I build/deploy the app in VS, then use the cli's code to start the app (using our powershell util `Start-Local`) the app launches fine. So somehow, either the app is being built or deployed wrong. Possibly related to #4705

**Comment by jonthysell** [comment]
Does not repro on 61.

**Comment by asklar** [comment]
Thanks for filing @jonthysell . I have confirmed the issue as well as with a simple hello world UWP app (non-RNW). This is due to the fact that registering from layout seems to have special logic in VS that isn't immediately apparent how to replicate it in MSBuild. We are following the docs on [layout registration](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/loose-file-registration) but it seems like there are issues with .net core apps. 
I have filed:

* [Registering layout with built appxmanifest.xml crashes app](https://github.com/MicrosoftDocs/windows-uwp/issues/2413)
* [How to create layout for C# app from MSBuild](https://github.com/MicrosoftDocs/windows-uwp/issues/2412)

For the time being I might disable layout registration for C# apps.

**Comment by chrisglein** [comment]
This issue (the crash) is addressed. @asklar can you open a tracking issue for us to clean this up when the core UWP changes are made?

**Comment by bberak** [comment]
Hey all,

Sorry I didn't quite follow conversation above. It seems like a fix for this issue has been merged into master, but not yet released with `react-native-windows`?

Thanks in advance for all your efforts, this is a great initiative by msft.

**Comment by asklar** [comment]
Hi @bberak - the latest on deploy-from-layout can be found in master. Last week I fixed some issues related to it failing on fresh machines (i.e. machines where no XAML apps had been installed before) so if you want the latest and greatest, that's where it's at :)

**Comment by bberak** [comment]
Thanks @asklar 

I've also found that deleting the `bin` and `obj` folders before running the `react-native run-windows` commands does the trick (not sure if it will work for others though).
