### ISSUE TITLE
Native modules access XamlView which is tied to XAML dialect

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#4926]
Native modules today interact with the `XamlView` type which is a typedef for `Windows.UI.Xaml.UIElement`. However, that means that they wouldn't work with a WinUI 3 build of RNW. 
We need to either:
* Update all native modules to WinUI3, or
* Make XamlView a type that is able to reason about WUX vs MUX

**Comment by chrisglein** [comment]
Should not allow mixing of WinUI2/inbox and WinUI3 in the same process.
Also need to figure out how community modules are supposed to navigate this, as the support window for WinUI3 is likely to be long.

**Comment by chrisglein** [comment]
@stmoy and @asklar can you work with the WinUI3 folks to figure out how they think someone should author a controls library in the brave new world of WinUI3? Also, how we want to inform the community module of best practices here (once we figure out what they are...).

**Comment by vmoroz** [comment]
Native modules ideally must not touch the XAML. We must remove the IReactContext dependency on XAML. Then we can focus on UI components and views. I.e. the issue is better to be focused on UI views, not the native modules. If we cannot combine these twoUI technologies, then we could produce two different DLLs.

**Comment by asklar** [comment]
current plan is to dual-compile modules and produce 2 DLLs, one for xaml and one for winui3
