### ISSUE TITLE
Start using the Windows SDK 10.0.19041.0

### ISSUE THREAD

**Issue by vmoroz** [microsoft/react-native-windows#4960]
The new Visual Studio 16.6.0 allows installation of the Windows SDK 10.0.19041.0.
We should start using it for our projects.
I do not know about all improvements there, but we can start to benefit from the new [noexcept] attribute in the MIDL 3.0 that will generate more compact WinRT code.

**Comment by JunielKatarn** [comment]
Shouldn't we do this until `19041` becomes the default SDK, to avoid multiple WinSDK installation?
What's the benefit of early adoption?

**Comment by asklar** [comment]
I think we want to hold off on this and actually maybe go the other direction. We shouldn't be using 18362 either, if we want to use WinUI3 we should be targeting 17633 if anything

**Comment by chrisglein** [comment]
End developers would then need to have this SDK installed. What version do they get by default? Does VS nag them to update or do we need to push manual steps on them as part of our developer environment setup?

But also there would be impact on the CI machines needing to install this (or needing to get a different VM that has a standard config) otherwise it's going to impact CI time.

I assume at some point we'll want to move forward, but there's cost to doing it too early.

What's the biggest payoff we'd get from this now? So far you called out this:
> I do not know about all improvements there, but we can start to benefit from the new [noexcept] attribute in the MIDL 3.0 that will generate more compact WinRT code.

Anything else?

**Comment by JunielKatarn** [comment]
> End developers would then need to have this SDK installed. What version do they get by default? Does VS nag them to update or do we need to push manual steps on them as part of our developer environment setup?

As of VS 16.6, they get `10.0.18362.0`.
If we are aligning the whole RNW to Azure Pipelines' release schedule, why not do the same with the Windows SDK?

**Comment by vmoroz** [comment]
I do not know about any other benefits. We can wait. There is no urgency.
