### ISSUE TITLE
Support rn-fetch-blob

### ISSUE THREAD

**Issue by stmoy** [microsoft/react-native-windows#5158]
# Support `rn-fetch-blob` on RNW

## Basic Info
- Module Repo URL: https://github.com/joltup/rn-fetch-blob

## Which app/customer is requesting this module?

Community request

## In what scenarios will this module be used?

A project committed to making file access and data transfer easier and more efficient for React Native developers.

## Essential Features

- Transfer data directly from/to storage without BASE64 bridging
- File API supports regular files, Asset files, and CameraRoll files
- Native-to-native file manipulation API, reduce JS bridging performance loss
- File stream support for dealing with large file
- Blob, File, XMLHttpRequest polyfills that make browser-based library available in RN (experimental)
- JSON stream supported base on Oboe.js @jimhigson

**Comment by thedf** [comment]
Hey there,

I want to know if the library is yet supported by RNW, because in the [Community modules](https://microsoft.github.io/react-native-windows/docs/supported-community-modules#community-modules) section in the docs it says that this library is already supported but I couldn't find the implementation. 

Thanks in advance.

**Comment by chrisglein** [comment]
Closing this module request as not in plan. Not that this module _shouldn't_ receive a Windows implementation, but it makes more sense to track that request on the module's repo rather this repo.
