### ISSUE TITLE
Split out e2etest build from running the tests 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5198]
Since we aren't able to get reliable e2etest runs and building takes a while, I wanted to propose that we split the e2etest build from running the test, which would allow us to re-run just the test part without having to wait for a new build that just rebuilds the same thing.

**Comment by chrisglein** [comment]
Feedback from Andrew, would make the happy path slower, since you have to build and then publish artifacts, then test. How much?
How does this interact with plans to use Helix for builds + tests?
How much time is it taking to the multiple build+retries right now? As in how much are we paying for the flakiness right now versus how would we be affecting our min run ("happy path").

**Comment by asklar** [comment]
@chrisglein every rebuild is about 20min and the test is pretty noisy/unreliable. I believe @JunielKatarn was working on fixing them up or disable them, I'm not sure what the latest on it is.

**Comment by chrisglein** [comment]
If we're moving stuff around for Helix, this may not just be useful because of the flakiness of the tests to justify this work. Built app delivered separately from the tests.

**Comment by NickGerleman** [comment]
This has gotten to be pretty reliable. Marking for feedback, to see whether this issue is still something we want to pursue.
