### ISSUE TITLE
Switch gets incorrectly disabled in very basic scenario with 2 Switches

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5204]
If I put 2 Switches into a barebones app and hook them both up with basic on/off behavior, interacting with one of the switches causes the other switch to become disabled. 

See this snack:
https://snack.expo.io/g5a5hvCnK

When I run this on Android/iOS it behaves as expected:  You can interact with either switch and both switches stay enabled.  For example if I flip the first switch on, it looks like this:

![Capture_Android](https://user-images.githubusercontent.com/33470154/84585605-69e58200-adc6-11ea-962f-c33300981af6.PNG)

On Windows, if I do the same thing, the second switch becomes disabled:

![Capture_Windows](https://user-images.githubusercontent.com/33470154/84585616-81bd0600-adc6-11ea-8e21-e68f949768c0.PNG)

That ain't right.

**Comment by NickGerleman** [comment]
I think this is my bug. Looks like I accidentally set the new ViewManager command for Switch in 0.62 to set the "IsEnabled" prop on the switch instead of "IsOn"

```jsx
void SwitchViewManager::DispatchCommand(
    const XamlView &viewToUpdate,
    const std::string &commandId,
    const folly::dynamic &commandArgs) {
  if (commandId == "setValue") {
    auto value = commandArgs[0].asBool();
    viewToUpdate.as<winrt::ToggleSwitch>().IsEnabled(value);
  } else {
    Super::DispatchCommand(viewToUpdate, commandId, commandArgs);
  }
}
```

In the RNTester switch examples, it looks like any of the examples explicitly setting state on the switch don't run into this for some reason. Likely implementation details of where React Native JS uses the ViewManager command vs not. The bottom example where no handlers or state is set does seem to run into the issue. IIRC this was broken in 0.61 in a slightly different way where we see the switch seems to flash on and off if clicked.

**Comment by NickGerleman** [comment]
Impact is that switches acting as uncontrolled components are broken in 0.62+, though I think they also might have been broken before. This seems like a backport candidate for 0.62.

**Comment by NickGerleman** [comment]
Actually, looking at Keith's example, we're explicitly setting state there as well, so I'm not sure the factors of why we don't see this issue in RNTester apart from one of the examples. 

Testing with Snack for a switch without value set, it looks like iOS and to a lesser Extent Android have the same behavior when uncontrolled of flickering back to the original state. The example that shows this is named "Switches are controlled components", which seems to imply that there's expectations that Switch eventually remain disabled if properties aren't set, unlike a form.

I.e. the 0.61 behavior was correct here.
