### ISSUE TITLE
Question: Is it possible to import a .dll file into our react-native-windows project?

### ISSUE THREAD

**Issue by AndreBastos23** [microsoft/react-native-windows#5280]
Hello,

I'm currently trying to add a .ddl file into our react-native-windows, but i'm getting the following error:

![image](https://user-images.githubusercontent.com/9679053/85069833-ac370680-b1ac-11ea-9ab4-dd074064de56.png)

As you can see in the picture below, i've imported the dll into the project root, and added a reference to the main ddl (their documentation only talks about referencing that specific dll).
![image](https://user-images.githubusercontent.com/9679053/85069942-dee0ff00-b1ac-11ea-98f1-b995f01450f0.png)

Am i missing something? Or is it not possible to import dll files into a react-native-windows project?

In like 10% of the builds i do, i can acess the methods from that specific dll's, but if i rebuild, that previous error starts happening.

Any idea of what i'm doing wrong?

**Comment by asklar** [comment]
@AndreBastos23 React Native for Windows apps are UWP apps, so you should be able to consume any DLLs/components that are available for UWP apps. There's usually no guarantee about Win32 DLLs since these sometimes call into APIs that are not available in UWP.
The first error you are getting seems to indicate a problem with .NET. Are you maybe running a preview of .NET Core 5? That's not currently something we support. Please provide your setup information so we may better assist you.
