### ISSUE TITLE
Manual verification checklist before release

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5326]
Before we publish a new release, we should manually verify things are working.  This is particularly needed at this point in time as we don't have much test automation yet.

This task is tracking creating a checklist of manual verification steps.  Should include things like:
-Validating pages in RNTester are working as expected
-Running the CLI is working with latest tools
-Can create an app and publish to the store

**Comment by TheSavior** [comment]
I believe we have a manual testing flow defined before doing releases on mobile. I imagine you’d at least want to do those same steps.

@alloy can probably link you to the right part in the releases repo if you can’t find it

**Comment by alloy** [comment]
Aye, it’s pretty much what @kmelmon lists: https://github.com/react-native-community/releases/blob/master/docs/publish-release.md

(There’s some more docs too https://github.com/react-native-community/releases/tree/master/docs)

**Comment by NickGerleman** [comment]
The init bugs we just saw with new versions of Yarn (or Yarn registry changes?) is a good example here where end-to-end CI gave us a false sense of security. Cases where we don't validate in CI, or it's hard to validate in CI seem good for the matrix, since this was a showstopper for Yarn users with resolution logic that wouldn't happen on CI, even if we were testing e2e init with Yarn instead of just npm.

Re the store, I'm still hopeful we can get WACK running in CI. At the very least, Office has some internal tools that will actually cause a build break if a DLL has symbols not on an API whitelist. Maybe we could consider that as a WACK-lite?

**Comment by kmelmon** [comment]
@chrisglein you were already creating a set of release steps.  Can you incorporate those into an official page so folks on the crew have a place to go when we're cutting a release?  Also note the link above from eloy.

**Comment by asklar** [comment]
@kmelmon @chrisglein we should make sure that we are testing the community modules that we added against the new version of RNW and update them if need be. See Community module support principles #5031

**Comment by NickGerleman** [comment]
Marking this for triage again since we've been needing to use an interim process for the past couple of releases. Not sure the state of this item.

**Comment by chrisglein** [comment]
This is something we have adhoc'd release to release, but not something we've formalized into a script. We are starting to leverage the [gallery](https://github.com/microsoft/react-native-gallery) app as the vehicle for this. What we need is a script of _how_ we use the gallery app to validate. I've opened [this issue](https://github.com/microsoft/react-native-gallery/issues/48) to track that. We also intend to publish that app to the store ([issue](https://github.com/microsoft/react-native-gallery/issues/11)), which can be used to validate store publish.

That at least covers some of this, not all of it. Having an RNTester script is also important as Gallery doesn't cover everything.

So something like this:
- Run RNTester script (to be built)
- Run Gallery script ([TBD](https://github.com/microsoft/react-native-gallery/issues/48))
- Create a fresh new app with steps in [current](https://microsoft.github.io/react-native-windows/versions) docs
- Publish app to the store (probably Gallery, not the new app)

Next action on this issue:
- Create that RNTester script
- Put the results on [this wiki page](https://github.com/microsoft/react-native-windows/wiki/Manual-Validation-Script)

**Comment by chiaramooney** [comment]
@chrisglein Oh my understanding of the TBD was that we don't currently have a RNTester script but the bullet is there because we have the intent of adding it in the future based on your comment here:

"That at least covers some of this, not all of it. Having an RNTester script is also important as Gallery doesn't cover everything.

So something like this:

**Run RNTester script (to be built)**
Run Gallery script (TBD)
Create a fresh new app with steps in current docs
Publish app to the store (probably Gallery, not the new app)
Next action on this issue:

Create that RNTester script
Put the results on this wiki page"

Do we now have a script?/Are there existing instructions for it?

The instructions for publishing gallery to the store are currently in the One Note because it's an internal/first-party process. Should I add a link to the OneNote on github?

**Comment by chrisglein** [comment]
> Run RNTester script (to be built)

Can we link to tracking issues # then? These seem relevant:
- #6227
- #4037

> The instructions for publishing gallery to the store are currently in the One Note because it's an internal/first-party process. Should I add a link to the OneNote on github?

Yep, include a link and have the display text as "internal link". It's okay to have those.

**Comment by chiaramooney** [comment]
All todo's completed.
