### ISSUE TITLE
'Question: [Is support for WPF dropped entirely?]'

### ISSUE THREAD

**Issue by Unforgiven-wanda** [microsoft/react-native-windows#5389]
Hello,
I remember checking this project some months back, the project description said you could generate both a Windows Store application for Windows 10 or a WPF application for older versions of Windows.
But now the docs are more than hazy on this point and I couldn't find a definitive answer in older issues, so please allow me to ask now:

- Does this project support older versions of Windows for the released app? Specifically Windows 7 and 8?
- And if yes, how? Is WPF support still on the roadmap?

In a word **does this only support Windows 10**?
Thank you.

**Comment by asklar** [comment]
@Unforgiven-wanda thanks for your question. The current version of RNW supports Windows 10 version 16299 and higher only, see https://microsoft.github.io/react-native-windows/docs/rnw-dependencies for full details.

In the future you'll be able to target other OS releases via WinUI 3. WPF is not in the roadmap.

**Comment by Unforgiven-wanda** [comment]
Thank you for the clarification. Is there a roadmap for when said support might become available?

**Comment by chrisglein** [comment]
Point of clarification: you can host RNW content inside a WPF app using XAML Islands. There's some samples for how to do that. But if you're looking to generate WPF content instead of UWP XAML yes that's now retired. As for WinUI3 there is some info about how to do that today (on preview 1) in the docs.
@harinikmsft I think you have an issue to add that sample link to the documentation, can you provide the link here?
