### ISSUE TITLE
Restore support for offline builds in run-windows

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#5404]
We should support offline builds. This was made possible by checking whether nuget was already installed and using that. Can you restore that functionality?

_Originally posted by @asklar in https://github.com/microsoft/react-native-windows/pull/5330_

**Comment by NickGerleman** [comment]
FWIW the previous NuGet binary logic was broken, and CI never tested it. When Pipelines did add a NuGet binary to its path, both us and partners saw CI failures because `run-windows` would crash.

Some more notes though:
1. We always run a NuGet restore during `run-windows`. Would this work if offline?
2. The Folly native project will download Folly sources as part of the build if not present

I think using the built-in NuGet binary in Visual Studio is a good option going forward. There are other bugs like a random console.log of the NuGet path in the CLI that interrupts the spinner that we should probably fix here as well.

**Comment by NickGerleman** [comment]
Looking at this more, it looks like VS doesn't include any local NuGet.exe (this is confirmed by https://www.nuget.org/downloads).

It seems to instead have a relatively private DLL that it uses that we probably shouldn't ourselves. An alternative solution would be to package NuGet ourselves and include as part of the JS payload.

**Comment by NickGerleman** [comment]
The linked PR cleans up NuGet logic, but doesn't fix the other issues mentioned.
