### ISSUE TITLE
Add `.focus()`, `.blur()`, `onFocus()`, `onBlur()` to Pressable

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-windows#5589]
From [Keyboarding in React Native Desktop](https://github.com/microsoft/react-native-windows/pull/5590/files) document:

> Add `.focus()`, `.blur()`, `onFocus()`, `onBlur()` and `isFocused()` to Pressable. These are currently supported in View, TextInput.

**Comment by TheSavior** [comment]
If these are added to View they should automatically become available on Pressable because Pressable uses forwardRef to `<View>`: https://github.com/facebook/react-native/blob/master/Libraries/Components/Pressable/Pressable.js#L158-L159

**Comment by chrisglein** [comment]
Rest should work, believe that `onFocus()` and `onBlur()` won't.

**Comment by rectified95** [comment]
@harinikmsft
> Add .focus(), .blur(), onFocus(), onBlur() and isFocused() to Pressable. These are currently supported in View, TextInput. 

Looking at https://reactnative.dev/docs/view, I don't see these functions exposed in View. Should we track that work separately? It looks a chunky bit.

**Comment by TheSavior** [comment]
`.focus()` and `.blur()` are methods on any native component, although the implementation just calls into TextInputState: 

https://github.com/facebook/react/blob/ded2a83ebfb7d0d755b0527bb221fa1a2b19b3b8/packages/react-native-renderer/src/ReactFabricHostConfig.js#L122-L128

In React Native today, only TextInputs can be focused and blurred. For this to properly work, someone probably needs to figure out how to change that so that any view can be focused.

**Comment by rectified95** [comment]
Thanks for the reply. I have a few focus-related tasks assigned (#5511 #2107 +this one), so that might be me.

**Comment by TheSavior** [comment]
Awesome, looking forward to it! :D

**Comment by rectified95** [comment]
Merged the isFocused() bit with the same task to add it to View #5511
