### ISSUE TITLE
Support react-native-audio

### ISSUE THREAD

**Issue by bwaldbaum** [microsoft/react-native-windows#5601]
# Support `react-native-audio` on RNW

## Basic Info
- Module Repo URL: [https://github.com/jsierles/react-native-audio](https://github.com/jsierles/react-native-audio)
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())

- [ ] Module has a Legacy/C# implementation (if so, [link]())

## Which app/customer is requesting this module?

Outlook for Windows

## In what scenarios will this module be used?

We'd like to add a button which plays the audio of a contact pronouncing their name.  Currently, we'd need to call back to native C++ code to play the audio file.  It would be better if it could be done from within the RNW code.

## Essential Features

Just the "play" function.

**Comment by chrisglein** [comment]
@bwaldbaum Thanks for filing the request. Trying to look into what team you're coming from, would this before the Win32 platform or main UWP RNW? We're not targeting modules for the former, only the latter, so I want to make sure.

**Comment by chrisglein** [comment]
@bwaldbaum We don't have a public story for developing community modules on the Win32/NetUI platform. That has to be handled by Office/Outlook directly. Since this isn't really in scope of what this repo is about I'm going to close this issue, but feel free to ping me for context if this is confusing.
