### ISSUE TITLE
RN version 64:  Validate static positioning works

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#5623]
This commit was recently made in facebook master:
https://github.com/facebook/react-native/commit/ec60ebe
It should be part of version 64.

The change adds support for position:static.  It's a simple change we can apply manually.  We should make sure that this layout feature works in RNW.

Static positioning comes from the W3C standard.  Here's what w3cschools has to say about it (taken from https://www.w3schools.com/css/css_positioning.asp):

position: static;
HTML elements are positioned static by default.

Static positioned elements are not affected by the top, bottom, left, and right properties.

An element with position: static; is not positioned in any special way; it is always positioned according to the normal flow of the page:

**Comment by chrisglein** [comment]
May not be any work here, but will want to validate when we get this payload that RNW matches the core behavior.

**Comment by chiaramooney** [comment]
Looks like only one file will need to be changed. Point of change will be [here](https://github.com/microsoft/react-native-windows/blob/48f6f67fc14f3f7a7c33e8a1b3c62e8e64882bd8/vnext/Microsoft.ReactNative/Modules/NativeUIManager.cpp#L514-L523). I'm assuming I will need to wait until RN 0.64 is released to make my change because the 'static' type won't exist until then.

**Comment by acoates-ms** [comment]
master should already have all these changes.  We have sync'd a bunch of RN 64 into master already.
