### ISSUE TITLE
The rnw-dependencies.ps1 script does not reinstall the node version if it has version 14.x

### ISSUE THREAD

**Issue by javieraparisivaldes** [microsoft/react-native-windows#5704]
## Environment
Target Platform Version(s):Desktop
Target Device(s): Visual Studio 2019
Visual Studio Version: Debug
npx react-native --version: 4.11.0
npx react-native run-windows --info:
System:
OS: Windows 10 10.0.18362
CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Memory: 1.04 GB / 7.89 GB
Binaries:
Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.19.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
npmPackages:
react: 16.11.0 => 16.11.0
react-native: ^0.62.0-0 => 0.62.2
react-native-windows: ^0.62.0-0 => 0.62.4
Installed UWP SDKs:
10.0.17134.0
10.0.17763.0
10.0.18362.0
10.0.19041.0

reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock":
AllowDevelopmentWithoutDevLicense REG_DWORD 0x1
AllowAllTrustedApps REG_DWORD 0x1

## Steps To Reproduce
1.Run script on elevated power shell 'https://raw.githubusercontent.com/microsoft/react-native-windows/master/vnext/Scripts/rnw-dependencies.ps1'
2.The script detects that I don't have the version of node 12 or 13 and asks me if I want to install it
3.When i response 'yes' the window close, doesn't install a different version node.

## Expected Results
Install node version and dont close de power shell window

![scripterror2](https://user-images.githubusercontent.com/56872233/90023174-b4df2100-dcb3-11ea-97af-09b4d4c08ff7.png)
![scripterror1](https://user-images.githubusercontent.com/56872233/90023176-b577b780-dcb3-11ea-849e-8e709f10ee1c.png)

**Comment by samiq** [comment]
also don't know if it's worth mentioning but this script also doesn't actually check properly all the Windows requirements, it checked everything for me to then fail because of MSBuild not been present on when I type run, then it took me a lot of peekaboo playing with the Visual Studio installer to check what was the right combination of checks required to get it to compile, it would be great if there was an actual list of individual packages required to run this, rather than just blindly checking 20GB worth of stuff I don't need in my computer

**Comment by chrisglein** [comment]
Unknown if we are incompatible with Node 14 or not. But at the very least this sounds like a very confusing result.
Our documentation currently recommends <14 (specifically 12.9.1 at this moment). Latest LTS. 

We're installing via chocolatey and it's exiting because a newer version exists. The script shouldn't downgrade the user's system for a lower version. But there should be a node version switcher option here so we can target the known supported version.

Any overlap with `doctor` and whether it checks Node version? Looks like it checks Node > version 8. There should probably be a stronger claim there from React Native core. We haven't yet invested in expanding `doctor` to cover RNW.

Sounds like you're unblocked (it will continue to install other dependencies, and Node 14 may work fine). But we should take an action at the very least to make the script less confusing in its result here.
