### ISSUE TITLE
Allow Deep-linking for Non-Protocol Activation (And Launch the app)

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#5852]
A UWP app can be activated for multiple reasons: https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.activationkind?view=winrt-19041

Right now we only respond to ProtocolActivation, and will embed the link so that the "Linking" JS API can read the link as to why were were launched.

#5850 noted that we don't currently launch if asked to because a notification for an RNW app was clicked on. Normally toast arguments would be passed to the UWP activation callback, letting us read notification properties and launch the app. The change makes it so that we can launch the app, but notification information is launched which prevents deep linking from notifications.

We should try to figure out the right thing to do, and try to figure out if we can/should embed extra activation information in a way JS can read it.

**Comment by kmelmon** [comment]
Needs some careful thought as it's UWP specific.

**Comment by chiaramooney** [comment]
Not something we plan to address on the Paper renderer as we move towards Fabric. Fabric apps will now be Win32 by default instead of UWP.

**Comment by chiaramooney** [comment]
Apps on the new architecture will be Win32 by default instead of UWP. This will mean that the native side of your app will be swapped to a Win32 app, but your JavaScript code will remain intact. We will have clear migration instructions out once we get closer to moving the new Fabric architecture into production. 

The move away from UWP was a decision made to stay in alignment with the new WinAppSDK and WinUI 3 which support Win32 apps.

**Comment by JakobKrummeichAndrena** [comment]
Alright, thank you for the answer! I'm looking forward to the switch to Win32.
