### ISSUE TITLE
Office code is built from inside react-native-windows repo

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6018]
We keep running into this so I figured I'd file a bug.
Often we will fix something or add a feature to RNW, but then we end up having to spend 2x fixing "Desktop" code (i.e. code used in Office). In the latest example, I some time ingesting the new Folly library, but then had to fix a whole bunch of Desktop code (product and test code) because of tight coupling:
- Office uses linker names (see #6001).
- Office publishes nugets from the react-native-windows repo, which includes folly headers
- Prob more tight/improper coupling points

Filing this to have a discussion about what the future path forward is and how we decouple office and rnw as much as we can so that Office is unblocked, but RNW team isn't burdened with maintaining Office infrastructure.

**Comment by chrisglein** [comment]
We've heard before that it's hard to take this code out of core. But maybe we're willing to invest in that hard now? We should discuss this and figure out what we can do. @acoates-ms what are your thoughts? Should we have a Monday discussion on this? How can we help divvy up the work?

**Comment by NickGerleman** [comment]
Commenting on the more technical aspects of this, we have a whole lot of artifacts from not just Office specific bits (e.g. NetUI) but also the history of the repo. E.g. ReactUwp also had Folly as a boundary, but Vlad did the MSRN work to replace that with JSValueReader/JSValueWriter.

There is ongoing work to try to reconcile a lot of the code between platforms (e.g. common native modules, core DLL allowing common instance management, etc). This is of course challenging, since the codebase for RNWCPP came from the Office monorepo, and things are still entangled.

There are a few different places where I see divergence:
- Instance management stack
  - The MSRN Instance management stack on top of Facebook's is derived from what's in Office, but hasn't replaced it yet. We need to expose lower level APIs for instance management in the meantime.
- Native modules are pretty split
  - Some of these need to be, some of them probably shouldn't be
- View managers are totally split
  - That's going to be the case for quite a while. We need to support Win8, special composition scenarios, etc
- We have the .win32 JS platform
  - Will have to exist while we have separate NMs + ViewManagers

If there are any concrete pain-points, it would be useful to know. I don't expect any of these to be too expensive to engineers focused on XAML only. There will of course be some overlap though, where XAML focused engineers need to care about Office scenarios, just as Office engineers have frequently done work that has solely benefited the XAML/OSS ecosystem.
