### ISSUE TITLE
[Native modules] react_method doesn't validate input param types/count

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6066]
When creating a native module and implementing a native module's methods, the method parameters are not checked so e.g. if the JS side looks like:
```js
const text = themodule.getString().then( ... )
```

and the native side looks like
```cpp
void getString(bool foo, int bar, Promise<std::string>&& promise) { ... }
``` 
Nothing will actually check that the parameters being passed from javascript can be mapped correctly to the native params

**Comment by asklar** [comment]
@asklar vmoroz fyi

**Comment by acoates-ms** [comment]
This is what the module spec files are for.   This is true with RN core native modules too.  There is no type checking between the JS and native until TurboModules.

**Comment by chrisglein** [comment]
What happens when the parameters don't match? Sounds like it doesn't crash. If they're omitted are they default initialized? Mismatch feels like an actual bug, where omitted parameters is likely a feature.

The question here seems to be about runtime validation versus static validation - as in what can we do at runtime and what should we.

@vmoroz What are your thoughts here? Is there more we should be doing now at runtime? What sort of runtime validation to the other platforms do?

**Comment by vmoroz** [comment]
We cannot do much here: the NM design does not support any signature verification. It is the reason why in MS Office we have created Reka, and the future react-native direction is the TurboModules. While we cannot do much with NM verifications, we can proceed with TurboModules and/or open source Reka.
Our current TurboModule specs are compatible with NM implementation, and it can be used immediately. While it does not use JSI, it effectively adds type/signature safety for NM.
