### ISSUE TITLE
Wiki instructions for testing CLI are out of date

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6071]
The wiki was not updated when the CLI was moved to its own typescript package

https://github.com/microsoft/react-native-windows/wiki/Contributing-to-the-CLI#a-faster-way-to-test-the-react-native-windows-init-cli

![image](https://user-images.githubusercontent.com/22989529/94010729-2c947700-fd5b-11ea-8111-603923fc9040.png)

**Comment by NickGerleman** [comment]
The instructions in the wiki are correct. The error here means that react-native-windows-init is unable to find find the generator in either of the two locations it's looking for (react-native-windows/generate or legacy).

We've seen this happen before when using an older version of react-native-windows-init, since search path changed before we released a final version of 0.63. Try making sure you have a recent version of the repo synced. There are otherwise some debug steps I could give.

**Comment by chrisglein** [comment]
If there's something that's updated as recently as final 0.63 maybe we should add some troubleshooting steps to that wiki?
