### ISSUE TITLE
Make Hermes the default JS engine

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#6136]

**Comment by chrisglein** [comment]
@tudorms @Khalef1 What is the appropriate timeline for this for RNW? I think the intent of this issue was not so much to track the work but to communicate when we thought it was going to happen... but obviously with shifting release rhythms and priorities that hasn't been the case. What should we be tracking?

**Comment by tudorms** [comment]
I think we need to wait for upstream React Native to switch the default to Hermes first. As far as I know there aren't any blocking issues (but since we're not actively using Hermes, it would be nice to get a confirmation for that from early adopters).

**Comment by vksgautam1986** [comment]
Hermes is a default engine for React native since 0.70 version.
https://reactnative.dev/docs/hermes#:~:text=Hermes%20is%20the%20default%20engine,to%20enable%20Hermes%20on%20iOS.
