### ISSUE TITLE
Clearer error messages for unsupported CSS units

### ISSUE THREAD

**Issue by aberba** [microsoft/react-native-windows#6217]
From `NativeUIManger.cpp`, you have:

```cpp
static YGValue YGValueOrDefault(const folly::dynamic &value, YGValue defaultValue) {
  YGValue result = defaultValue;

  if (value.isNumber())
    return YGValue{static_cast<float>(value.asDouble()), YGUnitPoint};

  if (value.isNull())
    return defaultValue;

  if (value.isString()) {
    std::string str = value.getString();
    if (str == "auto")
      return YGValue{YGUndefined, YGUnitAuto};
    if (str.length() > 0 && str.back() == '%') {
      str.pop_back();
      folly::dynamic pct(str);
      return YGValue{static_cast<float>(pct.asDouble()), YGUnitPercent};
    }
  }

  // Unexpected format, using default
  assert(false);
  return defaultValue;
}
```

The `assert(false)` just fails without any message as to why this happened. A message like `you used an unsupported CCS unit` might be a better dev experience. 

By the way, the code already returns  `defaultValue` so why `assert(false)`? How about just a warning?

**Comment by aberba** [comment]
commenting `assert(false)` out locally just works using `defaultValue` as a fallback

**Comment by chrisglein** [comment]
Can you provide the sample units you were using? We're assuming a "px" value but it'd be good to know.
We want to match the behavior of the other platforms here, whatever they do.

Looking at iOS, it provides a redbox failure:
![image](https://user-images.githubusercontent.com/26607885/95498288-6dde7680-0958-11eb-8908-619700e65222.png)
So we should probably do that instead of asserting.

**Comment by TheSavior** [comment]
An improvement to the iOS message (that should probably be upstreamed) is to detect `px` in the string and to tell them they can just specify the integer.
