### ISSUE TITLE
App certification fails due to HighVersionLie

### ISSUE THREAD

**Issue by exotexot** [microsoft/react-native-windows#6331]
Windows App Certification Kit - Test Results
App version:
2.0.2083.0
App Architecture:
x64
Kit Version:
10.0.19041.1
OS Version:
Microsoft Windows 10 Pro (10.0.19041.0)
OS Architecture:
x64
Report time:
25/10/2020 20:52:02

FAILED
Platform version launch
Error Found: The high OS version validation detected the following errors:
Task failed to enable HighVersionLie.
Impact if not fixed: The app should not use version information to provide functionality that is specific to the OS.
How to fix: Please use recommended methods to check for available functionality in the OS. See the link below for more information.
Operating System Version

System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 9.30 GB / 15.97 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30611.23 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.0
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
    react-native-windows: ^0.62.14 => 0.62.14
  npmGlobalPackages:
    *react-native*: Not Found

I also want to reference this recent issue regarding HighVersionLie: https://github.com/xamarin/Xamarin.Forms/issues/12510 which makes me think that this may not be a react-native issue. I'm just posting this in case people are facing similar issues, or even better, have someone hint me in the right direction.

**Comment by chrisglein** [comment]
Not going to be something specific to RNW most likely, but an issue with a difference in certification validation that you ran locally versus what is run when it's submitted to the store. We'll follow up to see if there's a known cert issue here, since it seems like based on the Xamarin issue you linked that many others are hitting this.

**Comment by justcoding121** [comment]
I am having the same issue since I updated visual studio 2019 to latest version (16.7.6) few weeks ago, and using a newly generated publisher certificate from my windows developer account on a differant machine. I don't know how to use the old publisher certificate, if it was stored in old computer I am not able to get it back. Either way, thew new certificate was generated through visual studio project manifest => Packaging tab => Choose certificate button.

App certification fails both locally and on store after submission review with the same message. I used to be able to update smoothly after publishing locally with certification and then uploading to store. All my NuGet packages are on latest stable version, including that of Xamarin Forms. 

I cannot update the app in windows store to keep my app features in sync with Android and iOS versions. I give up few times as build and certification itself takes like 15 mins. Posting relavant screenshots below if that helps.



![image](https://user-images.githubusercontent.com/2637679/97261419-6c300200-17e4-11eb-9ad7-ede3ba0a95cc.png)

![image](https://user-images.githubusercontent.com/2637679/97261520-9e416400-17e4-11eb-93bd-542c4c361326.png)

![image](https://user-images.githubusercontent.com/2637679/97261579-b9ac6f00-17e4-11eb-9797-99de878c3b49.png)

![image](https://user-images.githubusercontent.com/2637679/97261227-004d9980-17e4-11eb-9096-d93901fd5f66.png)

**Comment by asklar** [comment]
Issue understood - not specific to RNW. Following up internally first to get a KB article published on this.

@justcoding121  @exotexot you should be able to ignore this error and still submit the package to the store - could you try that and let us know if you run into any issues doing this?

**Comment by justcoding121** [comment]
I can confirm that I was able to now ignore the error and submit to store successfully.

**Comment by asklar** [comment]
thanks @justcoding121 . I've asked the WACK team to publish a KB article about this, glad to hear you were able to submit successfully, this issue only affects running WACK or AppVerifier locally.

**Comment by asklar** [comment]
In the meantime, you can work around this issue by taking ownership of the following regkey:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MsSense.exe

1. open regedit
2. navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MsSense.exe`. You will get an error that it cannot be opened, ignore it for now.
3. Right click on it, select permissions. You get another error, ignore it too.
4. Click on Advanced. Another error, ignore it.
5. Select **Change** next to the Owner label at the top
6. Change the owner of the regkey to either your user, or **Administrators** if you are an administrator on your PC
7. Press ok, ok, ok.

Then try re-running WACK and you should be able to get the WACK tests to run.

**Comment by asklar** [comment]
Alternatively here's how to script it from Powershell:

```powershell
$uname = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$user = new-object System.Security.Principal.NTAccount($uname)

pushd "HKLM:\software\microsoft\windows nt\CurrentVersion\Image File Execution Options"
$acl = Get-Acl '.\MsSense.exe\'
$acl.SetOwner($user)

$regRights = [System.Security.AccessControl.RegistryRights]::FullControl
$inhFlags = [System.Security.AccessControl.InheritanceFlags]::ContainerInherit
$prFlags = [System.Security.AccessControl.PropagationFlags]::None
$acType = [System.Security.AccessControl.AccessControlType]::Allow
$rule = New-Object System.Security.AccessControl.RegistryAccessRule ($user, $regRights, $inhFlags, $prFlags, $acType)

$acl.AddAccessRule($rule)

$acl | Set-Acl 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MsSense.exe'

popd
```
