### ISSUE TITLE
Audit Community Modules for Thread Affinity Issues with RNW 0.64

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6444]
#6284 changes semantics around native module thread affinity, where native modules are now called on the JS engine thread instead of the UI thread. Previous UI threadiness was unintentional, but likely means there are community modules using UI-thread affined resources from a native module.

We should try to provide a transition path for the break (e.g. UI-thread native modules though QuirkSettings), but may also need to audit any community modules that we are responsible for maintaining. Because these are generally lacking test coverage, it is likely we will otherwise see many of them break with 0.64.

**Comment by asklar** [comment]
Any native module that needs to access UI elements will need to be audited. Do we have a list? ViewManagers are not affected, only Native Modules.
https://microsoft.github.io/react-native-windows/docs/supported-community-modules

**Comment by asklar** [comment]
Meta-point: we have breaking changes for NM across releases (C# for 0.63, e.g.). How do we deal with keeping community modules working despite breaking changes in the platform? 
Breaking changes in Native Modules should have a higher bar than other breaking changes. 
Do we need to make the breaking change now at all?

**Comment by chrisglein** [comment]
At this point I believe we've taken this change into 0.64 but not backported further than that. Now that 0.64 first preview is out, we have a clear release candidate to evaluate native module compatibility against.

**Comment by chiaramooney** [comment]
See [here](https://github.com/microsoft/react-native-gallery/tree/v0.64.0-preview.5/src/examples) for page list of native modules which have been added to the gallery running on 0.64. All components attached to these pages are running and working on 0.64. 

react-native-webview component is blocked at the moment as a change was needed for the component to be able to be deployed in an RNW app. There is a [PR](https://github.com/react-native-webview/react-native-webview/pull/1850) out now for the update necessary. Once new version of webview is released it can be added to gallery and tested on 0.64. 

react-native-progress-view is blocked at the moment. [PR](https://github.com/react-native-progress-view/progress-view/pull/55) out now to fix build issues with module. Once new version of progress-view is released it can be added to gallery and tested on 0.64. 

react-native-linear-gradient blocked at the moment. Module needs updating in order to be compatible with 0.63+. Issue created to track this task #7008.

**Comment by chiaramooney** [comment]
Closing issue for now; all community modules we maintain have been reviewed and documented in above comment.
