### ISSUE TITLE
C++/WinRT based projects (app or module) are unable to consume C# nugets

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#6503]
This is not an issue with us per se, but something that affects us. If you try to add a C# UWP dependency to any C++/WinRT project, the operation will fail, using VS or nuget.exe.

How this affects us:

C++/WinRT Apps cannot consume C# native modules distributed via nuget. They can only consume those modules by source (presuming the source itself doesn't hit any of the other bugs impacting C# use by C++/WinRT, like #6470, #6473).

C++/WinRT Native Modules cannot consume C# libraries provided via nuget. So if you wanted so say, write a module to expose Telerik controls, you have to use C#.

**Comment by Scottj1s** [comment]
The new "Windows Desktop Compatible" setting in VS 16.8 (which sets $(DesktopCompatible) to true) enables UWP projects to be consumed by Desktop projects (note that to date, this has not been publicly documented beyond [a comment in the issue](https://developercommunity.visualstudio.com/idea/1128228/a-reference-cannot-be-added-because-the-two-projec.html)).

See also: 
https://github.com/microsoft/ProjectReunion/issues/58

**Comment by asklar** [comment]
thanks for the note @Scottj1s, note that all of the modules/apps discussed here are UWP though, does that new property gain us anything in that case?
