### ISSUE TITLE
CI Loop:  tree dump comparison file not being uploaded as artifacts

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#6684]
@chiaramooney  ran into this issue while working on:
https://github.com/microsoft/react-native-windows/pull/6609

The problem we're seeing is that when one of the E2E tests fails a master treedump comparison, the comparison file is not being uploaded as a test artifact.  This makes it impossible to see what actually failed by looking at the logs.

I created a little PR to repro this issue here:
https://github.com/microsoft/react-native-windows/pull/6683
Go to the CI loop ADO page and dig into the E2E test failure.  Notice you cannot locate the test comparison file, which is supposed to be here:
![e2e-errors](https://user-images.githubusercontent.com/33470154/101231081-c2068e00-365d-11eb-9981-3505746dea96.png)

Chiara and I debugged together and can see that when we run the test locally, the expected comparison file is generated on the local box.  This makes me think the issue is somewhere in the artifact publishing process.

**Comment by asklar** [comment]
https://dev.azure.com/ms/react-native-windows/_build/results?buildId=126297&view=logs&j=d748dad3-a0b7-5fdb-711c-b2cdfdfc24a4&t=927661ef-c977-523f-48c0-326d34d7e9ac&l=9
```
found 0 files
Finishing: Copy tree dump output files
```
This is because the publisher was changed in #6125 which changed the Package Family name.
We should be careful when updating things like app name/PFN since it has downstream implications like this one.

**Comment by asklar** [comment]
FYI: Looks like changing the certificate is not enough. The files are being written (see changes in the linked PR that prove this) however they are not accessible from outside. This makes me think either the files are being deleted, or FS access is being virtualized to be saved to a different location even if the app sees it being saved to the location it expects.

**Comment by asklar** [comment]
CC @kmelmon 
Looks like the files are being deleted because of this newly added snippet:

```csharp
            // RNTester will load the most recently visited example page (or a provided link to an example) if
            // reopened. Clear local storage to suppress that behavior and always go to the example list first.
            // #6319 Tracks a better way to do this
            ApplicationData.Current.ClearAsync().AsTask().Wait();
```

We save the actual visual tree dumps to `ApplicationData.LocalFolder`, so when a test fails and the app is killed and a new test is run, the appdata folder is deleted and the failure dumps are deleted with it.
