### ISSUE TITLE
Profiling UWP UI Performance

### ISSUE THREAD

**Issue by erikschlegel** [Microsoft/react-native-windows#67]
Something similar to the RN Android memory profiler https://facebook.github.io/react-native/docs/android-ui-performance.html#content

**Comment by rozele** [comment]
Also included in the scope of this work is to implement the Tracer utilities with ETW hooks, and get the JS profiler stuff working.  This will probably need to be broken down into smaller issues.

**Comment by rozele** [comment]
Closing this issue. I believe the "spirit" of this issue is some kind of custom FPS profiling mechanism, similar to the one on Android: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/devsupport/FpsView.java

If someone is interested, we can always re-open.
