### ISSUE TITLE
Support HTTP headers for source prop on <Image> components

### ISSUE THREAD

**Issue by rigdern** [microsoft/react-native-windows#689]
This would allow developers to specify headers to include in the HTTP request when fetching a remote image. For example, one might leverage this when fetching an image from an endpoint that requires authentication:

```
<Image
  style={styles.logo}
  source={{
    uri: 'http://facebook.github.io/react/img/logo_og.png',
    headers: {
      Authorization: 'someAuthToken'
    }
  }}
/>
```

Note that the header values must be strings.

Here are the iOS and Android PRs for that feature:
- iOS: https://github.com/facebook/react-native/pull/7338
- Android: https://github.com/facebook/react-native/pull/7791

**Comment by deregtd** [comment]
Checking in as well.  Any chance of any updates?  I'll need to figure out an answer here one way or another in the coming weeks.

**Comment by chukcha-wtf** [comment]
@deregtd in our case we've solved it in a very dumb way (that, surprisingly, works). 

You can use `fetch` request before rendering an image with `headers` and `cache: "force-cache"` params. After that, you should be able to display the image by using just a URL as a source prop `<Image source={{uri: 'image/url'}} />` because it's already cached

**Comment by deregtd** [comment]
Oh god that's beautiful and awful, but more importantly, it seems to work great.  Thanks so much for the workaround!  Also note to anyone that follows, you literally have to use the fetch() wrapper, an xmlhttprequest does not do it!
