### ISSUE TITLE
Is it possible to make auto-linking work with modules which contain XAML elements

### ISSUE THREAD

**Issue by jaimecbernardo** [microsoft/react-native-windows#6915]
Currently, adding the `#include` line to `pch.h` is still needed for modules that contain XAML elements, or there'll be an error when compiling the application's generated `XamlTypeInfo.g.cpp` file, even when the module supports auto-linking.

Asking the user to add the `#include` line in `pch.h` is a simple instruction, but is there currently a way to have auto-linking pick up on the XAML controls contained within the module?

Thank you.

**Comment by asklar** [comment]
The pch/xamltypeinfo issue is a XAML / cppwinrt behavior so it isn't specific to cppwinrt.
See:
- https://microsoft.github.io/react-native-windows/docs/next/native-modules-troubleshooting#compile-error-xamlmetadataprovider-is-not-a-member-of-winrtmymodulename
- https://docs.microsoft.com/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt#troubleshooting

The utility of auto-linking is to be able to add "glue" to an app so that it can consume a module, so really it is only applicable when running on the app project side. This means you still need a module to be able to get built without any app around it; so I don't think autolinking can help with this today.

**Comment by jaimecbernardo** [comment]
From the links provided, the current solution is to have the module user add the `#include` statement in the app's `pch.h`.
Thank you for the answer and additional references.
