### ISSUE TITLE
how to securely implement OAuth2 Authorization Code Flow

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/react-native-windows#7084]
There is a native module called [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth/issues/280) that only supports iOS/Android and they have expressed they have no plans to support it on Windows.

Anyone aware of any other modules or examples that show properly implementing the OAuth2 Authorization Code Flow with Identity Server 4?

I have of course googled to the extent of my ability and not found anything that supports Windows and seems to do anything close to a passable job.

**Comment by chrisglein** [comment]
There's a issue template for asking for Windows support for modules. You could file one for this modul. For example here are two:
- [react-native-auth0](https://github.com/microsoft/react-native-windows/issues/6787)
- [react-native-azure-auth](https://github.com/microsoft/react-native-windows/issues/4148)
To date I don't think anyone has gone after the auth modules, otherwise you could look to them specifically for examples. It does sound like the module you want isn't planning on adding Windows, but they would accept PRs to add Windows support.

In the meantime your next best option is to drop into native code. Once you're in native Windows code there should be good examples of how to use OAuth.
