### ISSUE TITLE
FrameAnimationDriver animations for scale transform ends with incorrect scale value

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#7214]
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Run RNTester, open Native Animated Example
2. Scroll to "Scale interpolation with clamping" example
3. Click the example to start the animation.

## Expected Results
The native example size shrinks at the end of the "grow" animation (see video). I haven't dug too deeply into why this happens (sorry!), other than it seems to occur for scale animations that use the FrameAnimationDriver.

## Snack, code example, screenshot, or link to a repository:
- Repros from RNTester on master

https://user-images.githubusercontent.com/1106239/109071647-fd938000-76c1-11eb-9849-92aa60e1a373.mp4

**Comment by chiaramooney** [comment]
Looks like the interpolation input is set to the range of 0-0.5, but the range of the animation value is set to 0-1. When I locally change the interpolation input range to 0-1, the issue disappears. When I test the scenario on iOS/Android, the issue doesn't occur. Is it expected for interpolation outside of the input range to be handled? Was this choice of the input range specified for interpolation being different from the actual input range intentional?

**Comment by chrisglein** [comment]
Test page in question is [this one](https://github.com/microsoft/react-native-windows/blob/003602b90aeda1b2a43702c6a9307c0f01010e59/packages/%40react-native/tester/js/examples/NativeAnimation/NativeAnimationsExample.js#L514). It has a 0->0.5 input mapped to 1->1.4. The [docs on interpolation](https://reactnative.dev/docs/animations#interpolation) cover how that's supposed to map out. Is the test page configured in a way where 0 to 1 is assumed but this individual test is off?
