### ISSUE TITLE
How can I use third party DLL?

### ISSUE THREAD

**Issue by Losiyu** [microsoft/react-native-windows#7293]
I am currently developing an app by using third party SDK, which includes many dlls. I want to call some functions in those dlls. How can I do it?
"react-native": "0.63.4",
"react-native-windows": "^0.63.0-0",
npm: 6.14.11
node: 14.16.0

**Comment by asklar** [comment]
@Losiyu it depends; you should follow the 3rd party SDK's instructions for how to use their SDK in the context of a UWP app, since React Native for Windows apps are UWP. There's some information in our docs that might be useful too:
[Native code - use of non-WinRT libraries](https://microsoft.github.io/react-native-windows/docs/next/native-code#use-of-non-winrt-libraries)
