### ISSUE TITLE
[Dead code] remove JSBigAbiString

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7376]
This type is not used by anybody, should be deleted.

**Comment by Oscar-Santacruz** [comment]
I'm working on this

**Comment by Oscar-Santacruz** [comment]
Is there a variable with the name "JSBigAbiString" or do you reference variables in the js scripts?

**Comment by NickGerleman** [comment]
Closing as per comments in https://github.com/microsoft/react-native-windows/pull/7520

**Comment by vmoroz** [comment]
@asklar, @chrisglein, @NickGerleman, it is unfortunate that this issue was marked as a "Good First Task". Generally, it is OK to look for the dead code inside of the Microsoft.ReactNative.dll project. Any other code especially in the Shared project needs to be double checked for being used in the react-native-win32.dll. Even if we have classes that may not be referenced directly, we must check the .def files that list all exported functions and types.

**Comment by asklar** [comment]
@vmoroz can you provide a list of files used by Office? I'm reality this repo should not need to concern itself about Office internals so I'm wondering if there's a short term plan we can put in place to decouple

**Comment by vmoroz** [comment]
+@Khalef1, +@acoates-ms

@asklar, let's consider all current files are being used by RN for Windows. The JSBigAbiString is not internal to Office - it is part of the react-native-win32.dll public API and exposed by the .def files. It has the same purpose or reason to be as any other file such as ReactNativeHost.idl.

Currently RNW targets several Windows platforms: UWP, XAML islands, WinUI 3, and Win32. The Win32 was the first platform and it is one of the most important because it is UI-technology agnostic. We work towards improving the API and code reuse. The last thing we want to do is to split repos. Let's not go this route.

I propose to continue any further discussions on this topic offline.
