### ISSUE TITLE
Future Roadmap?

### ISSUE THREAD

**Issue by rraczae** [microsoft/react-native-windows#7383]
Hey Team,

Do you have any roadmap for 2021 or long term support plan? We have a react native application working well and looking to port it to surface. This library looks very promising, however without long term commitment from msft I don't think we can allow to risk using it. Otherwise great work and really like the concept and the approach.

Cheers!
Robert

**Comment by rraczae** [comment]
@chrisglein thank you Chris! Awesome, that is reassuring. 

I think it would also be great if we had something under [microsoft docs ](https://docs.microsoft.com/). In my experience that just helps building confidence in a product when decisions are made.

**Comment by stmoy** [comment]
Following up on this - we're tracking our upcoming roadmap here: https://github.com/microsoft/react-native-windows/discussions/8906

I need to update that discussion with our latest thoughts, but that's where we will be posting our latest status. 

Since we're tracking updates on the discussion linked above, I'm gonna go ahead and close this for now and we can follow up over there as needed.
