### ISSUE TITLE
How to Updating / Upgrade older react-native project to latest. 

### ISSUE THREAD

**Issue by Jtomage** [microsoft/react-native-windows#7407]
I have been looking for documentation to update the react native project to the latest version. Currently working on the windows section. 

The original was created using npm so many of the yarn command do not seem to work. 

tried react-native upgrade and npm-check-updates but still have the same issues as they both modify the packages needed.

I tried following the guide on adding to established project but that fails first due to package-lock.json found, files generated by tools other than yarn. 

After removing package-lock.json it fails due packages being depreciated such as . 

`warning react-native-windws > @react-native-windows/cli > xmldom@0.3.0: Depreciated due to CVE-2021-21366`

There was custom modifications done to the windows sections as there were problems with display and connecting to sqlite.

As it seems right now I am stuck on the older version of react-native / react-native-windows

react: 16.2.0
react-native: ^0.52.3
react-native-windows: ^0.52.0
react-native-sqlite-2: ^1.6.0
react-native-device-info: ^.18.0
nodejs: 14.15.5

**Comment by asklar** [comment]
straightest path forward is to generate a new app with the latest version, open the app in Visual Studio, and copy your app code into the new app.

**Comment by chrisglein** [comment]
Especially since you're coming across such a version gap (0.52 to 0.64), in which the entirety of React Native for Windows has been rewritten, you're definitely going to want to generate a new app and bring over your app code.

We do want to document options here, tracking issue [here](https://github.com/microsoft/react-native-windows-samples/issues/258), and integrating with upgrade helper (issue [here](https://github.com/microsoft/react-native-windows/issues/3470))
