### ISSUE TITLE
[NuGet] creating app with NuGet should not bring down RNW npm package

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7465]
It should not be necessary to have two "sources of truth", the nuget packages should have everything that's needed. This also eliminates having to do version match checks at build time.

**Comment by NickGerleman** [comment]
We will still need the npm package for everything that's not native library code. E.g. all of the JS sources, the CLI, etc. I don't imagine we could remove it. 

PackageReference would eliminate the need for version matching bc that lets us declare the dependency within the npm package instead of the template. We can't really do that though for C++. At some point Danny and I were talking about what it would take to home roll that, but I don't think it's a good immediate idea.

**Comment by NickGerleman** [comment]
Alternatively, if we did do more build time codegen (e.g. what autolinking does), we could maybe have the npm package write to packages.config to make the version changes more automatic.

**Comment by asklar** [comment]
What i'd like to see is us shipping a "partial bundle" that contains all of the JS that RNW/RN/R.js provide, which can then be combined with the app's own dependencies+app code to form the bundle. Kind of like when you use an SDK, you don't *usually* have to recompile everything from scratch, you just compile your own things and link it together with the SDK.

**Comment by NickGerleman** [comment]
I'm having trouble understanding what this would look like in terms of JS dev experience, where these deoendencies would be bundled in a NuGet package, external from typical node_modules structure. I expect this would fight pretty hard against what is established (both in RNW and the community), but would love to hear more if you have a proposal on what this could look like.

Office internally has a motion of "platform bundles" where we combine some dependencies into a single bundle. The reasons for this are more so that dependencies can be shared between different experiences that have separate bundles, instead of anything developer facing. This is fairly involved though, and inner loop still relies on NPM packages.

This to my understanding was months of work, and was scoped towards something smaller than what is proposed.
