### ISSUE TITLE
Update JavaScript core controls to match WinUI2.6 styles

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#7558]
- [x] Audit JS controls (e.g. Button) and build a checklist here
- [ ] Update them to match WinUI 2.6 visual standards

**Comment by NickGerleman** [comment]
https://github.com/microsoft/react-native-windows/issues/5268 is related.

Right now Button just copy/pasted some Android styling. It is not very feature-filled, and doesn't really even support things like hover styling. Making it look more Windows-like seems good, but I don't expect parity could be a goal.

From Eli:

> The goal of is "A basic button component that should render nicely on any platform."
>
> I believe the intent of the existing platform styles is to kinda (but not super well) match the experience of default platform buttons. So on Windows I'd expect Button to kinda look like a default Windows button. Similar on Mac.
> 
> In reality, this component doesn't matter and nobody should really be using it in prod. It's just there to make it really easy out of the box to get some button behavior to prototype something with and not need to bring in a 3rd party library for that. So don't put too much time into making this perfect. :) Feel free to style it however you'd like :)

**Comment by chiaramooney** [comment]
Looks like list of controls that we have that are purely JS are:
- Button
- FlatList
- Touchable (TouchableHighlight, TouchableOpacity)
- Pressable

Of these only the Button control needs special styling to match the Windows standard, since FlatList is just a simple list display where the developer has control over the styling and the Touchable/Pressable components are built to be components that you always style from scratch (have no attachment to native plat styling)

Issue tracking update to Button control here: #5268
