### ISSUE TITLE
Update API doc version in CI every time we cut a release

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7599]
When we cut 0.65 (or any release), we currently update the docs in the website repo by creating a new folder like `version-0.65`, and references inside each markdown file are updated to point to the "original name" so that Docusaurus can find the right document for a given version.

We now have API doc generation happening in CI. This is set up to build the docs for "vNext" (i.e. `/docs/next/foo`).
So the docs checked into the website repo have the right version metadata, but the ones generated in CI don't since they're pointing to "vnext". So any time we cut a new release, we will also need to update the version of the generated docs so that we can continue to just copy them over (and not lose the versioning metadata).
To do that we have to tell winmd2md to generate docs for the cut version by passing the following flag to winmd2md: ` /apiVersion 0.65`

**Comment by chrisglein** [comment]
There's a script for the release process and this should be added to that.

**Comment by chiaramooney** [comment]
@asklar What if the API docs were added as is to \docs in rnw samples and then the website doc cutting script is run. The doc cutting script automatically updates the version ids for all documents to version-0.XX-<original id>? Could you clarify why this wouldn't work

**Comment by asklar** [comment]
> @asklar Alexander Sklar FTE What if the API docs were added as is to \docs in rnw samples and then the website doc cutting script is run. The doc cutting script automatically updates the version ids for all documents to version-0.XX-? Could you clarify why this wouldn't work

the docs for vnext and for 0.xx-stable need not match, we add/change/remove APIs, so the contents of the docs are bound to be different (not just in version numbers).

**Comment by chiaramooney** [comment]
@asklar Sorry let me clarify. Because we don't cut the docs until the release is ready, typically the "vnext" docs in the website (\docs) holds the info for our latest 0.XX-stable branch instead of info for "vnext" in the repo. 

So adding the 0.XX-stable docs to docs\native-apis isn't writing over information or assuming the docs won't be different for vnext. It's that the vnext api docs information is never held on the website because we only add in 0.XX-stable api docs right before a release is cut. 

From glancing at the winmd2md code, it looks like running the executable with the /apiversion 0.XX option simply builds the winmnd files as they would have been built without the option but with the "id" value altered and "orginal_id" field added. 

So if you took the winmd files generated in CI for a 0.XX-stable branch with their "id:" value still targeting vnext you'd have the right winmd data for the new version, then add those files to docs\native-apis, then cut the docs, all of the api files and remaining docs files would have their versions updated all together. Also, you would then have less duplication across the versioned_docs because docusaurus will only cut a doc if it has changed from the last time, so we'd be in better alignment with the flow of docusaurus.

**Comment by chiaramooney** [comment]
sync'd offline. Added task to release list of todos. Closing issue.
