### ISSUE TITLE
Unity project and react-native-windows project combine it all together

### ISSUE THREAD

**Issue by pujre** [microsoft/react-native-windows#7810]
My unity project is responsible for the game content, and the react-native project is responsible for the active interface and ui. I now want to combine them. This is no problem under the Android and ios platforms, but under the windows platform, I don’t know how to do it.

I have an idea: build the unity project into a Universal Windows Platform, and then merge it with the react-native-windows project, but that fails

Now what should I do to achieve this function

**Comment by chrisglein** [comment]
I _think_ what you need to do here is set up your UWP app first (using the RNW CLI to create your app template) and then host Unity inside of it, rather than start with an app created by the Unity toolchain. My information here may be dated, it's been a long time since I've tried to do this.

Here are some resources I found that might be helpful:
- [Integrating Unity into Windows and UWP applications](https://docs.unity3d.com/Manual/UnityasaLibrary-Windows.html)
- [Creating UWP Apps with Unity and XAML](https://channel9.msdn.com/Blogs/One-Dev-Minute/Creating-UWP-Apps-for-Xbox-with-Unity)

Is that helpful?

**Comment by pujre** [comment]
> I _think_ what you need to do here is set up your UWP app first (using the RNW CLI to create your app template) and then host Unity inside of it, rather than start with an app created by the Unity toolchain. My information here may be dated, it's been a long time since I've tried to do this.
> 
> Here are some resources I found that might be helpful:
> 
> * [Integrating Unity into Windows and UWP applications](https://docs.unity3d.com/Manual/UnityasaLibrary-Windows.html)
> * [Creating UWP Apps with Unity and XAML](https://channel9.msdn.com/Blogs/One-Dev-Minute/Creating-UWP-Apps-for-Xbox-with-Unity)
> 
> Is that helpful?
 yes。
Thank you for this information. You mentioned that you have tried this, did you succeed in merging the projects?

**Comment by chrisglein** [comment]
> You mentioned that you have tried this, did you succeed in merging the projects?

I think I got distracted and ended up exploring the Unity 2D APIs since I'd never tried them. So I've heard of it being done but haven't myself.
