### ISSUE TITLE
TextInput textAlign does not affect placeholder

### ISSUE THREAD

**Issue by DanielBroad** [microsoft/react-native-windows#793]
Using 

`textAlign: 'center',`

changes the alignment of the entered text, but does not align the placeholder correctly. 

iOS and Android work as expected.

![screen shot 2016-10-17 at 14 37 17](https://cloud.githubusercontent.com/assets/3619289/19439791/5e57b988-9477-11e6-97e4-4e52583042d9.png)

**Comment by rozele** [comment]
Thanks for filing @DanielBroad, I presume this is an issue with the underlying TextBox component in UWP and we won't have much control over how that placeholder text is rendered, but I'll take a look.

**Comment by rozele** [comment]
One option to work around this would be to create a custom ContentControl wrapper for TextBox and map the textAlignment React prop to also change the TextBox style template as described in http://stackoverflow.com/questions/33479705/center-placeholder-text-in-textbox

**Comment by furkee** [comment]
I am also having this issue. `textAlign: 'center'` does not even affect the view when user types something if TextInput.securedEntryText is true. Passwords will just appear on the left-hand side of the box.

Another issue is when TextInput's height is larger than font size, texts will not appear on the middle of the box but rather on the top.

NOTE: Password text styling issue persist even if PasswordBoxWindows from react-native-windows package is used.

**Comment by furkee** [comment]
I may work on a solution for this one if you are also willing to solve it and can help me?

**Comment by rozele** [comment]
@furkee I think implementing this for open source would be reasonably trivial, but likely time consuming. I would replace the `ReactTextBox.cs` imperative implementation with a XAML User Control with a single nested `TextBox` (call it `ReactTextBoxControl`). In the designer for XAML, you can right click the `TextBox` > Edit Template > Edit a Copy. This will generate the template used for the TextBox in the .xaml file. Once you have the template generated, you can edit it as shown above in the StackOverflow link. Make sure to the `HorizontalAlignment` property for the placeholder text to a bindable property instead of just `Center`.  Then you'll need to expose all the properties for the TextBox to the `ReactTextBoxControl` so they can still be set from the ViewManager.
