### ISSUE TITLE
Remove RTTI dependency in RN Core

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#7981]
RN core makes use of RTTI, which we don't want in Windows (produces binary bloat)

**Comment by asklar** [comment]
@acoates-ms my main concern with having it enabled in Debug is forking behavior in ways that are unexpected ("this works in debug but breaks in release", like we've seen for native modules). If the usage of RTTI is only for asserts then that seems ok to have in debug but if there's any visible functional divergence, I think we'd want to opt out of it. Thoughts?

**Comment by acoates-ms** [comment]
Most of the cases are literally within react_native_assert statements, so they will be debug only. -- And they seem like useful asserts since they are verifying that casts are correct.
We would still break the build if we hit any dynamic_cast in ship.  So its probably ok to just disable RTTI in release.

**Comment by ecreeth** [comment]
RN core is trying to remove the RTTI flags. Refs https://github.com/facebook/react-native/commit/a6768bfd70187634e587d7b2e92d2b6735a4037e and https://github.com/facebook/react-native/commit/7dc22116b077fcc4dc0eb1bdb4e6376c47a16d85

**Comment by acoates-ms** [comment]
This is only on fabric builds currently.  Ok to push past 0.66.
