### ISSUE TITLE
Visual Studio / IDE best practices

### ISSUE THREAD

**Issue by juhasuni** [microsoft/react-native-windows#8085]
We're having constant issues with building and even loading our solution in Visual Studio. Some examples: 

- VS needs to be sometimes started multiple times before the solution loads properly
- VS hangs with some background process, like "Loading IntelliSense" that never seems to finish
- Simple actions like switching from Debug to Release takes couple of minutes (not sure what it does here, does it build the JS bundle?)
- Building the solution takes ~15 minutes (we have a semi-large app with ~15 projects)
- Publishing the product takes another 15 minutes or so, regardless if the solution has been built previously or not
- Re-building/launching the Debug app takes couple of minutes even without code changes

Overall the developer experience when working with Visual Studio is poor, especially when compared to XCode or event Android Studio.

Since there are lots of experts with working with Visual Studio here, I'd like to hear if there are known best practices for VS or recommendations for the IDE to be used (should we switch to VS Code?).

We're moving towards CLI builds but that hasn't worked for us yet as we're still in 0.62 and our app has a special packaging (we have a CLI app integrated into UWP app). I also understand that these issues may be partly related to our app structure, but I'd be surprised if others aren't facing similar issues.

**Comment by asklar** [comment]
Hi @juhasuni , thanks for the detailed questions/feedback.

We've made lots of improvements in the developer inner loop / build system / integration with VS in recent releases. There was a bug at some point in 62 where changing Debug->Release would cause the JS Bundle to be built by the intellisense compiler, which was fixed. 

Builds taking 15min: Notably, we have been working on NuGet support, which can get an app built within a minute (since we aren't building the framework at that point). NuGet support for native modules is coming soon. 
If you are building everything from source, then 15 minutes seems par for the course. There is a lot of native code that needs to be compiled :)

I believe publishing requires rebuilding so that would explain the 15 minutes. This is standard for packaged apps, not just RNW apps.

Rebuilding would clear away any built artifacts so it would take another 15min. Launching without making changes should only require a no-op incremental build, so I'd assume under a minute.

We have 0.65 in preview at the moment, with lots of improvements. I'd strongly encourage you to upgrade soon, and share any additional feedback/questions you might have. We are very interested in making the developer experience of RNW apps better.

**Comment by juhasuni** [comment]
Thanks @asklar  for your comments! We're on our way towards using the most recent version. I'll post my findings in this thread once we're there. I'm aware of the NuGet development, I bet it is going to speed things up. And thanks for the great effort you're putting in to this.

**Comment by asklar** [comment]
Great, let us know what you find!
