### ISSUE TITLE
Developing a C++/winrt modules is different when compared with Android and iOS

### ISSUE THREAD

**Issue by jaimecbernardo** [microsoft/react-native-windows#8105]
When developing a native module for Windows using C++/winrt, the native implementation structure ends up being very different when we compare it to the Android / iOS implementation of the module, making it have a steeper learning curve / being harder to maintain alongside the other implementations.

Some examples of this are:
- The way that we can use annotations for UI components for native properties on Android/iOS vs `ViewManagerWithNativeProperties`.
- The way nested native components can be implemented on Android/iOS through extending Shadow Nodes or Views vs `IViewManagerWithChildren`.
- The way OOP can be used in Android and iOS for inheriting other UI components implementation, which can extend each other's logic, vs the IDL-based implementation for C++/winrt implementation of UI components, which extends interface but doesn't re-use code.

There is also another caveat I've run into.
- Some property names have implicit semantics (e.g.: can't use transform for a property name unless it's a 4x4 matrix): https://github.com/microsoft/react-native-windows/issues/7300

**Comment by asklar** [comment]
The approach for Native modules for iOS (Objective C) is macro based, whereas for Android (Java) it's annotation based.
For RNW, we allow writing native modules in C# (with annotations/attributes)  or C++/WinRT (with macros).
We could investigate providing a runtimeclass that hides some of the intricacies of cppwinrt (e.g. the micro interfaces) and have some more guardrails (standard way of declaring properties, methods, etc.)

**Comment by acoates-ms** [comment]
I think the issues listed are all about UI components, rather than native modules.

I agree that the current view manager implementations is not ideal.  At this point it would likely be a large change to bring it to closer parity with iOS/android.  I'm hoping to take a better look at this with Fabric, which will likely require changes anyway, so better to only have the community have to do a large change once rather than pushing a rewrite of the existing view managers.
