### ISSUE TITLE
Rename "desktop" to "Office" or similar

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8128]
We are pushing the Windows App SDK (formerly known as Project Reunion) and the notion of Desktop / win32 apps, React Native on desktop apps, etc. It's going to be a bit confusing for people to see something called Desktop in the RNW repo that is not usable for them. Proposals: Office, NetUI, ...?

**Comment by chrisglein** [comment]
Priority would be to rename public facing things instead of file structure and such (which only developers working on the platform are going to see). The NPM package is already clearly named. Nuget name has Office in it (and isn't published to nuget.org). So it may be that the solution files are the most confusing.

For determining Reunion/not we likely don't want a whole platform identifier fork but rather an API to find out which mode you're in, similar to TvOS.

**Comment by chrisglein** [comment]
Also it seems like @acoates-ms may be cleaning up some of the solution stuff here as a result of cleanup to stop using the exported functions and use the winmd functions.
