### ISSUE TITLE
Do not create temporary certs in default template

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8202]
We've been doing work to remove temporary signing certs from our repo. Apart from security goodness, these checked in certs expire and leave the world unable to deploy. FURN just recently hit this.

We should avoid temporary certs in the default case.

**Comment by chrisglein** [comment]
Certificates can be mysterious to those new to Windows development. Without one the app will only succeed in Debug as is. We should understand what the side effects will be for the developer experience if we aren't providing a default cert here. It's possible that the temporary cert is the best experience - needs some thought and investigation.

**Comment by chiaramooney** [comment]
Some initial investigation on this: 

Reasons to Remove the Default Certificates: 
- Removes the possibility that default certificates (which are attached to the React Native Windows team) are published publically.
- Developer is pushed to be proactive off the bat to add their own test certificate with their own password. 
- No temporary certificate present to fail unexpectedly. 

Reasons to Leave the Default Certificates in Place:
- By default developers should be able to build in Debug without a certificate. However, if they build in Release without one they will run into issues. Users will now need to generate a certificate or use the '--deploy-from--layout' option if they want to complete Release builds. 
- Certificates in general have an expiration date. Maybe we just need to highlight the documentation on the website to show that the temporary cert will need to be replaced and encourage that it's done sooner rather than later. Can we improve the discoverability of this info?
