### ISSUE TITLE
On trying to create package I got a message "certificate is password protected".

### ISSUE THREAD

**Issue by itsarnavsingh** [microsoft/react-native-windows#8247]
* I built the solution 
* Then I went to project > publish > create the package and I got the following message.

![image](https://user-images.githubusercontent.com/36072753/125641320-e138a8f3-de11-42f5-b2bc-053bbbab0363.png)

**Comment by chrisglein** [comment]
You have a temporary certificate. In order to publish to the store you'll need to create your own, alongside linking your account through VS so the package you produce can be published as you. This is fairly normal for Windows app publishing but we're working on better guidance here for people entering the ecosystem via RNW ([see this issue](https://github.com/microsoft/react-native-windows-samples/issues/62), @chiaramooney FYI).

**Comment by chiaramooney** [comment]
In the interim, here's some [guidance on packaging apps in Visual Studio](https://docs.microsoft.com/en-us/windows/msix/package/packaging-uwp-apps) which should help you get unblocked.
