### ISSUE TITLE
Create poisoned xaml headers to prevent including WUX headers directly

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8255]
Today it's easy for developers to mistakenly include / use a Windows.UI.Xaml header or type (when instead they should be using the straddled headers that know whether to use WUX or MUX, and the namespace aliases).

--

> OT, I wonder if we can create poisoned headers for WUX to tell folks to use the straddle types as a built-time error.

_Originally posted by @NickGerleman in https://github.com/microsoft/react-native-windows/pull/8248#discussion_r670090037_

**Comment by chrisglein** [comment]
Need to be careful to make sure there's no way to break 3rd party dependencies of WUX packages. There would need assurance that that can work and/or a way to opt out.

**Comment by chrisglein** [comment]
@NickGerleman You posed the suggestion for this one. Some of that captured in the PR link above. There were a fair number of questions about this in triage so if you have more to add put it here. I had interpreted this as catching a programming error with a cleaner error, but I was told that wasn't quite what this was.

**Comment by NickGerleman** [comment]
It's mostly just that. Within MSRN (where we are already using xaml straddle headers), including a MUX header where a straddle header is available is probably programmer error. We can create headers in front of the real MUX headers, that create compile time error if MUX headers are included (outside of the straddle headers). This is meant to help folks learn about the straddle headers early if they have not yet, instead of discovering them at PR time.
