### ISSUE TITLE
Debugger tools not fully connecting

### ISSUE THREAD

**Issue by jeanmaried** [microsoft/react-native-windows#8325]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
5.0.1
2. `npx react-native info`:
```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.54 GB / 15.69 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.16299.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    Visual Studio: 16.10.31424.327 (Visual Studio Enterprise 2019)
  Languages:
    Java: 16.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: ^0.64.0-0 => 0.64.14
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

I set up a basic app with RN 0.64 and redux toolkit to set up some basic redux. Here is an example repo: https://github.com/jeanmaried/rn-debugger-test

STEPS TO REPRODUCE
1. npx react-native run-windows
2. Run the app with the react-native-debugger app open so it doesn't open browser debugger
3. Debugger says connected to port 8081
4. React or Redux Devtools don't connect
5. App does not finish loading and stays on "Loading bundle." or "Connecting to Remote Debugger" screen
6. Metro server does not log an error.

I tried on RN 0.63 and RN for Windows 0.63 and it worked. I also tried on Android to make sure it was Windows specific and tried Android on 0.64 and it worked with debugger app, which is why I believe the error is related to either to RNfW 0.64 specifically or react-native-debugger. I have opened an issue on that repo too: https://github.com/jhen0409/react-native-debugger/issues/630

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by chrisglein** [comment]
> App does not finish loading and stays on "Loading bundle." or "Connecting to Remote Debugger" screen

So does that mean that, independent of debugger tools working, the app doesn't finish loading?
As in is the problem with Redux compatibility or is that somewhere in the 63->64 transition the app stopped working?

I don't think we've had a ton of questions about Redux so I can't say with confidence that anyone's validated that [react-native-debugger](https://github.com/jhen0409/react-native-debugger) works for Windows.

**Comment by jeanmaried** [comment]
If react-native-debugger is not open, the app will load correctly and open the browser debugger (though redux store never loads).

I will do a test without redux and report back if the app loads and the debugger at least loads react devtools.

**Comment by jeanmaried** [comment]
Yeah, redux doesn't seem to be the problem. The app doesn't load on 0.64 even if there is no redux code.

**Comment by acoates-ms** [comment]
This appears to be due to a difference in `react-native-debugger`'s implementation of the RN debugger API and RN core's.

`react-native-windows` is making a call to `flushedQueue` before a call to `executeApplicationScript`.  The standard RN debugger sends a reply to this call.  But `react-native-debugger` is not sending a reply to a call to `flushedQueue`.  `react-native-windows` ends up waiting for a response to this call before it will make the `executeApplicationScript` request.

I believe this is due to [this](​https://github.com/jhen0409/react-native-debugger/blob/639c02c0f3385c83e62b0ca483cb989db0e4b1a4/app/middlewares/debuggerAPI.js#L18) `scriptExecuted` check which will queue up the call if `executeApplicaitonScript` has not been called yet.  Where as the standard http://localhost:8081/debugger-ui/ debugger will reply with a response like this: `"{\"replyID\":4,\"result\":\"[[],[],[],0]\",\"error\":\"Failed to call function, __fbBatchedBridge is undefined\"}"`

We can look at removing this flush call, since I think RN core's web executor no-ops the flush method, where as we are sending a request across the websocket for it.

**Comment by chrisglein** [comment]
Fix is in and will be in the next release. Let's backport it to 0.65 (@acoates-ms) but that's probably far enough.

**Comment by acoates-ms** [comment]
This should be in 0.65.
