### ISSUE TITLE
Migrate playground-win32 to be a packaged win32 app

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8332]
Two options, to removes tar-pit traps re: activation, identity, etc.
1) MSIX package
2) Sparse package

**Comment by NickGerleman** [comment]
Heads up to anyone who takes this that there is a footgun hiding. We currently choose AsyncStorage backend based on whether the app is packaged or not, with the much better impl being used for unpackaged.

An unpackaged app switching to packaged  can experience AsyncStorage data loss and perf regression, since they do not migrate between each other.

https://github.com/microsoft/react-native-windows/blob/003602b90aeda1b2a43702c6a9307c0f01010e59/vnext/Microsoft.ReactNative/Base/CoreNativeModules.cpp#L88

**Comment by NickGerleman** [comment]
This doesn't matter for playground, but would affect current islands users of they package.

**Comment by asklar** [comment]
This issue is specific to playground-win32. We don't actively recommend using islands since it has drawbacks and caveats, but we have a sample in the repo, the sample should follow the most correct/recommended guidance, which is to package the desktop app.

**Comment by chrisglein** [comment]
Packaged is the more supported path. We wouldn't want to lose coverage of unpackaged. But that doesn't necessarily need to be playground-win32. If we move playground-win32 we need some app on hand for repro-ing and debugging unpackaged scenarios.

If playground has become the "please base your implementation off of this if you want to do islands" then we need something less overloaded. That should be the first step, to create a good sample there to relieve the double duty of playground.
