### ISSUE TITLE
Is the latest WINUI 3.0 fully supported?

### ISSUE THREAD

**Issue by jamespacileo** [microsoft/react-native-windows#8389]
I'm looking into using this library to work on a Windows 11 app, so I'm currently investigating which are the best tools to use.

It's not super clear if I can pick use react-native-windows if I intend to build a Win11 app or not.

Also my dev workflow uses WSL2, and I'm not sure if that's supported either?

Thanks

**Comment by chrisglein** [comment]
We do have experimental support for WinUI3 preview 4. Check out the docs [here](https://microsoft.github.io/react-native-windows/docs/winui3). We don't support the latest at this moment, as we need UWP support as that is the default for RNW apps.

You definitely can build a Windows 11 app with RNW.

However we haven't focused on WSL as a developer workflow, although that's a fair ask. We have a number of Windows-specific parts like using MSBuild and the Xaml Compiler and all that. So today it's not going to work, but that could be an area of future investment. Covered by this issue here: #4718
