### ISSUE TITLE
Finish Development of react-native-gesture-handler C++ Implementation

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8396]
# Finish Development of react-native-gesture-handler C++ Implementation

## Basic Info
- Module Repo URL: [link to repo](https://github.com/software-mansion/react-native-gesture-handler)
- Target version: 0.63
- [X] Issue exists on module repo ([link](https://github.com/software-mansion/react-native-gesture-handler/issues/382))
- [ ] Module has a Legacy/C# implementation

[PR](https://github.com/software-mansion/react-native-gesture-handler/pull/1409) open now with most of the implementation needed for GestureHandler. However, when added to a sample project we have been unable to get a response out of the module. Needs some additional dev work to carry it over the finish line. 

## Which app/customer is requesting this module?
No requests for now, but is a dependency of react-navigation.

Connected to #4140

**Comment by chrisglein** [comment]
Idea from @acoates-ms , this could be an issue with the import of the UI manager. Which was a difference between 63 and 64. See this PR: https://github.com/software-mansion/react-native-gesture-handler/pull/1528
Worth checking again with that merged (and published). No new releases since February, so the repo owner may need to be pinged and we can test with a private drop in the meantime.

**Comment by Flam3rboy** [comment]
Any updates on this?

**Comment by maskaravivek** [comment]
It would be great to get this implemented

**Comment by chrisglein** [comment]
Partial implementation exists int he above PR. Closing this issue as not in plan. Not that this module _shouldn't_ receive a complete Windows implementation, but it makes more sense to track that request on the module's repo rather this repo (where the source doesn't live).
