### ISSUE TITLE
Views with borderRadius apply transform to nested views twice

### ISSUE THREAD

**Issue by rozele** [microsoft/react-native-windows#8420]
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add the following example to RNTester's TransformExample:
```js
  {
    title: 'Translate with corner radius',
    description: 'Translate with corner radius',
    render(): Node {
      return (
        <View style={styles.container}>
          <View
            style={{
              backgroundColor: 'blue',
              borderRadius: 4,
              width: 100,
              height: 100,
              alignItems: 'center',
              justifyContent: 'center',
              transform: [{translateX: 50}],
            }}>
            <View
              style={{
                backgroundColor: 'cyan',
                width: 50,
                height: 50,
                alignItems: 'center',
                justifyContent: 'center',
              }}>
              <Text style={{color: 'white'}}>X</Text>
            </View>
          </View>
        </View>
      );
    },
  },
```
2.

## Expected Results
I expect the transform behavior to match what occurs when I do not set the `borderRadius`, which does not apply the transform to children twice.

## Snack, code example, screenshot, or link to a repository:
See example code above, which can be easily injected into any playground app or RNTester.

Here is what a transform with child views looks like without a `borderRadius`:
![image](https://user-images.githubusercontent.com/1106239/129392607-68cef441-1849-49bd-818d-58a75f9de317.png)

Here is what the transform looks like when a `borderRadius` is applied to the same view that also has a `transform`:
![image](https://user-images.githubusercontent.com/1106239/129392732-903ae97f-23bb-49e6-afb0-85c086b1e89f.png)

Another interesting issue, possibly unrelated, is that setting `borderRadius` seems to also implement `overflow: hidden` behavior. I suspect the `borderRadius` implementation just creates a custom clipping geometry.

Please note, this applies to any type of transform, so if I set `scaleX` to 2, I expect the outer and inner views to maintain the same width ratio, however the inner view doubles the scale and ends up matching the width of the outer view:
![image](https://user-images.githubusercontent.com/1106239/129392959-bef8793c-712f-40a3-afb9-01deee884a7b.png)

**Comment by rozele** [comment]
A reasonably simple work around is to just ensure that you don't apply the `borderRadius` and `transform` props on the same view, e.g.:
```js
  {
    title: 'Translate with corner radius',
    description: 'Translate with corner radius',
    render(): Node {
      return (
        <View style={styles.container}>
          <View style={{transform: [{translateX: 50}]}}>
            <View
              style={{
                backgroundColor: 'blue',
                borderRadius: 4,
                width: 100,
                height: 100,
                alignItems: 'center',
                justifyContent: 'center',
              }}>
              <View
                style={{
                  backgroundColor: 'cyan',
                  width: 50,
                  height: 50,
                  alignItems: 'center',
                  justifyContent: 'center',
                }}>
                <Text style={{color: 'white'}}>X</Text>
              </View>
            </View>
           </View>
        </View>
      );
    },
  },
```
![image](https://user-images.githubusercontent.com/1106239/129394535-867619f2-1225-4575-a1f6-d7b1e9be0150.png)

**Comment by Aashu-Dubey** [comment]
I recently faced the same issue in rn-windows version 0.70.6, though in my case it was happening in both with or without borderRadius, for example this code sample
```js
    <View
      style={{
        width: 140,
        height: 50,
        backgroundColor: 'red',
        transform: [{ translateX: 80 }],
      }}
    >
      <Text
        style={{
          color: 'white',
          fontSize: 16,
          fontWeight: 'bold',
          backgroundColor: 'blue',
        }}
      >
        react-native-windows
      </Text>
    </View>
``` 
will show like this
<img width="287" alt="image" src="https://user-images.githubusercontent.com/46301285/203865112-7cc7c2da-7314-4292-9e4d-a21d8781a7ac.png">

but the overflow issue does happen with me too.
this is how it look after applying `borderRadius: 12` to above View container
<img width="263" alt="image" src="https://user-images.githubusercontent.com/46301285/203865243-5f3b8643-b794-4f38-a5ea-f17ab2c65686.png">

but the workaround you mentioned does work
```js
    <View style={{ transform: [{ translateX: 80 }] }}>
      <View
        style={{
          width: 140,
          height: 50,
          borderRadius: 12,
          backgroundColor: 'red',
        }}
      >
        <Text
          style={{
            color: 'white',
            fontSize: 16,
            fontWeight: 'bold',
            backgroundColor: 'blue',
          }}
        >
          react-native-windows
        </Text>
      </View>
    </View>
```
<img width="296" alt="image" src="https://user-images.githubusercontent.com/46301285/203865738-6b8ee9be-bcd0-446f-9d07-7f16dcd3d676.png">

Here I also noticed that, in earlier case, View container didn't translateX completely based on applied value 80, as you can see with the difference in left spacing for both examples (red background).

this is a minimal example, the real implementation where I faced this issue is [this one](https://github.com/Aashu-Dubey/youtube/blob/react-native/rn_youtube/src/animatedToolbar/ToolbarAnimated.tsx), and to workaround this I had to apply reverse transform to nested views (Icon, Text) [here](https://github.com/Aashu-Dubey/youtube/blob/react-native/rn_youtube/src/animatedToolbar/ToolbarAnimated.tsx#L166).
