### ISSUE TITLE
Autolinking Overwrites WinUI2xVersion Set in ExperimentalFeatures

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#8431]
Unpackaged applications require a special WinUI package, as is currently used in Playground-Win32. Playground currently disables autolinking, which has its own logic to set WinUI packages in `packages.config`. If autolinking is enabled, it will rewrite the WinUI package in `packages.config` with the stock version.

E.g. this is the result of running autolinking for playground-win32 (or building it from the CLI instead of VS) 
![image](https://user-images.githubusercontent.com/835219/129693894-da974aea-68e4-4fc8-af27-ce557e198a78.png)

**Comment by asklar** [comment]
I think this is because there is no ExperimentalFeatures.props / entry for WinUI which should be the source of truth. Fix should be to add the props file with the override.

**Comment by chrisglein** [comment]
Is this an issue with autolinking or an issue with how playground is configured? Is autolinking missing some read of ExperimentalFreatures.props?

Scenario here: unpackaged app with autolinking that wants WinUI 2.

**Comment by jonthysell** [comment]
Autolinking gets the version from `WinUI.props`. Since playground overrides this, autolinking messes up the file.

Unfortunately playground is a bad example to test/guard against. We have three separate apps all co-locating their solution files in one folder, which means they share an `ExperimentalFeatures.props file`, which **conditionally** sets the WinUI2 version for only one of the playground apps.

So we can't just read what's in `ExperimentalFeatures.props` - the version we get will only be "right" for one of the playgrounds, not any of the others. We can't possibly replicate all of the msbuild logic to make sure that all of the playground apps can run autolinking without messing up the files.

The strangeness of playground is why it has autolinking disabled.

The **best** we could do would be to read the version from `ExperimentalFeatures.props` and *assume* that it is the final value, and use it, otherwise fallback to the value in `WinUI.props`. As said, users could specify this version elsewhere (or with conditionals) and we wouldn't detect it, and even then, playground (unpackaged win32) would be fixed, but playground win32 and uwp would both then be broken.

**Comment by jonthysell** [comment]
I have a fix, but not sure this is critical for 0.66 moving to 0.67. We can backport the change later if required by customers.
