### ISSUE TITLE
0.65 Community Module Template Solution Cannot Be Opened

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-windows#8467]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 6.0.0
2. `npx react-native info`:

System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 51.24 GB / 63.84 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    Visual Studio: 16.9.31529.145 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_282 - C:\Program Files\OpenJDK\openjdk-8u282-b08\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.0 => 0.65.0
    react-native-windows: ^0.65.0 => 0.65.0
  npmGlobalPackages:
    *react-native*: Not Found

- Target Platform Version(s): 10.0.19041.0
- Target Device(s): Desktop
- Visual Studio Version: 2019
- Build Configuration: Either

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow steps on website to generate a fresh native module using RN and RNW 0.65
2. Open sln in Visual Studio.

## Expected Results
Expect all projects to load. Instead module project and some React Native project fails to load. 

## Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/34109996/130519469-0bffc6f3-5582-405d-8828-1eb71c6e8b44.png)
![image](https://user-images.githubusercontent.com/34109996/130519516-f8d8cc97-827b-40ee-841c-08284859fc96.png)

**Comment by NickGerleman** [comment]
Looks legit. https://github.com/microsoft/react-native-windows/blob/0.65-stable/vnext/template/shared-lib/proj/ExperimentalFeatures.props

**Comment by NickGerleman** [comment]
FYI @asklar it looks like this change was responsible. This would be best to fix as soon as possible given impact. https://github.com/microsoft/react-native-windows/commit/3a875c2bf27354dc0b5cf96a291ab9105bf3a774#diff-b4b88e089cfc6c4d1993da50899647091c22ffc12d9b03e900d17ebe058e7743

**Comment by asklar** [comment]
IIRC the idea of that logic was that libraries should use whatever the app wanted to use (e.g. it is up to the app whether to use Hermes, or use a different SDK, or use WinUI3). 
Looking at the code now, the lookup of the app's ExperimentalFeatures.props from the module's EF.props seems wrong. For example:

react-native-gallery\node_modules\react-native-webview\windows
This directory has the module's EF. It looks for a windows\EF.props and fails, so it tries the parent folder.
Now it tries react-native-gallery\node_modules\react-native-webview and looks for a windows\EF.props and finds itself, instead of bubbling up and eventually finding the app's.

Either it needs to start 2 levels higher (so that the lib EF.props doesn't end up finding itself), or probably more correctly, it should use the SolutionDir directly *and* check that the file path it ended up with isn't the same file (to guard against running into this problem when opening a module's sln again).

It's curious that this isn't a problem when building in the CLI / msbuild but VS flat out refuses to open the projects.

**Comment by NickGerleman** [comment]
I think Jon later just removed the library ExperimentalFeatures.props

SolutionDir for a library will still point towards the app solution when building an app, so we get the app ExperimentalFeatures.props automatically. I think the only time the ExperimentalFeatures.props in the module template is read is at dev time (since that is where the module solution would be used).

It's a good question about why our validation didn't catch this. Would be worth taking at our library init tests to double check they are doing what we expect, or fill in any gaps.

**Comment by NickGerleman** [comment]
I think backporting would make sense if we isolate to just the ExperimentalFeatures.props template change.

The current backport PR bundled some more in and is quite large. I do not think that would be safe.

**Comment by chrisglein** [comment]
> Yeah, I think the change in #8402 is righteous: https://github.com/microsoft/react-native-windows/pull/8402/files#r687007640
> Jon did want to port this to 0.65 but we thought it would be too disruptive since it didn't get much bake time: #8428
> But... what was in the 0.65 branch didn't get tested enough either :-/
> Should we revisit that decision? @chrisglein Chris Glein FTE

@asklar @NickGerleman @jonthysell Sounds like the options are to take a targeted subset of the PR or the whole thing? What do we think? It was a larger change that hadn't had a long bake time, but if we're in a broken state and we feel like we can give it (or have given it) enough coverage then backporting it can be an option.

**Comment by NickGerleman** [comment]
https://github.com/microsoft/react-native-windows/pull/8472 fixes the issue

**Comment by jonthysell** [comment]
> It's a good question about why our validation didn't catch this. Would be worth taking at our library init tests to double check they are doing what we expect, or fill in any gaps.

Our validation didn't catch this because we don't validate that a new lib project can actually be consumed by an app. The lib template builds fine on it's own.

The only way to test this properly would be to:
1. Create a new lib project.
2. Build and publish to veraddacio
3. Create a new app project
4. Add dependency on lib project
5. Build new app project (with run-windows in order to get autolinking)
