### ISSUE TITLE
Project build successfully but when running it appears blank white screen (Existing react native project)

### ISSUE THREAD

**Issue by kobagapu** [microsoft/react-native-windows#8549]
## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:0.63.4
2. `react `:  17.0.2
3. visual studio version:16.11.2
4. Node : 14.17.6

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.   npx --legacy-peer-deps react-native-windows-init
2.  npx react-native run-windows

## Expected Results
Build the project successfully with  npx react-native run-windows  metro server also loading with 100% but in browser app launch  with blank white screen it does not reload it visible only white screen please help me

**Comment by chrisglein** [comment]
0.63.4 is a bit old at this point (0.65 is the current version now). Is there a reason you're still on that version? You mention in the title you have an existing react native project so maybe that's why?

There's a more detailed environment info command that'll the bot will provide below. Can you run that?

Does your existing app have many community module dependencies? Not all of those are available on windows, so it'd be helpful to know more about this project.

**Comment by taduyde** [comment]
the same issue. any update for this?

**Comment by chrisglein** [comment]
Duplicate of #10255
