### ISSUE TITLE
New project templates should include a .gitattributes file to prevent EOL conversions

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#8590]
This is related to #8530. It was right to fix autolinking to support modifying solution files with LF or CRLF line endings, because VS doesn't discriminate against either. However, all of the native template files are set to the "default" EOL for the file type according to VS, and while our templating code maintains the EOL of the file as it appears on disk, it's easy and common enough for the EOLs to be changed when checked in to git.

Adding a .gitattributes file to the windows folder of the template, targeting the VS filetypes we add (cpp, h, cs, props, vcxproj, csproj, sln) could help mitigate cross-plat devs hitting future issues.

**Comment by chrisglein** [comment]
Current template does not create a .gitattributes file. So that'd need to be added. And it'd need to not trample the other platforms, so it'd be in the Windows folder specifically. Once we have the file, adding the right attributes for this should be straightforward.

**Comment by TatianaKapos** [comment]
@chrisglein Closing due to discussions of:
- Not wanting to claim any further prescriptiveness of template files since our template files are large and prone to fragmentation.
- React-native core doesn't require or push these kind of requirements.
- Our tooling has been since fixed to work with different line endings.
