### ISSUE TITLE
Apps created in 0.65 do not build-deploy in VS

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#8756]
1. npx react-native init rn65
2. cd rn65
3. npx react-native-windows-init --overwrite
4. open windows\rn65.sln
5. F5

expected: app builds then deploys
actual: app fails to build:

![image](https://user-images.githubusercontent.com/22989529/135386700-d47bb80d-e472-486d-b5f8-4e39545fa7d6.png)

**Comment by chrisglein** [comment]
Error from the image:
```Certificate could not be opened: rn65_TemporaryKey.pfx```

There have been changes to the certificates, but those weren't intended to be in 0.65. But changes to `init` would apply to older versions. (@chiaramooney FYI to validate that this didn't hit older versions).

Questions:
- Do you need a certificate for a Debug build?
- We're supposed to have validation for this scenario. Why wasn't it caught?
- Does this also happen on 0.66 or main?
- Are there issues with path resolution of tools for creating a certificate?

**Comment by chrisglein** [comment]
@asklar to validate the repro environment
@chiaramooney  to check on a couple of the questions above

**Comment by chiaramooney** [comment]
Looks like last publish for react-native-windows-init was 23 days ago. Change to remove certs was merged 8 days ago, so this bug is separate from template change. This does highlight though that once the template alteration has been published we will need to backport a portion of the changes in #8672 so the v0.XX templates are compatible with react-native-window-init.

To my knowledge, a certificate should not be needed for a Debug build unless the msbuild prop AppxPackageSigningEnabled is set to true in the app's vcxproj.

We do have testing for app creation and running in the CLI for both release (signed and unsigned) and debug in ADO. Should investigate what is different between this case and the case we hit in the pipeline which has been successful. 

_Investigating other questions now..._
