### ISSUE TITLE
Non-SolidColorBrush brushes don't update cached values on theme change

### ISSUE THREAD

**Issue by DrewHigginsMSFT** [microsoft/react-native-windows#8861]
### Problem Description

We have some custom acrylic brushes defined in our app's resource dictionary that we use in JS code using the PlatformColor helper. When the user changes their Windows theme to a high contrast theme, we have solid color brushes defined for that theme type to switch to. However, due to the caching RNW does, these new brushes aren't used until our app is restarted unless they are solid color brushes in every theme type:
https://github.com/microsoft/react-native-windows/blob/main/vnext/Microsoft.ReactNative/Utils/ValueUtils.cpp

### Steps To Reproduce

1. Add a LinearGradient, Acrylic, or other non-SolidColorBrush to an app's resource dictionary
2. Add another brush in the resource dictionary for the HighContrast theme with the same name that is a SolidColorBrush
3. Add a `<View />` component in the app with a style applying that brush as the background color
4. Open the app, then change the Windows theme to a high contrast theme

### Expected Results

The brush changes to the SolidColorBrush defined above

### CLI version

6.1.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 111.93 GB / 127.71 GB
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31702.278 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: 6.1.0 => 6.1.0
    react: 17.0.2 => 17.0.2
    react-native: 0.64.2 => 0.64.2
    react-native-windows: 0.64.14 => 0.64.14
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

**Comment by DrewHigginsMSFT** [comment]
In our specific use case (the Xbox app), we have a provider component that re-renders consumers when the theme changes by updating an prop representing the theme type (light/dark/HC) in case the components have styles that need to adjust on the JS side.

**Comment by aschultz** [comment]
@asklar @acoates-ms The problem we ran into (and are currently patching around) is that the BrushCache code only updates its mapping if both the old and new brushes are SolidColorBrush. 

```
  struct BrushCache {
    std::map<winrt::hstring, xaml::Media::Brush> m_map;
    winrt::Windows::UI::ViewManagement::UISettings m_uiSettings{ nullptr };
    BrushCache() {
      m_map = {
          {L"SystemAccentColor", {nullptr}},
          {L"SystemAccentColorLight1", {nullptr}},
          {L"SystemAccentColorLight2", {nullptr}},
          {L"SystemAccentColorLight3", {nullptr}},
          {L"SystemAccentColorDark1", {nullptr}},
          {L"SystemAccentColorDark2", {nullptr}},
          {L"SystemAccentColorDark3", {nullptr}},
          {L"SystemListAccentLowColor", {nullptr}},
          {L"SystemListAccentMediumColor", {nullptr}},
          {L"SystemListAccentHighColor", {nullptr}} };

      m_uiSettings = winrt::Windows::UI::ViewManagement::UISettings();
      auto dq = winrt::dispatching::DispatcherQueue::GetForCurrentThread();
      m_uiSettings.ColorValuesChanged([this, dq](auto&& sender, auto&& args) {
        dq.TryEnqueue([this]() {
          for (auto& entry : m_map) {
            winrt::IInspectable resource{ winrt::Application::Current().Resources().Lookup(winrt::box_value(entry.first)) };
            if (auto oldSCBrush = entry.second.try_as<xaml::Media::SolidColorBrush>()) {
              if (auto newSCBrush = resource.try_as<xaml::Media::SolidColorBrush>()) {
                oldSCBrush.Color(newSCBrush.Color());
              }
            }
          }
          });
        });
    }
```

Changing this to handle other brush types would address our issue as any freshly-rendered content could then pick up the new values.

Our naive approach that is currently working is:
```
if (auto oldSCBrush = entry.second.try_as<xaml::Media::SolidColorBrush>()) {
    if (auto newSCBrush = resource.try_as<xaml::Media::SolidColorBrush>()) {
        oldSCBrush.Color(newSCBrush.Color());
        return;
    }
}
// Fall back to just adding the brush to the map
if (auto newBrush = resource.try_as<xaml::Media::Brush>())
{
    m_map.insert_or_assign(entry.first, newBrush);
}
```

I could put out a PR with this change, but I'm not clear on why the existing code tries to copy values from the new brushes instead of just storing the brush instance. Is this to ensure that each thread-local BrushCache has separate Brush instances?

**Comment by asklar** [comment]
If we just replaced the brushes in the cache instead of the rgb values in the brushes, then ui elements referencing existing brushes would not update.

**Comment by aschultz** [comment]
Gotcha. So the current behavior is:

- If old and new brushes are SolidColorBrush, all existing and new UI elements using those brushes get the new color
- Otherwise, all existing and new UI elements are stuck with the old color until app reboot.

The (naive) change I proposed would give:

- If old and new brushes are SolidColorBrush, all existing and new UI elements using those brushes get the new color
- Otherwise, existing elements are stuck with old brush, new elements get the new brush.

That's not ideal, but it's an improvement. At least then the app has some degree of workaround available in the JS layer to get the new values to show instead of requiring an app restart.

A more thorough fix would be to have the various RNW native components keep track of whether they're using "windowsbrush" and re-fetch/re-apply the brush when signaled (either by ColorValuesChanged or some future DynamicResource implementation).
