### ISSUE TITLE
Create sample C++ app for winappsdk

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9143]

**Comment by AgneLukoseviciute** [comment]
This is a good candidate for documenting the migration process of UWP -> WinAppSDK if we use one of the existing samples or branch off of one

**Comment by chrisglein** [comment]
In order to help parallelize, the sample app doesn't need to be built from the CLI. A manual app is sufficient.
Purpose of this app (initially): a test app? best practices (good for copying)? testing upgrades?
Which existing UWP sample app should we target?
Note this is _not_ about upgrading gallery (#9140) and not about creating and E2E test app (#9144).

Answer: This is the manual, non-automatic example app that others can copy. To be eventually revisited when there is a CLI generated app. It can be a Hello World app as a baseline (but tackling RNTester functionality would have upside for sure).

Build a WinAppSDK app, try to host a React Native root in there, check it in.

**Comment by jonthysell** [comment]
Do you think this will make 0.69 or should it be moved to 0.70?

**Comment by AgneLukoseviciute** [comment]
This one is essentially done, but relies on https://github.com/microsoft/react-native-windows/issues/8132 to be working e2e so I'm moving to 0.70
