### ISSUE TITLE
Upgrade to WinUI 2.8

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9196]
### Summary

We currently target WinUI 2.7. When WinUI 2.8 releases we'll want to upgrade.

### Motivation

WinUI 2.8 brings improvements, especially in that adds in support for WebView2.

**Comment by jonthysell** [comment]
We'll probably want to run a test and see how our code handles running on the 2.8 prerelease: https://www.nuget.org/packages/Microsoft.UI.Xaml/2.8.0-prerelease.210927001

This will also help validate the logic we added in https://github.com/microsoft/react-native-windows/pull/9195 works properly.

**Comment by chrisglein** [comment]
Notes from planning poker:
> As this process has been done many times it's been more streamlined over time.
WinUI2.8 will have some WebView jazz there may be more spice here. May be some ambiguity about what version here (and prerelease version for playground).
Actual steps are pretty quick, but there's a "what will break?" buffer. E.g. the original 2.7 release wasn't store shippable, which wasn't noticed until later.

**Comment by chrisglein** [comment]
2.8 is still in prerelease, right? [v2.8.0-prerelease.220118001](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.8.0-prerelease.220118001)
Not ready for us to move for 0.68.

**Comment by chiaramooney** [comment]
@chiaramooney Yes that's correct!

**Comment by jonthysell** [comment]
It looks like WinUI 2.8 is still in prerelease, moving to 0.70.

**Comment by chrisglein** [comment]
WinUI 2.8 has some implications on min SDK version. We're not going to consider that for 0.70 as a result until we know when/how we want to integrate that. Moving out for consideration in 0.71.

**Comment by chiaramooney** [comment]
Capturing considerations from offline thread:

- The change in min SDK version is due to a change in MSIT internal policy surrounding support. 

MOVE TO 2.8
- Unclear how many customers would fall into the bucket of losing support / how many customers want to be able to have their min version remain at its current value. The assumption is this number/percentage is small.
- Historically, we have always stayed in line with WinUI. It means we have the latest control set of WinUI and that we are not reliant on backports for bug fixes. 
- Removes extra hurdle to customers using WebView2. Currently, WebView2 customers have to always update their experimental features. With moving to WinUI2.8 cutomers on 71+ will not have to use the workaround.
- One proposal is to wait until we move to VS2022. VS2022 defaults to 17763 as the min version, but it can be changed to be lower.

REMAIN AT 2.7
- Moving to WinUI 2.8 will mean that a scenario we previously supported, will no longer available. 
- If customers want WinUI 2.8, they always have the ability to customize their WinUI version in ExperimentalFeatures; we do not need to be on 2.8 for our customers to have access to it.
- If/When we do move to WinUI 2.8, we will want to make sure to call out this change in the release notes and maybe even a blog post to make developers aware of this breaking change.
- Modules will need to have their min version bumped as well if we want them to be usable in 71+ apps. Getting ahold of repo maintainers has been an issue in the past. May mean that we lose some modules.

**Comment by chiaramooney** [comment]
Note after attempting to upgrade Gallery to WinUI2.8 upgrade was unsuccessful. Error produced that the targetplatformminversion in the Microsoft.ReactNative package is too low even when the app itself has a valid targetplatformminversion. Adding this as a point of consideration for migration to 2.8. Is there a way to override the targetplatformminversion of RNW from the app?

**Comment by jonthysell** [comment]
@chiaramooney Can you open a bug that we do not consistently allow app/module developers to specify/override `TargetPlatformVersion` and/or `TargetPlatformMinVersion` (for C# projects ) and `WindowsTargetPlatformVersion` and/or `WindowsTargetPlatformMinVersion` (for C++ projects)?

**Comment by chiaramooney** [comment]
No decision yet on whether we will be migrating to WinUI2.8 in the platform. With shift to VS2022, might be best to hold off on this change until the next release.

Bumping to 72.

**Comment by chiaramooney** [comment]
Flagging before cutting v0.72. Do we want this in the new RNW version?

**Comment by chrisglein** [comment]
Let's move to 2.8 in 0.72.
