### ISSUE TITLE
RNW needs to set the default value of XHR.withCredentials to false in the platform bundle

### ISSUE THREAD

**Issue by weidezhong-msft** [microsoft/react-native-windows#9246]
### Problem Description

RN's XHR implementation sets the default value of withCredentials to true. This is different from the browser and can unexpectedly leak cookies and other credentials for CORS requests.

The proposal is to overwrite it to false in the platform bundle.

react-native/XMLHttpRequest.js at ef5ff3e055482771cbe866d4961ee2d0a9e00e45 · facebook/react-native · GitHub

### Steps To Reproduce

var req = new XMLHttpRequest();
req.open("GET", "http://www.example.org/example.txt");
req.send();

Notice req.withCredentials is true.

### Expected Results

req.withCredentials is false by default.

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by NickGerleman** [comment]
@weidezhong the devmain HTTP client currently does not share code with the open-source version we have in this repo.

cc @JunielKatarn

**Comment by acoates-ms** [comment]
The default value is currently in JS not in native.

Note this bug is for the win32 platform, not the windows one.

https://github.com/facebook/react-native/issues/14063 has a long discussion from when RN tried to make this change in core.  -- Given how that went, I do not believe we can change the default in the windows platform.

Perhaps we can make the default configurable from the native side, but the default has to remain.

**Comment by chrisglein** [comment]
We could add an app global switch to core, which would allow apps to customize this without diverging the defaults from RN core and also not require that each callsite get this right.
