### ISSUE TITLE
add a style checker that disallows unsorted using statements

### ISSUE THREAD

**Issue by matthargett** [Microsoft/react-native-windows#929]
Based on @rozele feedback in code reviews, add a style checker that will fail the build if using statement are unsorted. It looks like CodeMaid is the one that implements his preferred style.

**Comment by rozele** [comment]
I think this is a great time to talk about what people prefer.  I chose sorted namespaces because it is a sunk cost and it's consistent with what's already in the solution.  However, if people have strong leanings towards a different sorting, e.g., ReSharper, or something that complies with Microsoft.AllRules CodeAnalysis, I'm happy to consider any alternatives.

**Comment by matthargett** [comment]
Plain alpha sort, grouped by static/non-static makes sense to me. I was surprised StyleCop didn't have a rule for that and wasn't configurable. I think ReSharper's sort is configurable, IIRC, so that's not a real problem AFAIK.

**Comment by rozele** [comment]
Agree that we should enable some code analysis rules, but closing for now.
