### ISSUE TITLE
Bump Minimum Node from 12 to 14

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#9474]
We target Node 12 as a minimum supported version in various config files (package.json, babel config), along with unit tests, which validate against 12, 14, and 16. RN core 0.68+ now [requests](https://github.com/facebook/react-native/commit/f1488db109d13e748b071c02b40e90cdca1cc79d) Node >= 14, so we should target that as our new minimum.

**Comment by chrisglein** [comment]
Related
#8982 
#8345
#8982

**Comment by jonthysell** [comment]
@NickGerleman Is it okay to build RNW (`yarn build`) on a later version of Node (>= 14) and then consume that code in a lower version (12)?

Since RNW requires Node 14 to build since 0.65, should we remove node 12 support/testing all the way back to 0.65? I mean, if a customer hits an issue in 0.65-0.67 that only repros on Node 12, we wouldn't be able to test it as we'd have Node >=14 on our machines in order to build.

**Comment by NickGerleman** [comment]
We can build on newer versions and run on older versions. An example where we do this intentionally is running UTs against our node packages. We build with the image-provided Node version (16), then perform tests with Node 12, 14, and 16. Most of the code we generate is emitted by the TypeScript compiler `tsc`, where we configure how to transpile the code in the `tsconfig` file. Apart from TypeScript compiler, we generate code at runtime using Babel in certain scenarios (e.g. UTs). Its configuration is controlled by `packages\@rnw-scripts\babel-node-config\babel.config.js`. It is currently configured to produce code compatible down to Node 12.
