### ISSUE TITLE
init with --useDevMode no longer works

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-windows#9691]
The instructions in the wiki for using the RNW to test no longer work with the introduction of the `@rnw-scripts/metro-dev-config`
I've updated the instructions to manually run `yarn link`  in the `packages\@rnw-scripts/metro-dev-config` folder and then `yarn link @rnw-scripts/metro-dev-config`  in the app. However this likely should be done by the init CLI when using `--useDevMode`

Even after doing the manual step, we fail to resolve packages with metro, it looks like we now have dependencies on rnx-kit in the RNW repo, I'm not sure how the apps would be able to consume those dependencies when using --useDevMode.

Once we fix this, we should probably validate in CI that --useDevMode works, it's important we keep our inner loop working.

**Comment by chrisglein** [comment]
Creating the project works.
Building works.
Running does not work (metro is failing - `useDevMode` changes it to a metro config that doesn't work)

[Details on `useDevMode` here](https://github.com/microsoft/react-native-windows/wiki/Contributing-to-the-CLI#testing-changes-made-to-our-other-packages-using---usedevmode)

**Comment by NickGerleman** [comment]
There are a couple of easy options to fix this.

1. Revert the change in the --useDevMode metro config. It's arguably better to keep the template more stock, to resemble the user experience, but we need to do special things to make linked packages work already. 

2. Fix the resolution logic. Instead of making the devmode config look with its search rooted in the user project (this is what it does right now), have it instead first resolve the symlinked RNW package, and start the search from there.
