### ISSUE TITLE
BinSkim Analysis fails for Desktop Arm64 builds

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9964]
### Problem Description

BinSkim Analysis is failing for Desktop Arm64 builds, both Debug and release, with:

```
Analysis did not complete due to one or more unrecoverable execution conditions.
Unexpected fatal runtime condition(s) observed: ExceptionLoadingPdb
```

### Steps To Reproduce

CI Logs: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=312413&view=logs&j=1753506a-98b8-5bc5-1546-f62521f93031&t=60ad2509-65b2-5d30-1c15-8f990d8af2e9

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by chrisglein** [comment]
@AgneLukoseviciute can you take a look?

**Comment by AgneLukoseviciute** [comment]
Binskim is complaining that the PDB for v8jsi.dll is stripped. Thought this was strange considering x64 and x86 are fine, syncing with someone on the BinSkim team to see if this might be a known issue on their end.

**Comment by AgneLukoseviciute** [comment]
Digging around V8jsi I see that they do in fact strip the pdb files for ARM64 only "due to size limitations", see https://github.com/microsoft/v8-jsi/blob/1875152450218bd27a4b8f8cb2aa776dc09daec9/scripts/build.ps1#L130

@dannyvv I see you added BinSkim for desktop with https://github.com/microsoft/react-native-windows/pull/9575. considering the v8jsi.dll is tested through binskim for x64 and x86 already, I'm thinking we should be okay to skip it in ARM64. Any concerns with that?

**Comment by jonthysell** [comment]
Ping @dannyvv

**Comment by AgneLukoseviciute** [comment]
Synced offline, got signoff from Danny :)
